/**
 * Collection Gaming & Pop : textes originaux créés pour TypeWav.
 * Évoque la culture du jeu vidéo, du retro gaming et de l'informatique
 * avec un vocabulaire propre à cette culture.
 *
 * Spec : docs/specs/06-content.md
 * Règle : textes originaux TypeWav (✅ autorisé par la spec)
 */

import type { CollectionConfig } from '@typewav/types';

export const gamingCollection: CollectionConfig = {
  id: 'gaming',
  name: 'Gaming',
  nameEn: 'Gaming',
  description:
    'Phrases et paragraphes inspirés de la culture du jeu vidéo : originaux TypeWav.',
  language: 'multi',
  recommendedTheme: 'arcade',
  isPremium: false,
  texts: [
    {
      id: 'gam-fr-01',
      content: `Le compteur XP grimpe. Chaque frappe juste ajoute un point. Chaque erreur efface une vie. La console ne ment jamais.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 1,
      wordCount: 20,
      charCount: 116,
      tags: ["gaming","arcade","xp"],
    },
    {
      id: 'gam-fr-02',
      content: `Respawn dans trois secondes. Le boss attend au niveau suivant. Tu as quinze points de vie et un seul sort magique restant.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 22,
      charCount: 122,
      tags: ["rpg","boss","vie"],
    },
    {
      id: 'gam-fr-03',
      content: `Speedrun en cours. Le record mondial est à deux minutes quarante-trois. La hitbox était imprécise mais le saut passait quand même.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 130,
      tags: ["speedrun","record","plateforme"],
    },
    {
      id: 'gam-fr-04',
      content: `Pixel art, huit couleurs, quatre bits de son. La limitation était une contrainte créative. La contrainte était une invitation.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 126,
      tags: ["pixel art","retro","8-bit"],
    },
    {
      id: 'gam-fr-05',
      content: `Le lag input rend chaque frame incertaine. Un ping élevé est l'ennemi du joueur compétitif. La connexion, c'est le fondement.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 20,
      charCount: 125,
      tags: ["online","compétitif","réseau"],
    },
    {
      id: 'gam-fr-06',
      content: `Inventaire plein. Droppez un objet pour en ramasser un autre. Le choix est cruel quand tout est rare.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 1,
      wordCount: 18,
      charCount: 101,
      tags: ["rpg","inventaire","loot"],
    },
    {
      id: 'gam-fr-07',
      content: `Le monde ouvert s'étend à l'infini. Les quêtes secondaires s'accumulent. L'histoire principale attend que tu aies le courage de la finir.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 137,
      tags: ["open world","quête","narration"],
    },
    {
      id: 'gam-fr-08',
      content: `Roguelike : chaque mort efface la partie. Chaque partie enseigne quelque chose. La progression réelle se fait dans la mémoire du joueur.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 22,
      charCount: 136,
      tags: ["roguelike","mort","progression"],
    },
    {
      id: 'gam-fr-09',
      content: `La cartouche souffle. Trois fois. La console redémarre. L'écran s'illumine. Tout recommence, comme si de rien n'était.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 1,
      wordCount: 17,
      charCount: 118,
      tags: ["retro","cartouche","nostalgie"],
    },
    {
      id: 'gam-fr-10',
      content: `Combo x32. Le multiplicateur explose. La musique s'accélère. Les doigts ne suivent plus. C'est exactement comme ça que ça devrait se terminer.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 22,
      charCount: 142,
      tags: ["combo","rythme","arcade"],
    },
    {
      id: 'gam-fr-11',
      content: `La barre de vie descend doucement. Un potion d'urgence reste. Ce n'est pas pour maintenant.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 1,
      wordCount: 15,
      charCount: 91,
      tags: ["rpg","vie","potion"],
    },
    {
      id: 'gam-fr-12',
      content: `Easter egg trouvé après dix-sept heures de jeu. Le développeur a laissé son nom gravé dans une salle secrète.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 109,
      tags: ["easter egg","secret","exploration"],
    },
    {
      id: 'gam-fr-13',
      content: `Le serveur est en maintenance. Retour dans vingt minutes. Les joueurs attendent depuis deux heures.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 15,
      charCount: 99,
      tags: ["serveur","maintenance","attente"],
    },
    {
      id: 'gam-fr-14',
      content: `Tir précis. Headshot. Le ratio grimpe. La concentration ne faiblit pas. C'est ce qu'on appelle un bon run.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 106,
      tags: ["fps","headshot","ratio"],
    },
    {
      id: 'gam-fr-15',
      content: `Mode coopératif. Quatre joueurs. Un seul objectif. La communication fait la différence entre la victoire et l'échec.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 116,
      tags: ["coop","équipe","communication"],
    },
    {
      id: 'gam-fr-16',
      content: `Le crafting est une question de patience. Chaque ressource compte. Chaque décision engage l'ensemble de la partie.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 114,
      tags: ["crafting","ressources","stratégie"],
    },
    {
      id: 'gam-fr-17',
      content: `Level design parfait. Chaque corridor mène quelque part. Aucun espace ne se perd. L'architecture du jeu est une œuvre d'art.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 20,
      charCount: 124,
      tags: ["level design","architecture","art"],
    },
    {
      id: 'gam-fr-18',
      content: `Trente heures de jeu. Quarante pour cent complétés. L'open world ne se laisse pas apprivoiser facilement.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 105,
      tags: ["open world","complétion","exploration"],
    },
    {
      id: 'gam-fr-19',
      content: `La bande sonore s'adapte à chaque action. Les basses montent. Le rythme s'accélère. Le corps suit sans le décider.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 19,
      charCount: 114,
      tags: ["bande sonore","musique","immersion"],
    },
    {
      id: 'gam-fr-20',
      content: `Un seul joueur contre cinq. Les probabilités sont claires. Mais les probabilités ignorent la volonté.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 101,
      tags: ["1v5","probabilité","volonté"],
    },
    {
      id: 'gam-fr-21',
      content: `Nouveau record personnel battu. Pas le record mondial. Mais le sien. C'est déjà quelque chose.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 15,
      charCount: 94,
      tags: ["record","personnel","progrès"],
    },
    {
      id: 'gam-fr-22',
      content: `La carte est vide. La brume de guerre couvre tout. Le premier mouvement définit la stratégie entière.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 101,
      tags: ["stratégie","brume","carte"],
    },
    {
      id: 'gam-fr-23',
      content: `Fin du jeu. Générique de fin. Trois ans de développement. Vingt heures de jeu. L'écran noir revient lentement.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 110,
      tags: ["fin","générique","émotion"],
    },
    {
      id: 'gam-fr-24',
      content: `Le mod tourne depuis trois mille heures. La communauté a ajouté plus de contenu que les développeurs d'origine.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 18,
      charCount: 111,
      tags: ["mod","communauté","contenu"],
    },
    {
      id: 'gam-fr-25',
      content: `Quicksave. Quickload. La mort n'est plus la fin. Elle devient une erreur parmi d'autres.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 88,
      tags: ["quicksave","mort","apprentissage"],
    },
    {
      id: 'gam-fr-26',
      content: `L'IA triche. Tout le monde le sait. Personne ne le dit. C'est le contrat tacite du jeu de stratégie.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 100,
      tags: ["ia","triche","stratégie"],
    },
    {
      id: 'gam-fr-27',
      content: `Le mode histoire se termine. Le mode libre commence. Les règles disparaissent. La créativité prend la relève.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 109,
      tags: ["mode libre","créativité","sandbox"],
    },
    {
      id: 'gam-fr-28',
      content: `Trois personnages jouables. Trois histoires parallèles. Un seul monde. La narration non linéaire à son meilleur.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 16,
      charCount: 112,
      tags: ["narration","personnages","parallèle"],
    },
    {
      id: 'gam-fr-29',
      content: `Le bouton A saute. Le bouton B court. La combinaison des deux crée quelque chose d'inattendu.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 16,
      charCount: 93,
      tags: ["contrôles","mécanique","découverte"],
    },
    {
      id: 'gam-fr-30',
      content: `Platine obtenue. Cent pour cent. Les trophées brillent dans la bibliothèque numérique. Personne ne s'en souviendra.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 115,
      tags: ["platine","100%","trophée"],
    },
    {
      id: 'gam-en-01',
      content: `Insert coin to continue. Ten seconds on the clock. High score belongs to a stranger who played here once and never came back.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 23,
      charCount: 125,
      tags: ["arcade","coin-op","high score"],
    },
    {
      id: 'gam-en-02',
      content: `Save file corrupted. Forty hours of progress gone in a single power outage. The world was already memorized anyway.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 5,
      wordCount: 19,
      charCount: 115,
      tags: ["save","loss","memory"],
    },
    {
      id: 'gam-en-03',
      content: `Permadeath means every decision matters. Every corridor, every enemy, every item found on the floor of a dungeon.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 113,
      tags: ["permadeath","roguelike","dungeon"],
    },
    {
      id: 'gam-en-04',
      content: `The frame rate drops to twenty. The physics engine panics. Three NPCs phase through a wall and disappear into the void.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 5,
      wordCount: 21,
      charCount: 119,
      tags: ["bugs","physics","npc"],
    },
    {
      id: 'gam-en-05',
      content: `Side-scrolling at sixty frames per second. Eight enemies incoming from the right. Jump timing is everything. Always was.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 120,
      tags: ["platformer","timing","side-scroll"],
    },
    {
      id: 'gam-en-06',
      content: `The tutorial ends. The game begins. Nobody told you the real rules. You learn them one respawn at a time.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 1,
      wordCount: 20,
      charCount: 105,
      tags: ["tutorial","learning","game design"],
    },
    {
      id: 'gam-en-07',
      content: `Loot drop rate: zero point one percent. Forty-seven hours of grinding. Still no legendary item. This is also a game.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 5,
      wordCount: 20,
      charCount: 116,
      tags: ["loot","grind","rng","mmo"],
    },
    {
      id: 'gam-en-08',
      content: `The final boss has three phases. Each phase harder than the last. You already memorized the pattern. You have done this before.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 22,
      charCount: 127,
      tags: ["boss","pattern","final"],
    },
    {
      id: 'gam-en-09',
      content: `Modders rebuilt the entire engine in two years. The original developers left. The community stayed. That is how games survive.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 5,
      wordCount: 20,
      charCount: 126,
      tags: ["modding","community","preservation"],
    },
    {
      id: 'gam-en-10',
      content: `Cheat code entered. Invincibility activated. The game becomes trivial. And somehow less fun. That was always the lesson.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 120,
      tags: ["cheat","difficulty","design"],
    },
    {
      id: 'gam-en-11',
      content: `Zero HP. Game over. But the memory of that attempt stays. Next time will be different.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 1,
      wordCount: 16,
      charCount: 86,
      tags: ["game over","memory","retry"],
    },
    {
      id: 'gam-en-12',
      content: `Respawn timer counting down. Five. Four. Three. The map is still being studied. Every second is information.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 17,
      charCount: 108,
      tags: ["respawn","timer","strategy"],
    },
    {
      id: 'gam-en-13',
      content: `Server full. Queue position: two hundred and forty-seven. This game must be worth it.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 14,
      charCount: 85,
      tags: ["server","queue","patience"],
    },
    {
      id: 'gam-en-14',
      content: `The silence after a perfect run is different from any other silence. It belongs to you.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 87,
      tags: ["silence","run","excellence"],
    },
    {
      id: 'gam-en-15',
      content: `Cooperative play requires trust. You cover left. I cover right. We move forward together or not at all.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 103,
      tags: ["coop","trust","teamwork"],
    },
    {
      id: 'gam-en-16',
      content: `The health bar depletes slowly. One more room. One more save point. The distance feels infinite.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 96,
      tags: ["health","distance","room"],
    },
    {
      id: 'gam-en-17',
      content: `The currency of this game is time. Forty grinding sessions. One legendary drop. The math never adds up.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 4,
      wordCount: 18,
      charCount: 103,
      tags: ["grind","time","rng"],
    },
    {
      id: 'gam-en-18',
      content: `New patch notes released. The meta has shifted. Everything learned before is now partially wrong.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 97,
      tags: ["patch","meta","learning"],
    },
    {
      id: 'gam-en-19',
      content: `Cutscene begins. Controller down. Story mode engaged. The line between player and character dissolves.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 102,
      tags: ["cutscene","story","immersion"],
    },
    {
      id: 'gam-en-20',
      content: `Achievement unlocked: survived five hundred hours. The game did not thank you. It never does.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 93,
      tags: ["achievement","hours","recognition"],
    },
    {
      id: 'gam-en-21',
      content: `The soundtrack shifts to minor key. The safe zone has ended. Everything ahead is unknown territory.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 99,
      tags: ["soundtrack","safe zone","unknown"],
    },
    {
      id: 'gam-en-22',
      content: `You built a town from nothing. Three virtual years later, ten thousand citizens depend on your decisions.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 4,
      wordCount: 17,
      charCount: 105,
      tags: ["city builder","citizens","decisions"],
    },
    {
      id: 'gam-en-23',
      content: `Optional boss. Strongest enemy in the game. Nobody told you it existed. You found it anyway.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 92,
      tags: ["optional boss","discovery","challenge"],
    },
    {
      id: 'gam-en-24',
      content: `The story branched here. Both paths lead somewhere. Only one leads where you want to go.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 88,
      tags: ["branch","choice","narrative"],
    },
    {
      id: 'gam-en-25',
      content: `Graphics on maximum settings. The framerate drops to twelve. It is still worth seeing.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 14,
      charCount: 86,
      tags: ["graphics","framerate","visuals"],
    },
    {
      id: 'gam-en-26',
      content: `The secret level exists only in rumor. After weeks of searching, you found the hidden door.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 91,
      tags: ["secret level","rumor","discovery"],
    },
    {
      id: 'gam-en-27',
      content: `Your ally disconnected mid-mission. The objective remains. You finish it alone. You always could.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 97,
      tags: ["disconnect","solo","resilience"],
    },
    {
      id: 'gam-en-28',
      content: `Narrative design at its finest: every object in this room tells part of the story.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 82,
      tags: ["narrative","design","storytelling"],
    },
    {
      id: 'gam-en-29',
      content: `Input delay at four hundred milliseconds. The character responds but the connection does not.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 93,
      tags: ["input lag","connection","frustration"],
    },
    {
      id: 'gam-en-30',
      content: `All difficulty levels beaten. The game is over. But the conversation about it never ends.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 89,
      tags: ["difficulty","completion","legacy"],
    },
    {
      id: 'gam-fr-31',
      content: `Le multijoueur en ligne a changé la manière de jouer. Fini le canapé partagé à quatre manettes, place au matchmaking mondial. Un lag de cinquante millisecondes suffit à briser un combo parfaitement exécuté. Le classement compétitif ne pardonne rien : chaque saison remet les rangs à zéro, et il faut tout regagner depuis le début.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 55,
      charCount: 330,
      tags: ["multijoueur", "en-ligne", "compétitif"],
    },
    {
      id: 'gam-fr-32',
      content: `La speedrun n'est pas une simple course contre la montre. C'est une science des glitches, des raccourcis cachés et des frames perdues. Chaque route optimale a été découverte après des milliers d'essais silencieux. Le record du monde tombe rarement, mais quand il tombe, c'est toute une communauté qui célèbre ensemble.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 50,
      charCount: 318,
      tags: ["speedrun", "glitch", "communauté"],
    },
    {
      id: 'gam-fr-33',
      content: `Le rétrogaming n'est pas de la nostalgie paresseuse. C'est une discipline exigeante : seize couleurs à l'écran, quatre canaux sonores, et pourtant des mondes entiers à faire tenir dedans. Les développeurs de l'époque codaient au plus près du métal, sans filet, sans moteur, juste l'assembleur et la patience.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 48,
      charCount: 308,
      tags: ["rétrogaming", "8-bit", "développement"],
    },
    {
      id: 'gam-fr-34',
      content: `Dans les salles d'arcade des années quatre-vingt, chaque pièce de monnaie était un pari. Le joueur s'installait devant la borne, la main sur le stick, et savait qu'une seule erreur pouvait tout terminer en quelques secondes. Pas de sauvegarde, pas de checkpoint, pas de seconde chance négociable : seulement le score final gravé dans la mémoire de la machine, visible de tous les joueurs suivants. Cette tension permanente forgeait une discipline particulière, faite de mémorisation des patterns ennemis et de réflexes affûtés séance après séance. Les meilleurs joueurs devenaient des légendes locales, reconnus au bruit de leurs pièces tombant dans la fente.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 102,
      charCount: 659,
      tags: ["arcade", "borne", "histoire"],
    },
    {
      id: 'gam-fr-35',
      content: `Un patch day divise toujours la communauté en deux camps. D'un côté ceux qui saluent l'équilibrage tant réclamé, de l'autre ceux qui pleurent leur build fétiche nerfée sans préavis. Les notes de version s'étalent parfois sur des dizaines de lignes : ajustements de dégâts, corrections de bugs obscurs, nouvelles fonctionnalités glissées discrètement en bas de liste. Les joueurs compétitifs les lisent ligne par ligne, cherchant le moindre changement qui pourrait bouleverser le métagame de la saison à venir. Les développeurs, eux, surveillent les forums avec une inquiétude mêlée d'excitation, sachant que le verdict tombera dès les premières heures.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 98,
      charCount: 652,
      tags: ["patch", "équilibrage", "communauté"],
    },
    {
      id: 'gam-fr-36',
      content: `La bande originale d'un jeu vidéo façonne un souvenir bien après que la manette soit reposée. Un thème principal bien composé revient des années plus tard, déclenché par trois notes entendues par hasard dans un centre commercial. Les compositeurs de jeux travaillent souvent sous contrainte technique sévère, avec un nombre limité de canaux audio et une mémoire minuscule allouée au son. Pourtant, certaines de ces mélodies contraintes sont devenues des classiques joués par des orchestres symphoniques entiers, preuve que la limitation technique n'a jamais empêché l'émotion de traverser les décennies.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 90,
      charCount: 603,
      tags: ["musique", "bande-originale", "compositeur"],
    },
    {
      id: 'gam-en-31',
      content: `Online matchmaking changed what competitive gaming even means. Local tournaments in cramped basements gave way to global ranked ladders reachable from any bedroom. A fifty millisecond spike can still ruin a perfectly timed combo. Every new season resets the leaderboard to zero, and climbing back to the top never gets easier the second time.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 54,
      charCount: 342,
      tags: ["multiplayer", "ranked", "competitive"],
    },
    {
      id: 'gam-en-32',
      content: `Speedrunning rewards obsession more than raw skill. Runners memorize every frame of a route, chase glitches that skip entire levels, and shave milliseconds off a personal best that already looked impossible. A world record rarely falls, but when it does, the community watches the run frame by frame for weeks afterward.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 51,
      charCount: 320,
      tags: ["speedrun", "glitch", "record"],
    },
    {
      id: 'gam-en-33',
      content: `Retro game development was a discipline of scarcity. Sixteen colors on screen, four sound channels, and a cartridge too small for a single modern texture. Developers hand-optimized assembly routines just to fit an entire world into a handful of kilobytes, and somehow those tight constraints produced some of gaming's most memorable worlds.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 52,
      charCount: 340,
      tags: ["retro", "8-bit", "development"],
    },
    {
      id: 'gam-en-34',
      content: `Arcade cabinets in the eighties turned every coin into a small wager. A player stepped up, gripped the stick, and knew a single mistake could end the run within seconds. There was no save file, no checkpoint, no quiet retry — only a final score burned into the machine's memory for every player who came after. That constant pressure shaped a very specific kind of discipline, built from memorizing enemy patterns and sharpening reflexes one credit at a time. The best players became local legends, recognized by the sound of their coins dropping into the slot before anyone even saw their face.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 102,
      charCount: 595,
      tags: ["arcade", "cabinet", "history"],
    },
    {
      id: 'gam-en-35',
      content: `Patch day always splits a community into two camps. Some players celebrate the long-awaited rebalance, while others mourn a favorite build nerfed without warning. Patch notes can stretch across dozens of lines: damage adjustments, obscure bug fixes, new features quietly buried near the bottom of the list. Competitive players read every line, hunting for the one change that might reshape the season's entire metagame. Developers, meanwhile, watch the forums with a mix of dread and excitement, knowing the community's verdict will already be forming within the first few hours after release.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 4,
      wordCount: 91,
      charCount: 593,
      tags: ["patch", "balance", "community"],
    },
    {
      id: 'gam-en-36',
      content: `A video game soundtrack shapes a memory long after the controller gets put down. A well-written main theme can resurface years later, triggered by three notes overheard by accident in a shopping mall. Game composers often work under brutal technical limits, with a handful of sound channels and barely any memory allocated to audio. And yet some of those constrained melodies became genuine classics, later performed by full symphony orchestras — proof that a hard technical ceiling never actually stopped real emotion from surviving the decades.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 86,
      charCount: 546,
      tags: ["music", "soundtrack", "composer"],
    },
    {
      id: 'gam-fr-37',
      content: `Le high score affiche 999 999 points. Personne n'a jamais dépassé ce chiffre depuis douze ans.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 16,
      charCount: 94,
      tags: ["high-score", "record", "arcade"],
    },
    {
      id: 'gam-fr-38',
      content: `Niveau 42 débloqué. Le boss final a soixante-quinze mille points de vie et trois phases distinctes.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 16,
      charCount: 99,
      tags: ["niveau", "boss", "rpg"],
    },
    {
      id: 'gam-fr-39',
      content: `60 FPS constants, zéro frame drop. Le patch 2.3 a corrigé les derniers bugs de collision.`,
      source: 'TypeWav, Texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 89,
      tags: ["fps", "patch", "performance"],
    },
    {
      id: 'gam-en-37',
      content: `Final boss health: 75000. Three phases, one save point, and exactly 12 minutes on the clock.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 92,
      tags: ["boss", "health", "rpg"],
    },
    {
      id: 'gam-en-38',
      content: `The leaderboard shows a top score of 999999. Nobody has beaten that number in over a decade.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 92,
      tags: ["leaderboard", "high-score", "record"],
    },
    {
      id: 'gam-en-39',
      content: `Patch 2.3 dropped today. 60 FPS locked, zero frame drops, and 14 bugs squashed for good.`,
      source: 'TypeWav, Original text',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 88,
      tags: ["patch", "fps", "performance"],
    },
    {
      id: 'gam-fr-40',
      content: `La cartouche refusait de démarrer. On la sortait, on soufflait dessus, on la remettait en priant. Ce geste n'a jamais rien réparé, mais toute une génération l'a répété comme un rituel avant chaque partie.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 34,
      charCount: 204,
      tags: ["retro","cartouche","rituel"],
    },
    {
      id: 'gam-fr-41',
      content: `Le speedrunner rejoue le même niveau depuis huit mois. Il connaît chaque pixel, chaque fenêtre d'un seizième de seconde où le saut passe. Sa main sait avant lui quand appuyer. Le record tombe de trois dixièmes, et il recommence aussitôt, parce qu'il reste une frame à gagner quelque part.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 49,
      charCount: 288,
      tags: ["speedrun","record","obsession"],
    },
    {
      id: 'gam-fr-42',
      content: `La soirée réseau commençait par une heure de portage. On démontait sa tour, on enroulait le câble, on chargeait l'écran cathodique dans le coffre en priant pour les virages. Une fois les six machines reliées par un fil qui traversait le salon, on jouait jusqu'à l'aube dans une odeur de plastique chaud, et le trajet du retour se faisait au lever du jour, l'écran sur les genoux.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 67,
      charCount: 379,
      tags: ["lan-party","portage","reseau"],
    },
    {
      id: 'gam-fr-43',
      content: `Le magasin de location fermait à vingt heures. On choisissait une boîte en fonction de la jaquette, sans note, sans avis, sans bande-annonce. La moitié des jeux étaient décevants. L'autre moitié devenait des souvenirs pour la vie, précisément parce qu'on n'avait rien vu venir.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 44,
      charCount: 277,
      tags: ["location","jaquette","decouverte"],
    },
    {
      id: 'gam-fr-44',
      content: `La carte mémoire tenait cent parties dans un boîtier plus petit qu'une boîte d'allumettes. On la trimballait chez les copains comme un passeport, on la protégeait de la poussière, on refusait de la prêter. Le jour où l'une d'elles rendait l'âme sans prévenir, c'étaient des années de progression qui disparaissaient d'un coup, et personne n'avait pensé à en faire une copie, parce qu'aucun moyen simple de copier n'existait.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 68,
      charCount: 424,
      tags: ["carte-memoire","sauvegarde","fragilite"],
    },
    {
      id: 'gam-fr-45',
      content: `Le manuel papier se lisait dans la voiture, sur le trajet du retour. Il y avait une carte du monde, la liste des ennemis, parfois une nouvelle de dix pages pour poser l'histoire. On connaissait le jeu par cœur avant même de l'avoir lancé.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 44,
      charCount: 238,
      tags: ["manuel","lore","attente"],
    },
    {
      id: 'gam-fr-46',
      content: `Le guide officiel était un livre de deux cents pages qu'on achetait séparément, parfois plus cher qu'un jeu d'occasion. On le lisait au lit, on cornait les cartes de donjon, on cachait volontairement les dernières pages pour ne pas se gâcher la fin. Aujourd'hui la même information tient dans un onglet ouvert sur un deuxième écran, et on ne corne plus rien.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 62,
      charCount: 358,
      tags: ["guide","livre","donjon"],
    },
    {
      id: 'gam-fr-47',
      content: `Le mode deux joueurs partageait un seul écran et un seul canapé. On se gênait, on se poussait du coude, on accusait la manette d'être défectueuse. Les meilleures soirées de jeu de cette époque tenaient autant à la personne assise à côté qu'au jeu lui-même.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 45,
      charCount: 256,
      tags: ["multijoueur","canape","local"],
    },
    {
      id: 'gam-fr-48',
      content: `Il y avait toujours, dans le groupe d'amis, celui qui était bon aux jeux. On lui passait la manette au moment du passage impossible, il franchissait l'obstacle en deux essais sans un mot, puis nous rendait la partie exactement là où elle avait coincé. Personne ne trouvait ça humiliant. C'était une entraide silencieuse, chacun tenait un rôle, et le sien était de débloquer les autres.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 65,
      charCount: 385,
      tags: ["amis","entraide","manette"],
    },
    {
      id: 'gam-fr-49',
      content: `Le code de triche se tapait à l'écran-titre, une séquence précise de directions et de boutons. On le recopiait depuis un magazine corné, on se trompait, on recommençait. Quand la petite musique de confirmation retentissait enfin, on savait qu'on venait de déverrouiller quelque chose que le jeu ne voulait pas montrer si facilement.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 53,
      charCount: 332,
      tags: ["triche","code","magazine"],
    },
    {
      id: 'gam-fr-50',
      content: `Le temps de chargement se comptait en minutes. On lançait le jeu, on partait se faire un sandwich, on revenait pour voir la barre avancer d'un cran. Personne ne s'en plaignait vraiment, parce que personne n'avait connu autre chose.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 39,
      charCount: 231,
      tags: ["chargement","patience","disquette"],
    },
    {
      id: 'gam-fr-51',
      content: `Le boss final n'avait pas de deuxième chance. Une seule barre de vie, un seul essai après vingt minutes de couloir, et le moindre faux pas renvoyait tout au début. La tension de ces affrontements n'a jamais été retrouvée par les jeux modernes, qui te reposent obligeamment juste devant la porte.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 51,
      charCount: 295,
      tags: ["boss","tension","permadeath"],
    },
    {
      id: 'gam-fr-52',
      content: `Le forum de fans documentait chaque secret, chaque salle cachée, chaque combinaison d'objets. Des inconnus passaient des week-ends entiers à cartographier un donjon au papier millimétré, puis publiaient le plan pour que personne d'autre n'ait à se perdre. C'était une forme de générosité qu'on ne nommait pas encore.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 48,
      charCount: 316,
      tags: ["communaute","forum","entraide"],
    },
    {
      id: 'gam-fr-53',
      content: `Le moteur physique du jeu contenait un bug si constant que les joueurs ont fini par le considérer comme une mécanique. En annulant un saut au bon moment, le personnage conservait sa vitesse et fusait à travers le décor. Les développeurs ont hésité, puis ils ont décidé de ne pas le corriger, parce qu'une communauté entière avait déjà bâti son plaisir autour de cette erreur, et qu'un correctif l'aurait rendue orpheline.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 71,
      charCount: 421,
      tags: ["bug","mecanique","communaute"],
    },
    {
      id: 'gam-fr-54',
      content: `L'écran de game over affichait un score, puis trois lettres à saisir si tu figurais dans le tableau. On choisissait ses initiales avec soin, comme une signature laissée sur la machine pour tous les joueurs qui viendraient après.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 38,
      charCount: 228,
      tags: ["game-over","score","initiales"],
    },
    {
      id: 'gam-fr-55',
      content: `Le mode photo a transformé des millions de joueurs en paysagistes. On arrête l'action, on fait pivoter la caméra, on règle la profondeur de champ et l'heure du jour. Certains passent plus de temps à composer un cliché qu'à progresser dans l'histoire, et le jeu ne leur en tient nullement rigueur.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 51,
      charCount: 296,
      tags: ["mode-photo","paysage","contemplation"],
    },
    {
      id: 'gam-fr-56',
      content: `La bêta fermée réunissait quelques milliers de joueurs sous accord de confidentialité. On testait des serveurs qui tombaient toutes les heures, on remontait des rapports de bug avec des captures d'écran, on avait le sentiment étrange de construire quelque chose avec des inconnus. Puis le jeu sortait, l'immense majorité arrivait, et notre petite version cassée devenait un souvenir de privilégiés.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 60,
      charCount: 398,
      tags: ["beta","test","communaute"],
    },
    {
      id: 'gam-fr-57',
      content: `Le disque dur de la console se remplissait sans qu'on comprenne pourquoi. On effaçait de vieilles sauvegardes le cœur lourd, une partie de rôle abandonnée à quarante heures, un circuit sur lequel on avait le meilleur temps du foyer. Libérer de l'espace, c'était accepter d'oublier.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 3,
      wordCount: 45,
      charCount: 281,
      tags: ["stockage","sauvegarde","nostalgie"],
    },
    {
      id: 'gam-fr-58',
      content: `Le générateur procédural promettait un monde infini, et il l'a tenu au pied de la lettre. Des milliards de planètes, chacune calculée à la volée à partir d'une seule graine numérique, aucune identique, presque aucune mémorable. Les joueurs ont vite compris que l'infini sans intention se visite comme un désert : on avance longtemps, on voit beaucoup, et on ne se souvient de rien.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 5,
      wordCount: 64,
      charCount: 381,
      tags: ["procedural","infini","design"],
    },
    {
      id: 'gam-fr-59',
      content: `La démo jouable arrivait sur un disque collé à la couverture du magazine. Trois niveaux, une limite de temps, un écran qui te renvoyait au menu en te conseillant d'acheter la version complète. On relançait ces trois niveaux pendant des mois.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 2,
      wordCount: 41,
      charCount: 241,
      tags: ["demo","magazine","attente"],
    },
    {
      id: 'gam-fr-60',
      content: `Le patch du premier jour pèse parfois plus lourd que le jeu gravé sur le disque. On rentre du magasin, on insère la galette, et on attend deux heures que le réseau télécharge la moitié manquante. L'objet physique n'est plus qu'une clé d'activation avec une belle jaquette, et quelque chose s'est perdu dans cette bascule qu'on a du mal à nommer.`,
      source: 'TypeWav, texte original',
      language: 'fr',
      difficulty: 4,
      wordCount: 61,
      charCount: 345,
      tags: ["patch","day-one","physique"],
    },
    {
      id: 'gam-en-40',
      content: `The cartridge would not boot. You pulled it out, blew across the contacts, slotted it back in like a prayer. The ritual never actually fixed anything, but a whole generation performed it before every session anyway.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 2,
      wordCount: 36,
      charCount: 215,
      tags: ["retro","cartridge","ritual"],
    },
    {
      id: 'gam-en-41',
      content: `The speedrunner has run this same level for eight months. He knows every pixel, every one-sixteenth-of-a-second window where the jump lands. His hands know before he does when to press. The record falls by three tenths, and he restarts immediately, because there is still a frame to save somewhere.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 49,
      charCount: 298,
      tags: ["speedrun","record","obsession"],
    },
    {
      id: 'gam-en-42',
      content: `The network night started with an hour of hauling. You unplugged your tower, coiled the cable, loaded the heavy monitor into the boot and prayed through every corner. Once six machines were linked by a wire running across the living room, you played until dawn in the smell of warm plastic, and the drive home happened at first light, the screen resting on your knees.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 4,
      wordCount: 65,
      charCount: 368,
      tags: ["lan-party","hauling","network"],
    },
    {
      id: 'gam-en-43',
      content: `The rental store closed at eight. You picked a box by its cover art, with no review, no rating, no trailer. Half the games were disappointing. The other half became memories for life, precisely because you had no idea what was coming.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 42,
      charCount: 234,
      tags: ["rental","cover-art","discovery"],
    },
    {
      id: 'gam-en-44',
      content: `The memory card held a hundred saves in a shell smaller than a matchbox. You carried it to friends' houses like a passport, kept it away from dust, refused to lend it out. The day one of them died without warning, years of progress vanished at once, and nobody had thought to make a copy, because no simple way to copy one existed.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 5,
      wordCount: 63,
      charCount: 331,
      tags: ["memory-card","save","fragility"],
    },
    {
      id: 'gam-en-45',
      content: `The paper manual was read in the car on the drive home. There was a world map, a bestiary, sometimes a ten-page short story to set up the plot. You knew the game by heart before you had even switched it on.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 2,
      wordCount: 42,
      charCount: 206,
      tags: ["manual","lore","anticipation"],
    },
    {
      id: 'gam-en-46',
      content: `The official guide was a two-hundred-page book you bought separately, sometimes for more than a used game. You read it in bed, dog-eared the dungeon maps, deliberately hid the last pages so as not to spoil the ending. Today the same information sits in a tab open on a second monitor, and nothing gets dog-eared anymore.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 4,
      wordCount: 56,
      charCount: 320,
      tags: ["guide","book","dungeon"],
    },
    {
      id: 'gam-en-47',
      content: `Two-player mode shared one screen and one couch. You crowded each other, elbowed for space, blamed the controller for being broken. The best gaming nights of that era owed as much to the person sitting beside you as to the game itself.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 42,
      charCount: 235,
      tags: ["multiplayer","couch","local"],
    },
    {
      id: 'gam-en-48',
      content: `There was always one friend in the group who was good at games. You handed them the controller at the impossible section, they cleared it in two tries without a word, then gave the game back exactly where it had stalled. Nobody found it humiliating. It was a quiet mutual aid, everyone held a role, and theirs was to unblock the others.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 5,
      wordCount: 62,
      charCount: 336,
      tags: ["friends","mutual-aid","controller"],
    },
    {
      id: 'gam-en-49',
      content: `The cheat code was entered at the title screen, a precise sequence of directions and buttons. You copied it from a dog-eared magazine, got it wrong, started over. When the little confirmation jingle finally played, you knew you had just unlocked something the game did not want to give up so easily.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 52,
      charCount: 299,
      tags: ["cheat","code","magazine"],
    },
    {
      id: 'gam-en-50',
      content: `Loading times were measured in minutes. You started the game, went to make a sandwich, came back to watch the bar move up one notch. Nobody really complained, because nobody had known anything else.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 2,
      wordCount: 34,
      charCount: 198,
      tags: ["loading","patience","floppy"],
    },
    {
      id: 'gam-en-51',
      content: `The final boss offered no second chance. A single health bar, one attempt after twenty minutes of corridor, and the smallest misstep sent everything back to the start. The tension of those fights has never been matched by modern games, which obligingly rest you just outside the door.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 4,
      wordCount: 48,
      charCount: 284,
      tags: ["boss","tension","stakes"],
    },
    {
      id: 'gam-en-52',
      content: `The fan forum documented every secret, every hidden room, every item combination. Strangers spent entire weekends mapping a dungeon on graph paper, then posted the layout so nobody else would have to get lost. It was a kind of generosity that did not yet have a name.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 47,
      charCount: 267,
      tags: ["community","forum","help"],
    },
    {
      id: 'gam-en-53',
      content: `The game's physics engine held a bug so consistent that players eventually treated it as a mechanic. By cancelling a jump at the right moment, the character kept its speed and shot across the level geometry. The developers hesitated, then decided not to fix it, because a whole community had already built its enjoyment around that error, and a patch would have orphaned it.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 5,
      wordCount: 64,
      charCount: 374,
      tags: ["bug","mechanic","community"],
    },
    {
      id: 'gam-en-54',
      content: `The game over screen showed a score, then three letters to type if you had made the table. You picked your initials with care, like a signature left on the machine for every player who would come after.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 2,
      wordCount: 38,
      charCount: 202,
      tags: ["game-over","score","initials"],
    },
    {
      id: 'gam-en-55',
      content: `Photo mode turned millions of players into landscape painters. You freeze the action, orbit the camera, dial in the depth of field and the time of day. Some spend more time composing a single shot than progressing through the story, and the game does not hold it against them in the slightest.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 52,
      charCount: 293,
      tags: ["photo-mode","landscape","contemplation"],
    },
    {
      id: 'gam-en-56',
      content: `The closed beta gathered a few thousand players under a confidentiality agreement. You tested servers that fell over every hour, filed bug reports with screenshots, felt the strange sense of building something with strangers. Then the game launched, the vast majority arrived, and our small broken version became a memory of the privileged few.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 4,
      wordCount: 54,
      charCount: 344,
      tags: ["beta","testing","community"],
    },
    {
      id: 'gam-en-57',
      content: `The console hard drive filled up for no reason you could see. You deleted old saves with a heavy heart, a role-playing game abandoned at forty hours, a track where you held the household best time. Freeing up space meant agreeing to forget.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 3,
      wordCount: 43,
      charCount: 240,
      tags: ["storage","save","nostalgia"],
    },
    {
      id: 'gam-en-58',
      content: `The procedural generator promised an infinite world, and it delivered on that literally. Billions of planets, each computed on the fly from a single numeric seed, none identical, almost none memorable. Players quickly learned that infinity without intention is toured like a desert: you travel a long way, you see a great deal, and you remember nothing.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 5,
      wordCount: 57,
      charCount: 353,
      tags: ["procedural","infinity","design"],
    },
    {
      id: 'gam-en-59',
      content: `The playable demo came on a disc glued to the magazine cover. Three levels, a time limit, a screen that sent you back to the menu advising you to buy the full version. You replayed those three levels for months.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 2,
      wordCount: 40,
      charCount: 211,
      tags: ["demo","magazine","anticipation"],
    },
    {
      id: 'gam-en-60',
      content: `The day-one patch sometimes weighs more than the game burned onto the disc. You come home from the store, insert the platter, and wait two hours for the network to download the missing half. The physical object is now just an activation key with nice cover art, and something has been lost in that shift that is hard to name.`,
      source: 'TypeWav, texte original',
      language: 'en',
      difficulty: 4,
      wordCount: 60,
      charCount: 325,
      tags: ["patch","day-one","physical"],
    },
    {
      id: 'gam-fr-61',
      content: `Le serveur du vieux jeu en ligne ferme dans un mois. L'éditeur l'a annoncé dans un communiqué de trois lignes, sans cérémonie. Pendant des années, des milliers de joueurs se sont connectés chaque soir sur cette carte, ont bâti des guildes, échangé des objets, tenu des mariages virtuels et des funérailles pour les comptes abandonnés. Rien de tout cela n'était sauvegardé ailleurs que sur des machines louées dans un centre de données anonyme. Le dernier soir, plusieurs centaines de personnes se sont donné rendez-vous sur la place principale de la ville de départ, celle où chacun était apparu la première fois. À l'heure dite, l'écran s'est figé, puis il a affiché une erreur de connexion, et le monde a cessé d'exister d'un seul coup, comme on souffle une bougie.`,
      language: 'fr',
      difficulty: 5,
      wordCount: 129,
      charCount: 767,
      tags: ["mmo","fermeture","communaute"],
    },
    {
      id: 'gam-en-61',
      content: `The old online game's server shuts down in a month. The publisher announced it in a three-line statement, without ceremony. For years, thousands of players logged in every evening on this map, built guilds, traded items, held virtual weddings and funerals for abandoned accounts. None of it was saved anywhere except on machines rented in an anonymous data centre. On the last night, several hundred people arranged to meet on the main square of the starting town, the one where everyone had first appeared. At the appointed hour the screen froze, then it displayed a connection error, and the world stopped existing all at once, the way you blow out a candle.`,
      language: 'en',
      difficulty: 5,
      wordCount: 112,
      charCount: 660,
      tags: ["mmo","shutdown","community"],
    },
    {
      id: 'gam-fr-62',
      content: `On appelait ça la ferme à expérience. Un endroit du jeu où les monstres réapparaissaient plus vite qu'ailleurs, dans un couloir étroit, faciles à aligner et à abattre en série. Ce n'était pas prévu par les concepteurs, juste une conséquence involontaire de la façon dont les zones se rechargeaient. Pendant des semaines, on y montait de niveau en boucle, l'œil vitreux, la main sur la même touche, à répéter le même geste des heures durant. Personne ne trouvait ça amusant. On le faisait parce que la suite du jeu, la vraie, demandait un personnage assez fort, et que ce couloir gris était le chemin le plus court pour y arriver. Le plaisir attendait de l'autre côté de l'ennui.`,
      language: 'fr',
      difficulty: 4,
      wordCount: 118,
      charCount: 678,
      tags: ["grind","ferme-xp","niveau"],
    },
    {
      id: 'gam-en-62',
      content: `We called it the experience farm. A spot in the game where monsters respawned faster than anywhere else, in a narrow corridor, easy to line up and cut down in a row. The designers had not planned it, it was just an accidental consequence of how the zones reloaded. For weeks we ground levels there in a loop, eyes glazed, hand on the same key, repeating the same motion for hours. Nobody found it fun. We did it because the rest of the game, the real part, needed a character strong enough, and that grey corridor was the shortest path there. The fun was waiting on the far side of the boredom.`,
      language: 'en',
      difficulty: 4,
      wordCount: 112,
      charCount: 594,
      tags: ["grind","xp-farm","levels"],
    },
    {
      id: 'gam-fr-63',
      content: `L'écran d'accueil bouclait une démo automatique quand personne ne jouait, montrant des coups impossibles exécutés par la machine elle-même, pour donner envie de glisser une pièce dans la fente.`,
      language: 'fr',
      difficulty: 3,
      wordCount: 29,
      charCount: 193,
      tags: ["attract-mode","arcade","demo"],
    },
    {
      id: 'gam-en-63',
      content: `The title screen looped an automatic demo when nobody was playing, showing impossible moves performed by the machine itself, to make you want to slip a coin into the slot.`,
      language: 'en',
      difficulty: 3,
      wordCount: 30,
      charCount: 171,
      tags: ["attract-mode","arcade","demo"],
    },
    {
      id: 'gam-fr-64',
      content: `La manette avait un fil de deux mètres. On s'asseyait par terre, le dos contre le canapé, à la distance exacte où le câble tirait sans débrancher, et on ne bougeait plus de la soirée.`,
      language: 'fr',
      difficulty: 2,
      wordCount: 35,
      charCount: 183,
      tags: ["manette","fil","canape"],
    },
    {
      id: 'gam-en-64',
      content: `The controller had a two-metre cord. You sat on the floor, back against the couch, at the exact distance where the cable pulled without unplugging, and did not move for the rest of the evening.`,
      language: 'en',
      difficulty: 2,
      wordCount: 35,
      charCount: 193,
      tags: ["controller","cord","couch"],
    },
  ],
};
