/**
 * Collection Poésie : textes du domaine public (auteur mort > 70 ans).
 * Sources : Wikisource, Project Gutenberg.
 * Spec : docs/specs/06-content.md
 */

import type { CollectionConfig } from '@typewav/types';

export const poesieCollection: CollectionConfig = {
  id: 'poesie',
  name: 'Poésie',
  nameEn: 'Poetry',
  description: 'Poèmes emblématiques du patrimoine mondial : domaine public.',
  language: 'multi',
  recommendedTheme: 'midnight-sun',
  isPremium: false,
  texts: [
    {
      id: 'poe-fr-01',
      content: `Mon enfant, ma sœur, songe à la douceur d'aller là-bas vivre ensemble.`,
      source: 'Charles Baudelaire, L\'Invitation au voyage (1857)',
      language: 'fr',
      difficulty: 3,
      wordCount: 12,
      charCount: 70,
      tags: ["baudelaire","romantisme","france"],
    },
    {
      id: 'poe-fr-02',
      content: `Demain, dès l'aube, à l'heure où blanchit la campagne, je partirai. Vois-tu, je sais que tu m'attends.`,
      source: 'Victor Hugo, Les Contemplations (1856)',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 102,
      tags: ["hugo","romantisme","france"],
    },
    {
      id: 'poe-fr-03',
      content: `Sous le pont Mirabeau coule la Seine et nos amours faut-il qu'il m'en souvienne la joie venait toujours après la peine.`,
      source: 'Guillaume Apollinaire, Le Pont Mirabeau (1913)',
      language: 'fr',
      difficulty: 3,
      wordCount: 21,
      charCount: 119,
      tags: ["apollinaire","modernisme","france"],
    },
    {
      id: 'poe-fr-04',
      content: `Heureux qui, comme Ulysse, a fait un beau voyage, ou comme cestuy-là qui conquit la toison.`,
      source: 'Joachim du Bellay, Les Regrets (1558)',
      language: 'fr',
      difficulty: 5,
      wordCount: 16,
      charCount: 91,
      tags: ["du bellay","renaissance","france"],
    },
    {
      id: 'poe-fr-05',
      content: `Sois sage, ô ma Douleur, et tiens-toi plus tranquille. Tu réclamais le Soir; il descend; le voici.`,
      source: 'Charles Baudelaire, Recueillement (1861)',
      language: 'fr',
      difficulty: 5,
      wordCount: 17,
      charCount: 98,
      tags: ["baudelaire","symbolisme","france"],
    },
    {
      id: 'poe-fr-06',
      content: `Il pleure dans mon cœur comme il pleut sur la ville. Quelle est cette langueur qui pénètre mon cœur?`,
      source: 'Paul Verlaine, Romances sans paroles (1874)',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 100,
      tags: ["verlaine","symbolisme","france"],
    },
    {
      id: 'poe-fr-07',
      content: `Ma bohème. Je m'en allais, les poings dans mes poches crevées; mon paletot aussi devenait idéal.`,
      source: 'Arthur Rimbaud, Ma Bohème (1870)',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 96,
      tags: ["rimbaud","symbolisme","france"],
    },
    {
      id: 'poe-fr-08',
      content: `La terre est bleue comme une orange. Jamais une erreur les mots ne mentent pas.`,
      source: 'Paul Éluard, L\'Amour la Poésie (1929)',
      language: 'fr',
      difficulty: 1,
      wordCount: 15,
      charCount: 79,
      tags: ["eluard","surréalisme","france"],
    },
    {
      id: 'poe-fr-09',
      content: `Liberté. J'ai écrit ton nom sur mes cahiers d'écolier sur mon pupitre et les arbres.`,
      source: 'Paul Éluard, Liberté (1942)',
      language: 'fr',
      difficulty: 1,
      wordCount: 15,
      charCount: 84,
      tags: ["eluard","résistance","france"],
    },
    {
      id: 'poe-fr-10',
      content: `Qui fait l'ange fait la bête. Le cœur a ses raisons que la raison ne connaît point.`,
      source: 'Blaise Pascal, Pensées (1670)',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 83,
      tags: ["pascal","philosophie","france"],
    },
    {
      id: 'poe-fr-11',
      content: `Roses, vous avez dit : pour qui suis-je si belle ?`,
      source: 'Pierre de Ronsard, Odes (1550)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 50,
      tags: ["ronsard","renaissance","france"],
    },
    {
      id: 'poe-fr-12',
      content: `Mes vers fuiraient, doux et frêles, vers votre jardin si beau.`,
      source: 'Victor Hugo, Vous avez le regard serein (1835)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 62,
      tags: ["hugo","romantisme","france"],
    },
    {
      id: 'poe-fr-13',
      content: `Et rose elle a vécu ce que vivent les roses, l'espace d'un matin.`,
      source: 'François de Malherbe, Consolation (1599)',
      language: 'fr',
      difficulty: 2,
      wordCount: 13,
      charCount: 65,
      tags: ["malherbe","classicisme","france"],
    },
    {
      id: 'poe-fr-14',
      content: `Je suis l'empire à la fin de la décadence, qui regarde passer les grands barbares blancs.`,
      source: 'Paul Verlaine, Langeur (1883)',
      language: 'fr',
      difficulty: 5,
      wordCount: 16,
      charCount: 89,
      tags: ["verlaine","décadence","france"],
    },
    {
      id: 'poe-fr-15',
      content: `Le vent se lève, il faut tenter de vivre.`,
      source: 'Paul Valéry, Le Cimetière marin (1920)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 41,
      tags: ["valéry","modernisme","france"],
    },
    {
      id: 'poe-fr-16',
      content: `Ô saisons, ô châteaux! Quelle âme est sans défauts?`,
      source: 'Arthur Rimbaud, Ô Saisons (1872)',
      language: 'fr',
      difficulty: 3,
      wordCount: 9,
      charCount: 51,
      tags: ["rimbaud","saisons","france"],
    },
    {
      id: 'poe-fr-17',
      content: `Maître Corbeau, sur un arbre perché, tenait en son bec un fromage.`,
      source: 'Jean de La Fontaine, Le Corbeau et le Renard (1668)',
      language: 'fr',
      difficulty: 1,
      wordCount: 12,
      charCount: 66,
      tags: ["la fontaine","fable","france"],
    },
    {
      id: 'poe-fr-18',
      content: `Ces nymphes, je les veux perpétuer.`,
      source: 'Stéphane Mallarmé, L\'Après-midi d\'un faune (1876)',
      language: 'fr',
      difficulty: 4,
      wordCount: 6,
      charCount: 35,
      tags: ["mallarmé","symbolisme","france"],
    },
    {
      id: 'poe-fr-19',
      content: `Tout ce qui est beau est difficile autant que rare.`,
      source: 'Baruch Spinoza, Éthique (1677)',
      language: 'fr',
      difficulty: 2,
      wordCount: 10,
      charCount: 51,
      tags: ["spinoza","philosophie","rare"],
    },
    {
      id: 'poe-fr-20',
      content: `Je suis le ténébreux, le veuf, l'inconsolé, le prince d'Aquitaine à la tour abolie.`,
      source: 'Gérard de Nerval, El Desdichado (1854)',
      language: 'fr',
      difficulty: 4,
      wordCount: 14,
      charCount: 83,
      tags: ["nerval", "symbolisme", "france"],
    },
    {
      id: 'poe-fr-21',
      content: `Ô nuit désastreuse ! Ô nuit effroyable, où retentit tout à coup comme un éclat de tonnerre cette étonnante nouvelle.`,
      source: 'Jacques-Bénigne Bossuet, Oraison funèbre (1686)',
      language: 'fr',
      difficulty: 5,
      wordCount: 20,
      charCount: 116,
      tags: ["bossuet","oraison","baroque"],
    },
    {
      id: 'poe-fr-22',
      content: `Minuit. La pluie. Une rue éclatante et noire.`,
      source: 'Émile Verhaeren, La Pluie (1895)',
      language: 'fr',
      difficulty: 2,
      wordCount: 8,
      charCount: 45,
      tags: ["verhaeren","symbolisme","belgique"],
    },
    {
      id: 'poe-fr-23',
      content: `J'ai plus de souvenirs que si j'avais mille ans.`,
      source: 'Charles Baudelaire, Spleen (1857)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 48,
      tags: ["baudelaire","spleen","mélancolie"],
    },
    {
      id: 'poe-fr-24',
      content: `On vit, on parle, on a le ciel et les nuages sur la tête.`,
      source: 'Victor Hugo, Les Contemplations (1856)',
      language: 'fr',
      difficulty: 1,
      wordCount: 14,
      charCount: 57,
      tags: ["hugo","vie","ciel"],
    },
    {
      id: 'poe-fr-25',
      content: `Beau soir de printemps à travers les nuages, doux reflets de lune sur les eaux dormantes.`,
      source: 'Paul Verlaine, Poèmes saturniens (1866)',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 89,
      tags: ["verlaine","printemps","lune"],
    },
    {
      id: 'poe-fr-26',
      content: `Il faut qu'une porte soit ouverte ou fermée.`,
      source: 'Alfred de Musset, Il faut qu\'une porte soit ouverte ou fermée (1845)',
      language: 'fr',
      difficulty: 1,
      wordCount: 8,
      charCount: 44,
      tags: ["musset","porte","proverbe"],
    },
    {
      id: 'poe-fr-27',
      content: `Le repos est une illusion. La paix est quelque chose que je n'ai jamais connu.`,
      source: 'Guillaume Apollinaire, Alcools (1913)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 78,
      tags: ["apollinaire","repos","paix"],
    },
    {
      id: 'poe-fr-28',
      content: `Lorsque l'enfant paraît, le cercle de famille applaudit à grands cris.`,
      source: 'Victor Hugo, Les Feuilles d\'automne (1831)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 70,
      tags: ["hugo", "famille", "france"],
    },
    {
      id: 'poe-fr-29',
      content: `Le bonheur est une chose rare et difficile à garder.`,
      source: 'Stendhal, De l\'Amour (1822)',
      language: 'fr',
      difficulty: 2,
      wordCount: 10,
      charCount: 52,
      tags: ["stendhal","bonheur","amour"],
    },
    {
      id: 'poe-fr-30',
      content: `Avoir été aimé une seule fois sincèrement vaut mieux que d'être adulé par des milliers.`,
      source: 'Honoré de Balzac, Aux gens qui rient (1830)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 87,
      tags: ["balzac","amour","sincérité"],
    },
    {
      id: 'poe-en-01',
      content: `Shall I compare thee to a summer's day? Thou art more lovely and more temperate.`,
      source: 'William Shakespeare, Sonnet 18 (1609)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 80,
      tags: ["shakespeare","sonnet","england"],
    },
    {
      id: 'poe-en-02',
      content: `Does the road wind up-hill all the way? Yes, to the very end. Will the day's journey take the whole long day? From morn to night, my friend.`,
      source: 'Christina Rossetti, Up-Hill (1861)',
      language: 'en',
      difficulty: 2,
      wordCount: 28,
      charCount: 140,
      tags: ["rossetti", "journey", "england"],
    },
    {
      id: 'poe-en-03',
      content: `Do not go gentle into that good night. Old age should burn and rave at close of day.`,
      source: 'Dylan Thomas, Do Not Go Gentle (1947)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 84,
      tags: ["thomas","villanelle","wales"],
    },
    {
      id: 'poe-en-04',
      content: `Because I could not stop for Death, he kindly stopped for me; the carriage held but just ourselves and Immortality.`,
      source: 'Emily Dickinson, Because I Could Not Stop for Death (c.1863)',
      language: 'en',
      difficulty: 3,
      wordCount: 20,
      charCount: 115,
      tags: ["dickinson","american","death"],
    },
    {
      id: 'poe-en-05',
      content: `I am the master of my fate, I am the captain of my soul.`,
      source: 'William Ernest Henley, Invictus (1875)',
      language: 'en',
      difficulty: 1,
      wordCount: 14,
      charCount: 56,
      tags: ["henley", "resolve", "england"],
    },
    {
      id: 'poe-en-06',
      content: `In Xanadu did Kubla Khan a stately pleasure-dome decree: where Alph, the sacred river, ran through caverns measureless to man down to a sunless sea.`,
      source: 'Samuel Taylor Coleridge, Kubla Khan (1816)',
      language: 'en',
      difficulty: 5,
      wordCount: 25,
      charCount: 148,
      tags: ["coleridge","romanticism","england"],
    },
    {
      id: 'poe-en-07',
      content: `Hope is the thing with feathers that perches in the soul, and sings the tune without the words, and never stops at all.`,
      source: 'Emily Dickinson, Hope is the Thing with Feathers (c.1861)',
      language: 'en',
      difficulty: 1,
      wordCount: 23,
      charCount: 119,
      tags: ["dickinson","american","hope"],
    },
    {
      id: 'poe-en-08',
      content: `Tyger Tyger, burning bright, in the forests of the night; what immortal hand or eye, could frame thy fearful symmetry?`,
      source: 'William Blake, Songs of Experience (1794)',
      language: 'en',
      difficulty: 3,
      wordCount: 20,
      charCount: 118,
      tags: ["blake","romanticism","england"],
    },
    {
      id: 'poe-en-09',
      content: `I wandered lonely as a cloud that floats on high o'er vales and hills, when all at once I saw a crowd, a host, of golden daffodils.`,
      source: 'William Wordsworth, Daffodils (1807)',
      language: 'en',
      difficulty: 3,
      wordCount: 27,
      charCount: 131,
      tags: ["wordsworth","romanticism","nature"],
    },
    {
      id: 'poe-en-10',
      content: `Who has seen the wind? Neither I nor you: but when the leaves hang trembling, the wind is passing through.`,
      source: 'Christina Rossetti, Who Has Seen the Wind (1872)',
      language: 'en',
      difficulty: 1,
      wordCount: 20,
      charCount: 106,
      tags: ["rossetti", "nature", "england"],
    },
    {
      id: 'poe-en-11',
      content: `Thou still unravish'd bride of quietness, thou foster-child of silence and slow time.`,
      source: 'John Keats, Ode on a Grecian Urn (1819)',
      language: 'en',
      difficulty: 5,
      wordCount: 13,
      charCount: 85,
      tags: ["keats","romanticism","urn"],
    },
    {
      id: 'poe-en-12',
      content: `Water, water, everywhere, nor any drop to drink.`,
      source: 'Samuel Taylor Coleridge, The Rime of the Ancient Mariner (1798)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 48,
      tags: ["coleridge","sea","mariner"],
    },
    {
      id: 'poe-en-13',
      content: `How do I love thee? Let me count the ways. I love thee to the depth and breadth and height my soul can reach.`,
      source: 'Elizabeth Barrett Browning, Sonnets from the Portuguese (1850)',
      language: 'en',
      difficulty: 3,
      wordCount: 24,
      charCount: 109,
      tags: ["browning","love","sonnet"],
    },
    {
      id: 'poe-en-14',
      content: `If you can keep your head when all about you are losing theirs and blaming it on you.`,
      source: 'Rudyard Kipling, If (1910)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 85,
      tags: ["kipling","virtue","england"],
    },
    {
      id: 'poe-en-15',
      content: `I cannot rest from travel: I will drink life to the lees.`,
      source: 'Alfred Lord Tennyson, Ulysses (1842)',
      language: 'en',
      difficulty: 2,
      wordCount: 12,
      charCount: 57,
      tags: ["tennyson", "travel", "road"],
    },
    {
      id: 'poe-en-16',
      content: `Shall I compare thee to a winter's night? More harsh, more cold, and more inconstant far.`,
      source: 'Anonymous, After Shakespeare',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 89,
      tags: ["sonnet","winter","comparison"],
    },
    {
      id: 'poe-en-17',
      content: `Death, be not proud, though some have called thee mighty and dreadful, for thou art not so.`,
      source: 'John Donne, Death Be Not Proud (1633)',
      language: 'en',
      difficulty: 5,
      wordCount: 17,
      charCount: 91,
      tags: ["donne","death","metaphysical"],
    },
    {
      id: 'poe-en-18',
      content: `Gather ye rosebuds while ye may, old time is still a-flying.`,
      source: 'Robert Herrick, To the Virgins (1648)',
      language: 'en',
      difficulty: 2,
      wordCount: 11,
      charCount: 60,
      tags: ["herrick","time","carpe diem"],
    },
    {
      id: 'poe-en-19',
      content: `What immortal hand or eye dare frame thy fearful symmetry?`,
      source: 'William Blake, The Tyger (1794)',
      language: 'en',
      difficulty: 3,
      wordCount: 10,
      charCount: 58,
      tags: ["blake","tiger","symmetry"],
    },
    {
      id: 'poe-en-20',
      content: `Breathes there the man with soul so dead who never to himself hath said, this is my own, my native land?`,
      source: 'Sir Walter Scott, The Lay of the Last Minstrel (1805)',
      language: 'en',
      difficulty: 5,
      wordCount: 21,
      charCount: 104,
      tags: ["scott","patriotism","scotland"],
    },
    {
      id: 'poe-en-21',
      content: `Tell me not, in mournful numbers, life is but an empty dream.`,
      source: 'Henry Wadsworth Longfellow, A Psalm of Life (1838)',
      language: 'en',
      difficulty: 3,
      wordCount: 12,
      charCount: 61,
      tags: ["longfellow","american","life"],
    },
    {
      id: 'poe-en-22',
      content: `Each mortal thing does one thing and the same: myself it speaks and spells, crying What I do is me: for that I came.`,
      source: 'Gerard Manley Hopkins, As Kingfishers Catch Fire (1877)',
      language: 'en',
      difficulty: 4,
      wordCount: 24,
      charCount: 116,
      tags: ["hopkins", "selfhood", "existence"],
    },
    {
      id: 'poe-en-23',
      content: `Beauty is truth, truth beauty, that is all ye know on earth and all ye need to know.`,
      source: 'John Keats, Ode on a Grecian Urn (1819)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 84,
      tags: ["keats","beauty","truth"],
    },
    {
      id: 'poe-en-24',
      content: `To her fair works did Nature link the human soul that through me ran; and much it grieved my heart to think what man has made of man.`,
      source: 'William Wordsworth, Lines Written in Early Spring (1798)',
      language: 'en',
      difficulty: 3,
      wordCount: 28,
      charCount: 133,
      tags: ["wordsworth", "nature", "reflection"],
    },
    {
      id: 'poe-en-25',
      content: `To see a World in a Grain of Sand and a Heaven in a Wild Flower.`,
      source: 'William Blake, Auguries of Innocence (c.1803)',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 64,
      tags: ["blake","infinity","nature"],
    },
    {
      id: 'poe-en-26',
      content: `O Captain! My Captain! our fearful trip is done.`,
      source: 'Walt Whitman, O Captain! My Captain! (1865)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 48,
      tags: ["whitman","lincoln","elegy"],
    },
    {
      id: 'poe-en-27',
      content: `Half a league, half a league, half a league onward, all in the valley of Death rode the six hundred.`,
      source: 'Alfred Lord Tennyson, The Charge of the Light Brigade (1854)',
      language: 'en',
      difficulty: 3,
      wordCount: 20,
      charCount: 100,
      tags: ["tennyson","battle","duty"],
    },
    {
      id: 'poe-en-28',
      content: `Let me not to the marriage of true minds admit impediments.`,
      source: 'William Shakespeare, Sonnet 116 (1609)',
      language: 'en',
      difficulty: 3,
      wordCount: 11,
      charCount: 59,
      tags: ["shakespeare","love","constancy"],
    },
    {
      id: 'poe-en-29',
      content: `Once upon a midnight dreary, while I pondered, weak and weary, over many a quaint and curious volume of forgotten lore.`,
      source: 'Edgar Allan Poe, The Raven (1845)',
      language: 'en',
      difficulty: 5,
      wordCount: 21,
      charCount: 119,
      tags: ["poe","raven","mystery"],
    },
    {
      id: 'poe-en-30',
      content: `Bright star, would I were steadfast as thou art.`,
      source: 'John Keats, Bright Star (1819)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 48,
      tags: ["keats","star","steadfast"],
    },
    {
      id: 'poe-fr-31',
      content: `Ainsi, toujours poussés vers de nouveaux rivages, Dans la nuit éternelle emportés sans retour, Ne pourrons-nous jamais sur l'océan des âges Jeter l'ancre un seul jour ? Ô lac ! l'année à peine a fini sa carrière, Et près des flots chéris qu'elle devait revoir, Regarde ! je viens seul m'asseoir sur cette pierre Où tu la vis s'asseoir !`,
      source: 'Alphonse de Lamartine, Le Lac (1820)',
      language: 'fr',
      difficulty: 3,
      wordCount: 60,
      charCount: 336,
      tags: ["lamartine", "romantisme", "nature"],
    },
    {
      id: 'poe-fr-32',
      content: `Oui, l'œuvre sort plus belle D'une forme au travail Rebelle, Vers, marbre, onyx, émail. Point de contraintes fausses ! Mais que pour marcher droit Tu chausses, Muse, un cothurne étroit ! Fi du rythme commode, Comme un soulier trop grand, Du mode Que tout pied quitte et prend !`,
      source: 'Théophile Gautier, L\'Art (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 49,
      charCount: 277,
      tags: ["gautier", "parnasse", "art poétique"],
    },
    {
      id: 'poe-fr-33',
      content: `Poëte, prends ton luth et me donne un baiser ; La fleur de l'églantier sent ses bourgeons éclore. Le printemps naît ce soir ; les vents vont s'embraser ; Et la bergeronnette, en attendant l'aurore, Aux premiers buissons verts commence à se poser. Poëte, prends ton luth, et me donne un baiser.`,
      source: 'Alfred de Musset, La Nuit de mai (1835)',
      language: 'fr',
      difficulty: 3,
      wordCount: 52,
      charCount: 293,
      tags: ["musset", "romantisme", "muse"],
    },
    {
      id: 'poe-fr-34',
      content: `Souvent, pour s'amuser, les hommes d'équipage Prennent des albatros, vastes oiseaux des mers, Qui suivent, indolents compagnons de voyage, Le navire glissant sur les gouffres amers. À peine les ont-ils déposés sur les planches, Que ces rois de l'azur, maladroits et honteux, Laissent piteusement leurs grandes ailes blanches Comme des avirons traîner à côté d'eux. Ce voyageur ailé, comme il est gauche et veule ! Lui, naguère si beau, qu'il est comique et laid ! L'un agace son bec avec un brûle-gueule, L'autre mime, en boitant, l'infirme qui volait ! Le Poëte est semblable au prince des nuées Qui hante la tempête et se rit de l'archer ; Exilé sur le sol au milieu des huées, Ses ailes de géant l'empêchent de marcher.`,
      source: 'Charles Baudelaire, L\'Albatros (1861)',
      language: 'fr',
      difficulty: 4,
      wordCount: 123,
      charCount: 722,
      tags: ["baudelaire", "symbolisme", "poète"],
    },
    {
      id: 'poe-fr-35',
      content: `Comme un vol de gerfauts hors du charnier natal, Fatigués de porter leurs misères hautaines, De Palos de Moguer, routiers et capitaines Partaient, ivres d'un rêve héroïque et brutal. Ils allaient conquérir le fabuleux métal Que Cipango mûrit dans ses mines lointaines, Et les vents alizés inclinaient leurs antennes Aux bords mystérieux du monde Occidental. Chaque soir, espérant des lendemains épiques, L'azur phosphorescent de la mer des Tropiques Enchantait leur sommeil d'un mirage doré ; Ou penchés à l'avant des blanches caravelles, Ils regardaient monter en un ciel ignoré Du fond de l'Océan des étoiles nouvelles.`,
      source: 'José-Maria de Heredia, Les Conquérants (1893)',
      language: 'fr',
      difficulty: 4,
      wordCount: 96,
      charCount: 621,
      tags: ["heredia", "parnasse", "exploration"],
    },
    {
      id: 'poe-fr-36',
      content: `Booz s'était couché de fatigue accablé ; Il avait tout le jour travaillé dans son aire ; Puis avait fait son lit à sa place ordinaire ; Booz dormait auprès des boisseaux pleins de blé. Ce vieillard possédait des champs de blés et d'orge ; Il était, quoique riche, à la justice enclin ; Il n'avait pas de fange en l'eau de son moulin ; Il n'avait pas d'enfer dans le feu de sa forge. Sa barbe était d'argent comme un ruisseau d'avril. Sa gerbe n'était point avare ni haineuse ; Quand il voyait passer quelque pauvre glaneuse : « Laissez tomber exprès des épis », disait-il.`,
      source: 'Victor Hugo, Booz endormi (1859)',
      language: 'fr',
      difficulty: 3,
      wordCount: 107,
      charCount: 572,
      tags: ["hugo", "romantisme", "biblique"],
    },
    {
      id: 'poe-en-31',
      content: `I'm Nobody! Who are you? Are you nobody, too? Then there's a pair of us—don't tell! They'd banish us, you know. How dreary to be somebody! How public, like a frog, To tell your name the livelong day To an admiring bog!`,
      source: 'Emily Dickinson, I\'m Nobody! Who are you? (c.1861)',
      language: 'en',
      difficulty: 2,
      wordCount: 42,
      charCount: 218,
      tags: ["dickinson", "american poetry", "identity"],
    },
    {
      id: 'poe-en-32',
      content: `She walks in beauty, like the night Of cloudless climes and starry skies; And all that's best of dark and bright Meet in her aspect and her eyes: Thus mellow'd to that tender light Which heaven to gaudy day denies.`,
      source: 'Lord Byron, She Walks in Beauty (1815)',
      language: 'en',
      difficulty: 3,
      wordCount: 40,
      charCount: 214,
      tags: ["byron", "romanticism", "beauty"],
    },
    {
      id: 'poe-en-33',
      content: `It was many and many a year ago, In a kingdom by the sea, That a maiden there lived whom you may know By the name of Annabel Lee;— And this maiden she lived with no other thought Than to love and be loved by me.`,
      source: 'Edgar Allan Poe, Annabel Lee (1849)',
      language: 'en',
      difficulty: 3,
      wordCount: 46,
      charCount: 211,
      tags: ["poe", "romanticism", "love"],
    },
    {
      id: 'poe-en-34',
      content: `When I have fears that I may cease to be Before my pen has glean'd my teeming brain, Before high pilèd books, in charactry, Hold like rich garners the full-ripen'd grain; When I behold, upon the night's starr'd face, Huge cloudy symbols of a high romance, And think that I may never live to trace Their shadows, with the magic hand of chance; And when I feel, fair creature of an hour! That I shall never look upon thee more, Never have relish in the faery power Of unreflecting love;—then on the shore Of the wide world I stand alone, and think Till Love and Fame to nothingness do sink.`,
      source: 'John Keats, When I Have Fears That I May Cease to Be (1818)',
      language: 'en',
      difficulty: 5,
      wordCount: 110,
      charCount: 588,
      tags: ["keats", "romanticism", "mortality"],
    },
    {
      id: 'poe-en-35',
      content: `The world is too much with us; late and soon, Getting and spending, we lay waste our powers: Little we see in nature that is ours; We have given our hearts away, a sordid boon! This Sea that bares her bosom to the moon; The Winds that will be howling at all hours And are up-gathered now like sleeping flowers; For this, for every thing, we are out of tune; It moves us not— Great God! I'd rather be A Pagan suckled in a creed outworn; So might I, standing on this pleasant lea, Have glimpses that would make me less forlorn Have sight of Proteus coming from the sea; Or hear old Triton blow his wreathed horn.`,
      source: 'William Wordsworth, The World Is Too Much with Us (1807)',
      language: 'en',
      difficulty: 4,
      wordCount: 118,
      charCount: 610,
      tags: ["wordsworth", "romanticism", "nature"],
    },
    {
      id: 'poe-en-36',
      content: `I celebrate myself, and sing myself, And what I assume you shall assume, For every atom belonging to me as good belongs to you. I loafe and invite my soul, I lean and loafe at my ease observing a spear of summer grass. My tongue, every atom of my blood, form'd from this soil, this air, Born here of parents born here from parents the same, and their parents the same, I, now thirty-seven years old in perfect health begin, Hoping to cease not till death.`,
      source: 'Walt Whitman, Song of Myself (1855)',
      language: 'en',
      difficulty: 3,
      wordCount: 86,
      charCount: 455,
      tags: ["whitman", "american poetry", "self"],
    },
    {
      id: 'poe-fr-37',
      content: `Voilà la poésie ce matin et pour la prose il y a les journaux. Il y a les livraisons à 25 centimes pleines d'aventures policières.`,
      source: 'Guillaume Apollinaire, Zone (1913)',
      language: 'fr',
      difficulty: 3,
      wordCount: 25,
      charCount: 130,
      tags: ["apollinaire", "modernisme", "chiffre"],
    },
    {
      id: 'poe-fr-38',
      content: `L'éclatante victoire de Sarrebrück, remportée aux cris de vive l'Empereur! Gravure belge brillamment coloriée, se vend à Charleroi, 35 centimes.`,
      source: 'Arthur Rimbaud, L\'Éclatante Victoire de Sarrebrück (1870)',
      language: 'fr',
      difficulty: 4,
      wordCount: 20,
      charCount: 144,
      tags: ["rimbaud", "satire", "chiffre"],
    },
    {
      id: 'poe-en-37',
      content: `IN FIELDING FORCE SERVICE. Encampment, 10th Jan. Dear Sir, I have honour to send, as you said, for final approval (see under) Boh's Head.`,
      source: 'Rudyard Kipling, The Ballad of Boh Da Thone (1892)',
      language: 'en',
      difficulty: 4,
      wordCount: 24,
      charCount: 137,
      tags: ["kipling", "ballad", "chiffre"],
    },
    {
      id: 'poe-en-38',
      content: `The mediaeval navigators rise before me, the world of 1492, with its awaken'd enterprise, something swelling in humanity now like the sap of the earth in spring, the sunset splendor of chivalry declining.`,
      source: 'Walt Whitman, Passage to India (1871)',
      language: 'en',
      difficulty: 3,
      wordCount: 33,
      charCount: 204,
      tags: ["whitman", "american poetry", "chiffre"],
    },
    {
      id: 'poe-en-39',
      content: `I met a traveller from an antique land, Who said: Two vast and trunkless legs of stone Stand in the desert. Near them, on the sand, Half sunk a shattered visage lies, whose frown, And wrinkled lip, and sneer of cold command, Tell that its sculptor well those passions read Which yet survive, stamped on these lifeless things, The hand that mocked them, and the heart that fed.`,
      source: 'Percy Bysshe Shelley, Ozymandias (1818)',
      language: 'en',
      difficulty: 4,
      wordCount: 68,
      charCount: 376,
      tags: ["shelley","sonnet","romantic"],
    },
    {
      id: 'poe-en-40',
      content: `The sea is calm to-night. The tide is full, the moon lies fair Upon the straits; on the French coast the light Gleams and is gone; the cliffs of England stand, Glimmering and vast, out in the tranquil bay. Come to the window, sweet is the night-air! Only, from the long line of spray Where the sea meets the moon-blanched land, Listen! you hear the grating roar Of pebbles which the waves draw back, and fling.`,
      source: 'Matthew Arnold, Dover Beach (1867)',
      language: 'en',
      difficulty: 4,
      wordCount: 76,
      charCount: 410,
      tags: ["arnold","victorian","sea"],
    },
    {
      id: 'poe-en-41',
      content: `Loveliest of trees, the cherry now Is hung with bloom along the bough, And stands about the woodland ride Wearing white for Eastertide. Now, of my threescore years and ten, Twenty will not come again, And take from seventy springs a score, It only leaves me fifty more. And since to look at things in bloom Fifty springs are little room, About the woodlands I will go To see the cherry hung with snow.`,
      source: 'A. E. Housman, A Shropshire Lad, II (1896)',
      language: 'en',
      difficulty: 3,
      wordCount: 74,
      charCount: 401,
      tags: ["housman","spring","time"],
    },
    {
      id: 'poe-en-42',
      content: `There will come soft rains and the smell of the ground, And swallows circling with their shimmering sound; And frogs in the pools singing at night, And wild plum trees in tremulous white, Robins will wear their feathery fire Whistling their whims on a low fence-wire; And not one will know of the war, not one Will care at last when it is done.`,
      source: 'Sara Teasdale, There Will Come Soft Rains (1918)',
      language: 'en',
      difficulty: 3,
      wordCount: 64,
      charCount: 344,
      tags: ["teasdale","nature","war"],
    },
    {
      id: 'poe-en-43',
      content: `Remember me when I am gone away, Gone far away into the silent land; When you can no more hold me by the hand, Nor I half turn to go yet turning stay. Remember me when no more day by day You tell me of our future that you planned: Only remember me; you understand It will be late to counsel then or pray.`,
      source: 'Christina Rossetti, Remember (1862)',
      language: 'en',
      difficulty: 4,
      wordCount: 64,
      charCount: 304,
      tags: ["rossetti","sonnet","memory"],
    },
    {
      id: 'poe-en-44',
      content: `That's my last Duchess painted on the wall, Looking as if she were alive. I call That piece a wonder, now: Fra Pandolf's hands Worked busily a day, and there she stands. Will't please you sit and look at her? I said Fra Pandolf by design, for never read Strangers like you that pictured countenance, The depth and passion of its earnest glance.`,
      source: 'Robert Browning, My Last Duchess (1842)',
      language: 'en',
      difficulty: 5,
      wordCount: 63,
      charCount: 344,
      tags: ["browning","monologue","victorian"],
    },
    {
      id: 'poe-en-45',
      content: `I will arise and go now, and go to Innisfree, And a small cabin build there, of clay and wattles made; Nine bean-rows will I have there, a hive for the honey-bee, And live alone in the bee-loud glade. And I shall have some peace there, for peace comes dropping slow, Dropping from the veils of the morning to where the cricket sings.`,
      source: 'William Butler Yeats, The Lake Isle of Innisfree (1890)',
      language: 'en',
      difficulty: 4,
      wordCount: 63,
      charCount: 333,
      tags: ["yeats","irish","nature"],
    },
    {
      id: 'poe-fr-39',
      content: `J'ai perdu ma force et ma vie, Et mes amis et ma gaîté ; J'ai perdu jusqu'à la fierté Qui faisait croire à mon génie. Quand j'ai connu la Vérité, J'ai cru que c'était une amie ; Quand je l'ai comprise et sentie, J'en étais déjà dégoûté. Et pourtant elle est éternelle, Et ceux qui se sont passés d'elle Ici-bas ont tout ignoré.`,
      source: 'Alfred de Musset, Tristesse (1840)',
      language: 'fr',
      difficulty: 3,
      wordCount: 63,
      charCount: 327,
      tags: ["musset","sonnet","romantisme"],
    },
    {
      id: 'poe-fr-40',
      content: `C'est un trou de verdure où chante une rivière Accrochant follement aux herbes des haillons D'argent ; où le soleil, de la montagne fière, Luit : c'est un petit val qui mousse de rayons. Un soldat jeune, bouche ouverte, tête nue, Et la nuque baignant dans le frais cresson bleu, Dort ; il est étendu dans l'herbe, sous la nue, Pâle dans son lit vert où la lumière pleut.`,
      source: 'Arthur Rimbaud, Le Dormeur du val (1870)',
      language: 'fr',
      difficulty: 4,
      wordCount: 69,
      charCount: 370,
      tags: ["rimbaud","guerre","nature"],
    },
    {
      id: 'poe-fr-41',
      content: `J'ai voulu ce matin te rapporter des roses ; Mais j'en avais tant pris dans mes ceintures closes Que les nœuds trop serrés n'ont pu les contenir. Les nœuds ont éclaté. Les roses envolées Dans le vent, à la mer s'en sont toutes allées. Elles ont suivi l'eau pour ne plus revenir.`,
      source: 'Marceline Desbordes-Valmore, Les Roses de Saadi (1860)',
      language: 'fr',
      difficulty: 3,
      wordCount: 52,
      charCount: 278,
      tags: ["desbordes-valmore","roses","romantisme"],
    },
    {
      id: 'poe-fr-42',
      content: `Les nuages couraient sur la lune enflammée Comme sur l'incendie on voit fuir la fumée, Et les bois étaient noirs jusques à l'horizon. Nous marchions sans parler, dans l'humide gazon, Dans la bruyère épaisse et dans les hautes brandes, Lorsque, sous des sapins pareils à ceux des Landes, Nous avons aperçu les grands ongles marqués Par les loups voyageurs que nous avions traqués.`,
      source: 'Alfred de Vigny, La Mort du loup (1843)',
      language: 'fr',
      difficulty: 4,
      wordCount: 63,
      charCount: 379,
      tags: ["vigny","nuit","stoicisme"],
    },
    {
      id: 'poe-fr-43',
      content: `Le vase où meurt cette verveine D'un coup d'éventail fut fêlé ; Le coup dut effleurer à peine, Aucun bruit ne l'a révélé. Mais la légère meurtrissure, Mordant le cristal chaque jour, D'une marche invisible et sûre En a fait lentement le tour.`,
      source: 'Sully Prudhomme, Le Vase brisé (1865)',
      language: 'fr',
      difficulty: 3,
      wordCount: 43,
      charCount: 242,
      tags: ["sully-prudhomme","parnasse","coeur"],
    },
    {
      id: 'poe-fr-44',
      content: `Midi, roi des étés, épandu sur la plaine, Tombe en nappes d'argent des hauteurs du ciel bleu. Tout se tait. L'air flamboie et brûle sans haleine ; La terre est assoupie en sa robe de feu. L'étendue est immense, et les champs n'ont point d'ombre, Et la source est tarie où buvaient les troupeaux ; La lointaine forêt, dont la lisière est sombre, Dort là-bas, immobile, en un pesant repos.`,
      source: 'Leconte de Lisle, Midi (1852)',
      language: 'fr',
      difficulty: 5,
      wordCount: 70,
      charCount: 387,
      tags: ["leconte-de-lisle","parnasse","ete"],
    },
  ],
};
