/**
 * Pools de contenu francais pour le mode Apprentissage (curriculum AZERTY).
 *
 * Donnees pures, sans logique. Les modules en aval (learning-content.ts, tache 6)
 * filtrent ces pools par touches autorisees et choisissent les paragraphes par tag.
 *
 * Contraintes verifiees par learning-texts.test.ts :
 *  - WORDS_FR_PLAIN      : chaque mot correspond a /^[a-z]+$/ (minuscules a-z, aucun
 *    accent, aucune ponctuation) ; 120 mots minimum.
 *  - WORDS_FR_PROPER     : capitale initiale, aucun accent ni circonflexe ;
 *    30 minimum.
 *  - WORDS_FR_ACCENTS    : au moins un caractere parmi e accent aigu, e accent grave,
 *    a accent grave, c cedille, u accent grave ; aucun circonflexe ni trema ;
 *    80 minimum.
 *  - WORDS_FR_CIRCUMFLEX : au moins un circonflexe ou trema ; 60 minimum.
 *  - LEARNING_PARAGRAPHS : 4 entrees minimum par tag ; texte original, neutre et
 *    didactique, de 150 a 600 caracteres ; contenu 100 pour cent original (regle
 *    CONTRIBUTING), aucune citation ni source tierce.
 *
 * Progression pedagogique : chaque stade isole une competence. Les paragraphes
 * "punctuation" restent volontairement sans accent ni chiffre, les "digits"
 * introduisent les nombres, les "full" melangent tout.
 */

/** Mots courants (2 a 8 lettres), minuscules strictes, sans accent ni ponctuation. */
export const WORDS_FR_PLAIN: string[] = [
  // Vie quotidienne, lieux, objets simples
  'le',
  'chat',
  'chien',
  'dort',
  'sur',
  'mur',
  'train',
  'part',
  'gare',
  'ville',
  'matin',
  'jardin',
  'fleur',
  'table',
  'livre',
  'porte',
  'route',
  'pont',
  'arbre',
  'pomme',
  'robe',
  'bras',
  'main',
  'pied',
  'nord',
  'sud',
  'jour',
  'nuit',
  'soir',
  'lune',
  'sol',
  'feu',
  'air',
  'eau',
  'vent',
  'pluie',
  'neige',
  'froid',
  'chaud',
  'vite',
  'lent',
  'grand',
  'petit',
  'haut',
  'bas',
  'loin',
  'ici',
  'oui',
  'non',
  'bon',
  'beau',
  'joli',
  'noir',
  'blanc',
  'bleu',
  'vert',
  'rouge',
  'jaune',
  'rose',
  'gris',
  'brun',
  // Mer et bord de mer
  'bois',
  'pierre',
  'sable',
  'herbe',
  'champ',
  'mer',
  'lac',
  'plage',
  'bateau',
  'voile',
  'quai',
  'phare',
  'roche',
  'galet',
  'dune',
  'vague',
  'marin',
  'poisson',
  'crabe',
  'mouette',
  'corde',
  'filet',
  'panier',
  'seau',
  'pelle',
  // Maison et objets
  'balai',
  'brosse',
  'savon',
  'linge',
  'drap',
  'matelas',
  'lampe',
  'chaise',
  'coussin',
  'tapis',
  'rideau',
  'placard',
  'tiroir',
  'miroir',
  'cadre',
  'vase',
  'plante',
  'bougie',
  'flamme',
  'cendre',
  // Bois et papeterie
  'souche',
  'tronc',
  'branche',
  'racine',
  'feuille',
  'graine',
  'terre',
  'boue',
  'argile',
  'craie',
  'plume',
  'encre',
  'stylo',
  'cahier',
  'crayon',
  'gomme',
  'carton',
  'colle',
  'ruban',
  'ficelle',
  'sac',
  'poche',
  'bouton',
  'fil',
  // Textile et habits
  'laine',
  'coton',
  'soie',
  'cuir',
  'toile',
  'tissu',
  'jupe',
  'veste',
  'manteau',
  'chapeau',
  'gant',
  'botte',
  'lacet',
  'chemise',
  'foulard',
  'montre',
  'bague',
  'collier',
  'perle',
  // Actions simples
  'marche',
  'saute',
  'monte',
  'tombe',
  'roule',
  'glisse',
  'nage',
  'vole',
  'plonge',
  'grimpe',
  'danse',
  'chante',
  'parle',
  'regarde',
  'ferme',
  'ouvre',
  'pousse',
  'tire',
  'pose',
  'donne',
  'garde',
  'cherche',
  'trouve',
  'gagne',
  'joue',
  'compte',
  'mesure',
  'coupe',
  'lave',
  'range',
  'tourne',
  'avance',
  'recule',
  'respire',
  'souffle',
  // Maison, nature, animaux
  'maison',
  'salle',
  'cuisine',
  'chambre',
  'cave',
  'toit',
  'volet',
  'sentier',
  'chemin',
  'colline',
  'source',
  'cascade',
  'ruisseau',
  'buisson',
  'mousse',
  'lierre',
  'sapin',
  'bouleau',
  'roseau',
  'brume',
  'givre',
  'orage',
  'nuage',
  'brise',
  'rafale',
  'loup',
  'ours',
  'lapin',
  'souris',
  'renard',
  'biche',
  'cerf',
  'sanglier',
  'lion',
  'tigre',
  'singe',
  'girafe',
  'panda',
  'hibou',
  'chouette',
  'corbeau',
  'pigeon',
  'moineau',
  'merle',
  'canard',
  'cygne',
  'faucon',
  'aigle',
];

/** Noms propres capitalises, sans accent ni circonflexe. */
export const WORDS_FR_PROPER: string[] = [
  // Villes
  'Paris',
  'Rome',
  'Lyon',
  'Nantes',
  'Dijon',
  'Lille',
  'Brest',
  'Rennes',
  'Tours',
  'Nancy',
  'Metz',
  'Reims',
  'Caen',
  'Nice',
  'Cannes',
  'Toulon',
  'Arras',
  'Blois',
  'Vichy',
  'Laval',
  'Vannes',
  'Lorient',
  'Quimper',
  'Bastia',
  'Ajaccio',
  'Calvi',
  // Prenoms
  'Marie',
  'Louis',
  'Anna',
  'Julie',
  'Simon',
  'Iris',
  'Nina',
  'Marc',
  'Paul',
  'Jules',
  'Clara',
  'Lola',
  'Emma',
  'Alice',
  'Hugo',
  'Louise',
  'Sarah',
  'Adam',
  'Lucas',
  'Manon',
  'Robin',
  'Oscar',
  'Victor',
  'Camille',
];

/**
 * Mots contenant au moins un accent direct (aigu, grave ou cedille) et jamais de
 * circonflexe ni de trema.
 */
export const WORDS_FR_ACCENTS: string[] = [
  // Accent aigu
  'été',
  'café',
  'école',
  'élève',
  'année',
  'journée',
  'soirée',
  'matinée',
  'idée',
  'musée',
  'lycée',
  'clé',
  'thé',
  'blé',
  'pré',
  'étoile',
  'échelle',
  'éléphant',
  'épée',
  'général',
  'médecin',
  'légume',
  'céleri',
  'cinéma',
  'numéro',
  'téléphone',
  'télé',
  'vérité',
  'société',
  'beauté',
  'santé',
  'bonté',
  'clarté',
  'fierté',
  'liberté',
  'égalité',
  'quantité',
  'qualité',
  'université',
  'réalité',
  'énergie',
  'économie',
  'écran',
  'étape',
  'état',
  'épais',
  'décor',
  'début',
  'défi',
  'délai',
  'député',
  'désert',
  'détail',
  'décidé',
  'préféré',
  'résumé',
  'invité',
  'employé',
  'marché',
  // Accent grave
  'près',
  'très',
  'après',
  'mère',
  'père',
  'frère',
  'règle',
  'pièce',
  'crème',
  'problème',
  'système',
  'thème',
  'poème',
  'scène',
  'règne',
  'lèvre',
  'fièvre',
  'zèbre',
  'chèvre',
  'lièvre',
  'colère',
  'misère',
  'rivière',
  'lumière',
  'manière',
  'première',
  'dernière',
  'matière',
  'carrière',
  'barrière',
  'prière',
  'entière',
  'légère',
  'étagère',
  'sévère',
  'célèbre',
  'modèle',
  'fidèle',
  'nièce',
  'siècle',
  'voilà',
  'déjà',
  'là',
  // Cedille
  'ça',
  'garçon',
  'leçon',
  'français',
  'façon',
  'aperçu',
  'déçu',
  'reçu',
  'maçon',
  'glaçon',
  'soupçon',
  'façade',
  'balançoire',
  'commerçant',
  'limaçon',
  // U accent grave
  'où',
];

/** Mots contenant au moins un accent circonflexe ou un trema. */
export const WORDS_FR_CIRCUMFLEX: string[] = [
  // Circonflexe sur e
  'être',
  'tête',
  'fête',
  'forêt',
  'bête',
  'rêve',
  'prêt',
  'arrêt',
  'crêpe',
  'pêche',
  'fenêtre',
  'hêtre',
  'guêpe',
  'tempête',
  'conquête',
  'enquête',
  'honnête',
  'arête',
  'bêtise',
  'prêtre',
  'ancêtre',
  'vêtement',
  'extrême',
  'suprême',
  'baptême',
  'carême',
  'même',
  'trêve',
  'grêle',
  'rêne',
  // Circonflexe sur o
  'hôpital',
  'hôtel',
  'côté',
  'rôle',
  'drôle',
  'diplôme',
  'contrôle',
  'trône',
  'cône',
  'pôle',
  'dôme',
  'arôme',
  'symptôme',
  'hôte',
  'plutôt',
  'aussitôt',
  'bientôt',
  'impôt',
  'dépôt',
  'côte',
  'apôtre',
  'rôti',
  // Circonflexe sur i
  'île',
  'dîner',
  'maître',
  'boîte',
  'naître',
  'chaîne',
  'fraîche',
  'paraître',
  'connaître',
  'abîme',
  'gîte',
  'huître',
  'cloître',
  'traître',
  // Circonflexe sur u
  'goût',
  'coût',
  'août',
  'croûte',
  'flûte',
  'bûche',
  'sûr',
  'piqûre',
  'brûler',
  'voûte',
  'jeûne',
  'mûr',
  // Trema
  'Noël',
  'canoë',
  'aiguë',
  'maïs',
  'naïf',
  'haïr',
  'égoïste',
  'héroïne',
  'mosaïque',
  'faïence',
  'inouï',
  'aïeul',
  'laïque',
];

/** Un paragraphe d'entrainement, associe a un ou plusieurs stades du curriculum. */
export interface LearningParagraph {
  tags: ('punctuation' | 'digits' | 'full')[];
  text: string;
}

/**
 * Paragraphes originaux, neutres et didactiques (frappe, quotidien, nature).
 * Aucun tiret cadratin ni demi-cadratin : seuls le point, la virgule, le
 * point-virgule, les deux-points, le point d'exclamation, le point
 * d'interrogation, l'apostrophe droite et le trait d'union sont utilises.
 */
export const LEARNING_PARAGRAPHS: LearningParagraph[] = [
  // --- Stade ponctuation : riche en signes, sans chiffre. Les accents sont
  //     acquis (niveaux 7 et 8) avant ce stade (niveau 9). ---
  {
    tags: ['punctuation'],
    text: "Pose les doigts sur la rangée du milieu, respire, puis avance lettre par lettre. Ne fixe pas le clavier: garde les yeux sur le texte. Une touche résiste? Ralentis un peu; la vitesse revient d'elle-même. Espace, virgule, point-virgule: chaque signe compte autant qu'une lettre. Détends les épaules, souffle, et continue sans t'arrêter!",
  },
  {
    tags: ['punctuation'],
    text: "Le rythme, c'est presque tout: frappe, pause, frappe. Un texte propre respire grâce à la ponctuation. La virgule marque un souffle court; le point ferme l'idée. Les deux-points annoncent: une liste, une cause, une précision. Le point d'interrogation attend une réponse, n'est-ce pas? Le trait d'union relie deux mots, comme dans arc-en-ciel. Garde-le en tête!",
  },
  {
    tags: ['punctuation'],
    text: "Chaque signe a sa place. En français courant, la virgule et le point se collent au mot; le point-virgule, les deux-points et le point d'exclamation prennent une espace avant. Teste, relis, corrige. Une phrase claire tient sur un souffle: sujet, verbe, complément. Trop de virgules hachent le sens; trop peu l'étouffent. Une question? Un seul signe suffit. Vise l'équilibre!",
  },
  {
    tags: ['punctuation'],
    text: "Entraîne-toi sur des phrases simples avant les longues. Commence: un sujet, un verbe, un point. Ajoute ensuite une incise, entre virgules, pour préciser. Puis relie deux idées proches par un point-virgule; l'effet est net. Termine par une exclamation quand le ton monte! Ou par une interrogation, si le doute reste, d'accord? La ponctuation guide le regard autant que la voix.",
  },
  {
    tags: ['punctuation'],
    text: "Un dernier conseil sur les signes: lis la phrase à voix haute avant de la taper. Là où tu respires, mets une virgule; là où tu t'arrêtes, mets un point. Besoin de lier deux idées proches? Un point-virgule fait le pont. Besoin d'annoncer une suite? Deux-points. Un cri, une surprise, un ordre bref: le point d'exclamation! Et si le doute reste, l'interrogation attend, patiente.",
  },

  // --- Stade chiffres : dates, quantites, prix ---
  {
    tags: ['digits'],
    text: "Le 14 juillet, 3 amis partent à 8 heures du matin. Ils emportent 250 grammes de pain, 2 litres d'eau et 4 pommes. Le train roule à 120 kilomètres par heure et arrive à 11 h 30. La marche fait 7 kilomètres, avec 300 mètres de montée. Retour prévu vers 18 h, pour un budget de 25 euros par personne.",
  },
  {
    tags: ['digits'],
    text: "Une séance de frappe efficace dure 20 minutes. Vise 30 mots par minute la première semaine, puis 45 le mois suivant. Fais 3 séries de 5 lignes, avec 60 secondes de pause entre chaque. Note ton score sur 100 et compare-le à celui de la veille. En 21 jours, une habitude se forme; en 90 jours, elle tient bon.",
  },
  {
    tags: ['digits'],
    text: "Au marché, le kilo de carottes coûte 2 euros, les oeufs 3 euros la douzaine. Pour 6 personnes, prends 1 kilo de riz, 500 grammes de beurre et 2 salades. La recette demande 4 étapes et 35 minutes de cuisson à 180 degrés. Sers 2 louches par assiette. Il reste 12 euros sur les 40 du départ.",
  },
  {
    tags: ['digits'],
    text: "Le bureau ouvre à 9 h et ferme à 17 h, du lundi au vendredi. La salle 2 compte 15 postes, la salle 3 en compte 18. Chaque cours dure 50 minutes, avec 10 minutes de battement. En 1 trimestre, un groupe suit 24 séances et tape près de 40 000 signes. Le niveau se mesure tous les 15 jours.",
  },
  {
    tags: ['digits'],
    text: "Règle des paliers: on ne monte le rythme qu'après deux séances propres. Semaine 1, vise 25 mots par minute; semaine 2, vise 33; semaine 3, vise 40. Une faute pour 8 lignes reste acceptable, pas plus. Repose les mains 5 secondes toutes les 3 lignes. En 4 semaines, le gain moyen atteint 60 pour cent.",
  },

  // --- Stade complet : majuscules, accents, circonflexes, ponctuation, chiffres ---
  {
    tags: ['full'],
    text: "Aujourd'hui, 5 élèves testent la méthode complète. Marie tape la première ligne à 42 mots par minute; Hugo suit de près. La règle est simple: une majuscule après le point, une virgule pour le souffle, un accent là où il se doit. Le texte parle d'été, de forêt et de rivière. En 15 minutes, chacun écrit 3 phrases nettes, relève son score et recommence. La constance paie!",
  },
  {
    tags: ['full'],
    text: "Le 2 mars, l'atelier reprend à 14 heures. Thème du jour: la ponctuation fine et les nombres. Chloé relit son paragraphe, corrige deux fautes d'accent, puis ajoute un point-virgule là où la phrase penchait. Objectif: 50 mots par minute sans erreur sur 4 lignes. Le formateur rappelle une chose: mieux vaut lent et juste que vite et faux! On reprend à zéro, calmement.",
  },
  {
    tags: ['full'],
    text: "Nina prépare un carnet de bord. En haut de chaque page: la date, l'heure, la durée. Elle écrit trois colonnes: mots par minute, fautes, ressenti. Le 9 avril, elle passe de 38 à 44, avec 2 fautes seulement. La clé, note-t-elle, tient en un mot: régularité. Trente minutes par jour valent mieux qu'une heure le dimanche. Demain, même heure, même place; on continue.",
  },
  {
    tags: ['full'],
    text: "Simon revient sur les touches difficiles. Les chiffres, d'abord: le 1, le 2 et le 0 lui échappent encore. Puis les accents, là où la main hésite. Il tape une phrase test, la relit à voix basse, souligne chaque faute. Résultat du jour: 4 erreurs sur 5 lignes, contre 9 la veille. Le progrès est net, même s'il reste lent. Patience: une semaine de plus et le geste sera sûr.",
  },
  {
    tags: ['full'],
    text: "Julie ferme la session par un bilan court. Trois questions: qu'est-ce qui a bloqué? qu'est-ce qui a coulé tout seul? que viser demain? Le 30 du mois, son score grimpe à 55 mots par minute, avec 1 faute sur 6 lignes. Elle range le carnet, étire les poignets, souffle un grand coup. La musique s'arrête à la dernière note: la page est propre, l'exercice est fini!",
  },
];
