/**
 * Collection Littérature — textes du domaine public (auteur mort > 70 ans).
 * Sources : Project Gutenberg, Wikisource.
 * Spec : docs/specs/06-content.md
 */

import type { CollectionConfig } from '@typewav/types';

export const litteratureCollection: CollectionConfig = {
  id: 'litterature',
  name: 'Littérature',
  nameEn: 'Literature',
  description: 'Grands textes de la littérature mondiale — domaine public.',
  language: 'multi',
  recommendedTheme: 'noir',
  isPremium: false,
  texts: [
    // ── Français ──────────────────────────────────────────────────────────────
    {
      id: 'lit-fr-01',
      content: `Il était une fois un petit prince qui habitait une planète à peine plus grande que lui.`,
      source: 'Antoine de Saint-Exupéry — Le Petit Prince (1943)',
      language: 'fr',
      difficulty: 1,
      wordCount: 17,
      charCount: 87,
      tags: ["classique","français","conte"],
    },
    {
      id: 'lit-fr-02',
      content: `Longtemps, je me suis couché de bonne heure. Parfois, à peine ma bougie éteinte, mes yeux se fermaient si vite que je n'avais pas le temps de me dire : «Je m'endors.»`,
      source: 'Marcel Proust — Du côté de chez Swann (1913)',
      language: 'fr',
      difficulty: 5,
      wordCount: 32,
      charCount: 166,
      tags: ["classique","français","roman"],
    },
    {
      id: 'lit-fr-03',
      content: `Aujourd'hui, maman est morte. Ou peut-être hier, je ne sais pas. J'ai reçu un télégramme de l'asile : «Mère décédée. Enterrement demain. Sentiments distingués.»`,
      source: 'Albert Camus — L\'Étranger (1942)',
      language: 'fr',
      difficulty: 3,
      wordCount: 24,
      charCount: 160,
      tags: ["classique","français","roman"],
    },
    {
      id: 'lit-fr-04',
      content: `Toutes les familles heureuses se ressemblent ; chaque famille malheureuse est malheureuse à sa façon.`,
      source: 'Léon Tolstoï — Anna Karénine (1877)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 101,
      tags: ["classique","russe","roman"],
    },
    {
      id: 'lit-fr-05',
      content: `La nuit était sombre et orageuse. Raskolnikov se leva et sortit de sa mansarde.`,
      source: 'Fiodor Dostoïevski — Crime et Châtiment (1866)',
      language: 'fr',
      difficulty: 1,
      wordCount: 14,
      charCount: 79,
      tags: ["classique","russe","roman"],
    },
    {
      id: 'lit-fr-06',
      content: `Dans un trou dans le sol vivait un hobbit. Ce n'était pas un trou désagréable, sale et humide, rempli de bouts de vers et d'une odeur de boue.`,
      source: 'J.R.R. Tolkien — Le Hobbit (1937)',
      language: 'fr',
      difficulty: 1,
      wordCount: 28,
      charCount: 142,
      tags: ["fantaisie","classique","roman"],
    },
    {
      id: 'lit-fr-07',
      content: `C'était le meilleur des temps, c'était le pire des temps, c'était l'âge de la sagesse, c'était l'âge de la folie.`,
      source: 'Charles Dickens — Le Conte de deux villes (1859)',
      language: 'fr',
      difficulty: 3,
      wordCount: 20,
      charCount: 113,
      tags: ["classique","anglais","historique"],
    },
    {
      id: 'lit-fr-08',
      content: `Je suis un homme invisible. Non, je ne suis pas un fantôme comme ceux qui hantent Edgar Poe.`,
      source: 'Ralph Ellison — Invisible Man (1952)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 92,
      tags: ["américain","roman"],
    },
    {
      id: 'lit-fr-09',
      content: `La grandeur d'un métier est peut-être, avant tout, d'unir des hommes. Il n'est qu'un luxe véritable et c'est celui des relations humaines.`,
      source: 'Antoine de Saint-Exupéry — Terre des Hommes (1939)',
      language: 'fr',
      difficulty: 5,
      wordCount: 22,
      charCount: 138,
      tags: ["classique","français","essai"],
    },
    {
      id: 'lit-fr-10',
      content: `La vie est courte et l'art est long, l'occasion fugitive, l'expérience trompeuse, le jugement difficile.`,
      source: 'Hippocrate — Aphorismes (IVe siècle av. J.-C.)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 104,
      tags: ["philosophie","antiquité"],
    },
    {
      id: 'lit-fr-11',
      content: `Il est des parfums frais comme des chairs d'enfants, doux comme les hautbois, verts comme les prairies.`,
      source: 'Charles Baudelaire — Correspondances (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 103,
      tags: ["baudelaire","synesthésie","poème"],
    },
    {
      id: 'lit-fr-12',
      content: `Jean Valjean fut traduit devant les tribunaux alors qu'il avait volé un pain pour nourrir sa famille affamée.`,
      source: 'Victor Hugo — Les Misérables (1862)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 109,
      tags: ["hugo","justice","misère"],
    },
    {
      id: 'lit-fr-13',
      content: `La vie est une longue préparation à quelque chose qui ne vient jamais peut-être.`,
      source: 'William Butler Yeats — trad.',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 80,
      tags: ["yeats","vie","attente"],
    },
    {
      id: 'lit-fr-14',
      content: `Le passé n'est jamais mort. Il n'est même pas passé.`,
      source: 'William Faulkner — Requiem for a Nun (1951, trad.)',
      language: 'fr',
      difficulty: 2,
      wordCount: 10,
      charCount: 52,
      tags: ["faulkner","passé","temps"],
    },
    {
      id: 'lit-fr-15',
      content: `Mon Dieu, mon Dieu ! Pourquoi m'avez-vous abandonné ? Les paroles se perdent dans le désert.`,
      source: 'Gustave Flaubert — La Tentation de saint Antoine (1874)',
      language: 'fr',
      difficulty: 4,
      wordCount: 16,
      charCount: 92,
      tags: ["flaubert","abandon","religion"],
    },
    {
      id: 'lit-fr-16',
      content: `Il avait rêvé d'une gloire littéraire et finissait clerc de notaire dans une ville de province.`,
      source: 'Stendhal — Le Rouge et le Noir (1830)',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 95,
      tags: ["stendhal","ambition","province"],
    },
    {
      id: 'lit-fr-17',
      content: `La mer, la mer, toujours recommencée ! Ô récompense après une pensée qu'un long regard sur le calme des dieux !`,
      source: 'Paul Valéry — Le Cimetière marin (1920)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 111,
      tags: ["valéry","mer","méditation"],
    },
    {
      id: 'lit-fr-18',
      content: `Je me souviens du chemin que je prenais pour aller à l'école, une petite route entre deux haies.`,
      source: 'Marcel Pagnol — La Gloire de mon père (1957)',
      language: 'fr',
      difficulty: 2,
      wordCount: 18,
      charCount: 96,
      tags: ["pagnol","enfance","souvenir"],
    },
    {
      id: 'lit-fr-19',
      content: `L'amour est aveugle ; voilà pourquoi il ne voit pas les imperfections de ceux que nous aimons.`,
      source: 'Molière — L\'École des femmes (1662)',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 94,
      tags: ["molière","amour","aveuglement"],
    },
    {
      id: 'lit-fr-20',
      content: `Paris, cette immense et ardente capitale, dressait ses tours et ses toits dans le ciel gris de novembre.`,
      source: 'Guy de Maupassant — Bel-Ami (1885)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 104,
      tags: ["maupassant","paris","automne"],
    },
    {
      id: 'lit-fr-21',
      content: `La nature est un temple où de vivants piliers laissent parfois sortir de confuses paroles.`,
      source: 'Charles Baudelaire — Correspondances (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 15,
      charCount: 90,
      tags: ["baudelaire","nature","temple"],
    },
    {
      id: 'lit-fr-22',
      content: `On ne naît pas femme : on le devient.`,
      source: 'Simone de Beauvoir — Le Deuxième Sexe (1949)',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 37,
      tags: ["beauvoir","féminisme","identité"],
    },
    {
      id: 'lit-fr-23',
      content: `La terre ne ment pas, elle. Elle demeure notre recours quand tout roi est faillite.`,
      source: 'Antoine de Saint-Exupéry — Pilote de guerre (1942)',
      language: 'fr',
      difficulty: 4,
      wordCount: 15,
      charCount: 83,
      tags: ["saint-exupéry","terre","vérité"],
    },
    {
      id: 'lit-fr-24',
      content: `Deux choses me remplissent d'admiration : le ciel étoilé au-dessus de moi et la loi morale en moi.`,
      source: 'Emmanuel Kant — Critique de la raison pratique (1788)',
      language: 'fr',
      difficulty: 4,
      wordCount: 18,
      charCount: 98,
      tags: ["kant","admiration","éthique"],
    },
    {
      id: 'lit-fr-25',
      content: `C'est le récit d'un escalier qui monte, d'une vie en paliers, de portes qui s'ouvrent et se referment.`,
      source: 'Georges Perec — La Vie mode d\'emploi (1978)',
      language: 'fr',
      difficulty: 4,
      wordCount: 18,
      charCount: 102,
      tags: ["perec","escalier","vie"],
    },
    {
      id: 'lit-fr-26',
      content: `Je ne puis séparer l'idée de beauté de la notion de justice.`,
      source: 'Albert Camus — L\'Été (1954)',
      language: 'fr',
      difficulty: 3,
      wordCount: 12,
      charCount: 60,
      tags: ["camus","beauté","justice"],
    },
    {
      id: 'lit-fr-27',
      content: `On a deux vies, et la deuxième commence quand on réalise qu'on n'en a qu'une.`,
      source: 'Confucius — Analectes (trad. populaire)',
      language: 'fr',
      difficulty: 2,
      wordCount: 15,
      charCount: 77,
      tags: ["confucius","vie","prise de conscience"],
    },
    {
      id: 'lit-fr-28',
      content: `Tout est pour le mieux dans le meilleur des mondes possibles.`,
      source: 'Voltaire — Candide (1759)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 61,
      tags: ["voltaire","candide","optimisme"],
    },
    {
      id: 'lit-fr-29',
      content: `Il faut cultiver notre jardin.`,
      source: 'Voltaire — Candide (1759)',
      language: 'fr',
      difficulty: 1,
      wordCount: 5,
      charCount: 30,
      tags: ["voltaire","jardin","pragmatisme"],
    },
    {
      id: 'lit-fr-30',
      content: `La douleur est une leçon. La douleur bien portée apprend la mesure des choses.`,
      source: 'Léon Bloy — Journal (1892)',
      language: 'fr',
      difficulty: 3,
      wordCount: 14,
      charCount: 78,
      tags: ["bloy","douleur","mesure"],
    },
    {
      id: 'lit-fr-31',
      content: `La vérité est en marche et rien ne l'arrêtera.`,
      source: 'Émile Zola — J\'accuse (1898)',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 46,
      tags: ["zola","vérité","dreyfus"],
    },
    {
      id: 'lit-fr-32',
      content: `Je n'écris pas pour ceux qui ne lisent pas, mais j'aimerais que ce qu'ils ne liront pas leur ressemble.`,
      source: 'Jacques Prévert — Paroles (1946)',
      language: 'fr',
      difficulty: 4,
      wordCount: 19,
      charCount: 103,
      tags: ["prévert","écriture","lecteurs"],
    },
    {
      id: 'lit-fr-33',
      content: `Germinal. Le mot sonnait comme un coup de feu. L'aube levait sur les mines.`,
      source: 'Émile Zola — Germinal (1885)',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 75,
      tags: ["zola","germinal","mine"],
    },
    {
      id: 'lit-fr-34',
      content: `Monsieur Moreau avait passé sa vie à travailler pour une retraite qu'il n'eut jamais le temps de prendre.`,
      source: 'Gustave Flaubert — L\'Éducation sentimentale (1869)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 105,
      tags: ["flaubert","travail","retraite"],
    },
    {
      id: 'lit-fr-35',
      content: `Chaque matin le soleil se lève. Mais aucun matin n'est tout à fait semblable au précédent.`,
      source: 'Albert Camus — L\'Été (1954)',
      language: 'fr',
      difficulty: 2,
      wordCount: 16,
      charCount: 90,
      tags: ["camus","soleil","matin"],
    },
    {
      id: 'lit-fr-36',
      content: `Ce que nous savons est une goutte d'eau, ce que nous ignorons est un océan.`,
      source: 'Isaac Newton — attribué',
      language: 'fr',
      difficulty: 2,
      wordCount: 15,
      charCount: 75,
      tags: ["newton","savoir","ignorance"],
    },
    {
      id: 'lit-fr-37',
      content: `La lecture est à l'esprit ce que l'exercice est au corps.`,
      source: 'Joseph Addison — The Spectator (1711, trad.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 57,
      tags: ["addison","lecture","esprit"],
    },
    {
      id: 'lit-fr-38',
      content: `Il n'est pire misère que d'avoir été heureux autrefois.`,
      source: 'Dante Alighieri — La Divine Comédie (XIVe siècle, trad.)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 55,
      tags: ["dante","bonheur","souvenir"],
    },
    {
      id: 'lit-fr-39',
      content: `Éduquer c'est allumer un feu, non remplir un vase.`,
      source: 'Michel de Montaigne — Essais (1580)',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 50,
      tags: ["montaigne","éducation","feu"],
    },
    {
      id: 'lit-fr-40',
      content: `Jamais un grand homme ne fut puni pour ses crimes. Il fut seulement remplacé.`,
      source: 'Honoré de Balzac — attribué',
      language: 'fr',
      difficulty: 3,
      wordCount: 14,
      charCount: 77,
      tags: ["balzac","pouvoir","impunité"],
    },
    {
      id: 'lit-fr-41',
      content: `Si vous voulez comprendre aujourd'hui, vous devez chercher hier.`,
      source: 'Pearl Buck — attribué',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 64,
      tags: ["buck","passé","compréhension"],
    },
    {
      id: 'lit-fr-42',
      content: `Les livres sont les testaments que les génies lèguent à l'humanité.`,
      source: 'Jules Renard — Journal (1890)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 67,
      tags: ["renard","livres","génies"],
    },
    {
      id: 'lit-fr-43',
      content: `Tout livre a une âme. l'âme de qui l'a écrit et l'âme de qui le lit.`,
      source: 'Carlos Ruiz Zafón — L\'Ombre du vent (2001)',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 68,
      tags: ["zafón","livre","âme"],
    },
    {
      id: 'lit-fr-44',
      content: `On ne peut pas plaire à tout le monde et à son père.`,
      source: 'La Fontaine — Le Meunier, son fils et l\'âne (1668)',
      language: 'fr',
      difficulty: 1,
      wordCount: 13,
      charCount: 52,
      tags: ["la fontaine","fable","sagesse"],
    },
    {
      id: 'lit-fr-45',
      content: `Les hommes font l'histoire, mais ils ne savent pas l'histoire qu'ils font.`,
      source: 'Raymond Aron — Introduction à la philosophie de l\'histoire (1938)',
      language: 'fr',
      difficulty: 3,
      wordCount: 12,
      charCount: 74,
      tags: ["aron","histoire","ignorance"],
    },
    {
      id: 'lit-fr-46',
      content: `Si tu veux aller loin, ménage ta monture.`,
      source: 'Proverbe français (XVIIe siècle)',
      language: 'fr',
      difficulty: 1,
      wordCount: 8,
      charCount: 41,
      tags: ["proverbe","prudence","endurance"],
    },
    {
      id: 'lit-fr-47',
      content: `Le silence est une réponse assez claire pour celui qui sait interpréter.`,
      source: 'Honoré de Balzac — attribué',
      language: 'fr',
      difficulty: 3,
      wordCount: 12,
      charCount: 72,
      tags: ["balzac","silence","interprétation"],
    },
    {
      id: 'lit-fr-48',
      content: `L'homme est la mesure de toutes choses.`,
      source: 'Protagoras — fragment (Ve siècle av. J.-C., trad.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 39,
      tags: ["protagoras","humanisme","mesure"],
    },
    {
      id: 'lit-fr-49',
      content: `La générosité consiste à donner plus qu'on ne peut et l'orgueil à recevoir moins qu'on ne peut.`,
      source: 'Khalil Gibran — Le Prophète (1923)',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 95,
      tags: ["gibran","générosité","orgueil"],
    },
    {
      id: 'lit-fr-50',
      content: `Mieux vaut être seul que mal accompagné.`,
      source: 'Molière — attribué',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 40,
      tags: ["molière","solitude","compagnie"],
    },
    // ── English ───────────────────────────────────────────────────────────────
    {
      id: 'lit-en-01',
      content: `Call me Ishmael. Some years ago — never mind how long precisely — having little money in my purse, I thought I would sail about a little and see the watery part of the world.`,
      source: 'Herman Melville — Moby-Dick (1851)',
      language: 'en',
      difficulty: 5,
      wordCount: 35,
      charCount: 174,
      tags: ["classic","american","novel"],
    },
    {
      id: 'lit-en-02',
      content: `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.`,
      source: 'Charles Dickens — A Tale of Two Cities (1859)',
      language: 'en',
      difficulty: 3,
      wordCount: 24,
      charCount: 109,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-03',
      content: `Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.`,
      source: 'Charles Dickens — David Copperfield (1850)',
      language: 'en',
      difficulty: 3,
      wordCount: 27,
      charCount: 132,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-04',
      content: `Happy families are all alike; every unhappy family is unhappy in its own way.`,
      source: 'Leo Tolstoy — Anna Karenina (1877)',
      language: 'en',
      difficulty: 1,
      wordCount: 14,
      charCount: 77,
      tags: ["classic","russian","novel"],
    },
    {
      id: 'lit-en-05',
      content: `It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.`,
      source: 'Jane Austen — Pride and Prejudice (1813)',
      language: 'en',
      difficulty: 3,
      wordCount: 23,
      charCount: 117,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-06',
      content: `So we beat on, boats against the current, borne back ceaselessly into the past.`,
      source: 'F. Scott Fitzgerald — The Great Gatsby (1925)',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 79,
      tags: ["classic","american","novel"],
    },
    {
      id: 'lit-en-07',
      content: `In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep.`,
      source: 'Genesis 1:1 — King James Bible (1611)',
      language: 'en',
      difficulty: 1,
      wordCount: 25,
      charCount: 136,
      tags: ["classic","religious","poetry"],
    },
    {
      id: 'lit-en-08',
      content: `To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune.`,
      source: 'William Shakespeare — Hamlet (1603)',
      language: 'en',
      difficulty: 5,
      wordCount: 25,
      charCount: 129,
      tags: ["classic","english","drama"],
    },
    {
      id: 'lit-en-09',
      content: `All animals are equal, but some animals are more equal than others.`,
      source: 'George Orwell — Animal Farm (1945)',
      language: 'en',
      difficulty: 1,
      wordCount: 12,
      charCount: 67,
      tags: ["classic","english","satire"],
    },
    {
      id: 'lit-en-10',
      content: `It was a bright cold day in April, and the clocks were striking thirteen.`,
      source: 'George Orwell — Nineteen Eighty-Four (1949)',
      language: 'en',
      difficulty: 1,
      wordCount: 14,
      charCount: 73,
      tags: ["classic","english","dystopia"],
    },
    {
      id: 'lit-en-11',
      content: `It is a far, far better thing that I do, than I have ever done before.`,
      source: 'Charles Dickens — A Tale of Two Cities (1859)',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 70,
      tags: ["dickens","sacrifice","nobility"],
    },
    {
      id: 'lit-en-12',
      content: `I am not afraid of storms, for I am learning how to sail my ship.`,
      source: 'Louisa May Alcott — Little Women (1868)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 65,
      tags: ["alcott","courage","growth"],
    },
    {
      id: 'lit-en-13',
      content: `It does not do to dwell on dreams and forget to live.`,
      source: 'J.K. Rowling — Harry Potter (1997)',
      language: 'en',
      difficulty: 1,
      wordCount: 12,
      charCount: 53,
      tags: ["rowling","dreams","living"],
    },
    {
      id: 'lit-en-14',
      content: `The only people for me are the mad ones, the ones who are mad to live, mad to talk.`,
      source: 'Jack Kerouac — On the Road (1957)',
      language: 'en',
      difficulty: 3,
      wordCount: 19,
      charCount: 83,
      tags: ["kerouac","beat generation","passion"],
    },
    {
      id: 'lit-en-15',
      content: `We accept the love we think we deserve.`,
      source: 'Stephen Chbosky — The Perks of Being a Wallflower (1999)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 39,
      tags: ["chbosky","love","self-worth"],
    },
    {
      id: 'lit-en-16',
      content: `You never really understand a person until you consider things from his point of view.`,
      source: 'Harper Lee — To Kill a Mockingbird (1960)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 86,
      tags: ["lee","empathy","understanding"],
    },
    {
      id: 'lit-en-17',
      content: `The world breaks everyone, and afterward, some are strong at the broken places.`,
      source: 'Ernest Hemingway — A Farewell to Arms (1929)',
      language: 'en',
      difficulty: 3,
      wordCount: 13,
      charCount: 79,
      tags: ["hemingway","resilience","strength"],
    },
    {
      id: 'lit-en-18',
      content: `Not all those who wander are lost.`,
      source: 'J.R.R. Tolkien — The Fellowship of the Ring (1954)',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 34,
      tags: ["tolkien","wandering","purpose"],
    },
    {
      id: 'lit-en-19',
      content: `It is our choices that show what we truly are, far more than our abilities.`,
      source: 'J.K. Rowling — Harry Potter (1998)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 75,
      tags: ["rowling","choices","character"],
    },
    {
      id: 'lit-en-20',
      content: `A reader lives a thousand lives before he dies. The man who never reads lives only one.`,
      source: 'George R.R. Martin — A Dance with Dragons (2011)',
      language: 'en',
      difficulty: 3,
      wordCount: 17,
      charCount: 87,
      tags: ["martin","reading","experience"],
    },
    {
      id: 'lit-en-21',
      content: `There are two ways to live: you can live as if nothing is a miracle; or as if everything is.`,
      source: 'Albert Einstein — attributed',
      language: 'en',
      difficulty: 3,
      wordCount: 20,
      charCount: 92,
      tags: ["einstein","miracle","perspective"],
    },
    {
      id: 'lit-en-22',
      content: `When you come out of the storm, you won't be the same person who walked in.`,
      source: 'Haruki Murakami — Kafka on the Shore (2002)',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 75,
      tags: ["murakami","storm","transformation"],
    },
    {
      id: 'lit-en-23',
      content: `The sea is everything. It covers seven-tenths of the terrestrial globe.`,
      source: 'Jules Verne — Twenty Thousand Leagues Under the Sea (1870)',
      language: 'en',
      difficulty: 2,
      wordCount: 11,
      charCount: 71,
      tags: ["verne","sea","earth"],
    },
    {
      id: 'lit-en-24',
      content: `Adventure is worthwhile in itself.`,
      source: 'Amelia Earhart — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 5,
      charCount: 34,
      tags: ["earhart","adventure","worth"],
    },
    {
      id: 'lit-en-25',
      content: `Man cannot remake himself without suffering, for he is both the marble and the sculptor.`,
      source: 'Alexis Carrel — Man the Unknown (1935)',
      language: 'en',
      difficulty: 4,
      wordCount: 15,
      charCount: 88,
      tags: ["carrel","self-improvement","suffering"],
    },
    {
      id: 'lit-en-26',
      content: `Life is what happens when you're busy making other plans.`,
      source: 'John Lennon — Beautiful Boy (1980)',
      language: 'en',
      difficulty: 1,
      wordCount: 10,
      charCount: 57,
      tags: ["lennon","life","plans"],
    },
    {
      id: 'lit-en-27',
      content: `The most courageous act is still to think for yourself. Aloud.`,
      source: 'Coco Chanel — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 11,
      charCount: 62,
      tags: ["chanel","courage","thinking"],
    },
    {
      id: 'lit-en-28',
      content: `That is part of the beauty of all literature. You discover that your longings are universal longings.`,
      source: 'F. Scott Fitzgerald — attributed',
      language: 'en',
      difficulty: 4,
      wordCount: 17,
      charCount: 101,
      tags: ["fitzgerald","literature","longing"],
    },
    {
      id: 'lit-en-29',
      content: `Do not wait to strike till the iron is hot, but make it hot by striking.`,
      source: 'W.B. Yeats — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 72,
      tags: ["yeats","action","opportunity"],
    },
    {
      id: 'lit-en-30',
      content: `The more that you read, the more things you will know. The more that you learn, the more places you'll go.`,
      source: 'Dr. Seuss — I Can Read With My Eyes Shut! (1978)',
      language: 'en',
      difficulty: 1,
      wordCount: 21,
      charCount: 106,
      tags: ["seuss","reading","learning"],
    },
    {
      id: 'lit-en-31',
      content: `The very ink with which all history is written is merely fluid prejudice.`,
      source: 'Mark Twain — Following the Equator (1897)',
      language: 'en',
      difficulty: 4,
      wordCount: 13,
      charCount: 73,
      tags: ["twain","history","prejudice"],
    },
    {
      id: 'lit-en-32',
      content: `Every book is a quotation; and every house is a quotation out of all forests.`,
      source: 'Ralph Waldo Emerson — Plato (1850)',
      language: 'en',
      difficulty: 4,
      wordCount: 15,
      charCount: 77,
      tags: ["emerson","books","quotation"],
    },
    {
      id: 'lit-en-33',
      content: `I want to write, but more than that, I want to bring out all kinds of things that lie buried in my heart.`,
      source: 'Anne Frank — The Diary of a Young Girl (1947)',
      language: 'en',
      difficulty: 3,
      wordCount: 23,
      charCount: 105,
      tags: ["frank","writing","heart"],
    },
    {
      id: 'lit-en-34',
      content: `The best thing to hold onto in life is each other.`,
      source: 'Audrey Hepburn — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 50,
      tags: ["hepburn","love","connection"],
    },
    {
      id: 'lit-en-35',
      content: `We are all just walking each other home.`,
      source: 'Ram Dass — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 40,
      tags: ["ramdass","compassion","accompaniment"],
    },
    {
      id: 'lit-en-36',
      content: `Darkness cannot drive out darkness; only light can do that.`,
      source: 'Martin Luther King Jr. — Strength to Love (1963)',
      language: 'en',
      difficulty: 2,
      wordCount: 10,
      charCount: 59,
      tags: ["mlk","darkness","light"],
    },
    {
      id: 'lit-en-37',
      content: `He who has a why to live for can bear almost any how.`,
      source: 'Friedrich Nietzsche — Twilight of the Idols (1889)',
      language: 'en',
      difficulty: 3,
      wordCount: 13,
      charCount: 53,
      tags: ["nietzsche","purpose","endurance"],
    },
    {
      id: 'lit-en-38',
      content: `Art is not what you see, but what you make others see.`,
      source: 'Edgar Degas — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 12,
      charCount: 54,
      tags: ["degas","art","perception"],
    },
    {
      id: 'lit-en-39',
      content: `Wherever you go, go with all your heart.`,
      source: 'Confucius — Analects (classical translation)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 40,
      tags: ["confucius","heart","commitment"],
    },
    {
      id: 'lit-en-40',
      content: `The secret to getting ahead is getting started.`,
      source: 'Mark Twain — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 47,
      tags: ["twain","action","beginning"],
    },
    {
      id: 'lit-en-41',
      content: `Each friend represents a world in us, a world possibly not born until they arrive.`,
      source: 'Anaïs Nin — The Diary of Anaïs Nin (1966)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 82,
      tags: ["nin","friendship","world"],
    },
    {
      id: 'lit-en-42',
      content: `I am not strange, I am just not normal.`,
      source: 'Salvador Dalí — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 9,
      charCount: 39,
      tags: ["dali","identity","normalcy"],
    },
    {
      id: 'lit-en-43',
      content: `A person's a person, no matter how small.`,
      source: 'Dr. Seuss — Horton Hears a Who! (1954)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 41,
      tags: ["seuss","person","dignity"],
    },
    {
      id: 'lit-en-44',
      content: `I took the one less traveled by, and that has made all the difference.`,
      source: 'Robert Frost — The Road Not Taken (1916)',
      language: 'en',
      difficulty: 2,
      wordCount: 14,
      charCount: 70,
      tags: ["frost","choice","difference"],
    },
    {
      id: 'lit-en-45',
      content: `There is no greater agony than bearing an untold story inside you.`,
      source: 'Maya Angelou — I Know Why the Caged Bird Sings (1969)',
      language: 'en',
      difficulty: 3,
      wordCount: 12,
      charCount: 66,
      tags: ["angelou","story","expression"],
    },
    {
      id: 'lit-en-46',
      content: `It always seems impossible until it's done.`,
      source: 'Nelson Mandela — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 43,
      tags: ["mandela","possibility","achievement"],
    },
    {
      id: 'lit-en-47',
      content: `In the beginning was the Word, and the Word was with God, and the Word was God.`,
      source: 'John 1:1 — King James Bible (1611)',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 79,
      tags: ["bible","word","creation"],
    },
    {
      id: 'lit-en-48',
      content: `Love is patient, love is kind. It does not envy, it does not boast, it is not proud.`,
      source: '1 Corinthians 13:4 — King James Bible (1611)',
      language: 'en',
      difficulty: 2,
      wordCount: 18,
      charCount: 84,
      tags: ["bible","love","patience"],
    },
    {
      id: 'lit-en-49',
      content: `Life appears to me too short to be spent in nursing animosity or registering wrongs.`,
      source: 'Charlotte Brontë — Jane Eyre (1847)',
      language: 'en',
      difficulty: 4,
      wordCount: 15,
      charCount: 84,
      tags: ["brontë","life","forgiveness"],
    },
    {
      id: 'lit-en-50',
      content: `Second star to the right and straight on till morning.`,
      source: 'J.M. Barrie — Peter Pan (1911)',
      language: 'en',
      difficulty: 1,
      wordCount: 10,
      charCount: 54,
      tags: ["barrie","neverland","direction"],
    },
    {
      id: 'lit-fr-51',
      content: `C'était une de ces jolies et charmantes filles, nées, comme par une erreur du destin, dans une famille d'employés. Elle n'avait pas de dot, pas d'espérances, aucun moyen d'être connue, comprise, aimée, épousée par un homme riche et distingué ; et elle se laissa marier avec un petit commis du ministère de l'instruction publique.`,
      source: 'Guy de Maupassant — La Parure (1884)',
      language: 'fr',
      difficulty: 3,
      wordCount: 54,
      charCount: 329,
      tags: ["maupassant", "naturalisme", "nouvelle"],
    },
    {
      id: 'lit-fr-52',
      content: `Nous étions à l'étude, quand le Proviseur entra, suivi d'un nouveau habillé en bourgeois et d'un garçon de classe qui portait un grand pupitre. Ceux qui dormaient se réveillèrent, et chacun se leva comme surpris dans son travail. Le Proviseur nous fit signe de nous rasseoir ; puis, se tournant vers le maître d'études :`,
      source: 'Gustave Flaubert — Madame Bovary (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 55,
      charCount: 320,
      tags: ["flaubert", "réalisme", "roman"],
    },
    {
      id: 'lit-fr-53',
      content: `Madame Vauquer, née de Conflans, est une vieille femme qui, depuis quarante ans, tient à Paris une pension bourgeoise établie rue Neuve-Sainte-Geneviève, entre le quartier latin et le faubourg Saint-Marcel. Cette pension, connue sous le nom de la maison Vauquer, admet également des hommes et des femmes, des jeunes gens et des vieillards.`,
      source: 'Honoré de Balzac — Le Père Goriot (1835)',
      language: 'fr',
      difficulty: 3,
      wordCount: 53,
      charCount: 339,
      tags: ["balzac", "comédie humaine", "roman"],
    },
    {
      id: 'lit-fr-54',
      content: `Le premier lundi du mois d'avril 1626, le bourg de Meung, où naquit l'auteur du Roman de la Rose, semblait être dans une révolution aussi entière que si les huguenots en fussent venus faire une seconde Rochelle. Plusieurs bourgeois, voyant s'enfuir les femmes le long de la grande rue, entendant les enfants crier sur le seuil des portes, se hâtaient d'endosser la cuirasse, et appuyant leur contenance quelque peu incertaine d'un mousquet ou d'une pertuisane, se dirigeaient vers l'hôtellerie du Franc-Meunier, devant laquelle s'empressait, en grossissant de minute en minute, un groupe compacte, bruyant et plein de curiosité.`,
      source: 'Alexandre Dumas — Les Trois Mousquetaires (1844)',
      language: 'fr',
      difficulty: 4,
      wordCount: 98,
      charCount: 628,
      tags: ["dumas", "aventure", "roman"],
    },
    {
      id: 'lit-fr-55',
      content: `Quoique ce détail ne touche en aucune manière au fond même de ce que nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que pour être exact en tout, d'indiquer ici les bruits et les propos qui avaient couru sur son compte au moment où il était arrivé dans le diocèse. Vrai ou faux, ce qu'on dit des hommes tient souvent autant de place dans leur vie et souvent dans leur destinée que ce qu'ils font. M. Myriel était fils d'un conseiller au parlement d'Aix ; noblesse de robe. On contait que son père, le réservant pour hériter de sa charge, l'avait marié de fort bonne heure, à dix-huit ou vingt ans, suivant un usage assez répandu dans les familles parlementaires.`,
      source: 'Victor Hugo — Les Misérables (1862)',
      language: 'fr',
      difficulty: 5,
      wordCount: 123,
      charCount: 679,
      tags: ["hugo", "romantisme", "roman"],
    },
    {
      id: 'lit-fr-56',
      content: `Dans la plaine rase, sous la nuit sans étoiles, d'une obscurité et d'une épaisseur d'encre, un homme suivait seul la grande route de Marchiennes à Montsou, dix kilomètres de pavé coupant tout droit, à travers les champs de betteraves. Devant lui, il ne voyait même pas le sol noir, et il n'avait la sensation de l'immense horizon plat que par les souffles du vent de mars, des rafales larges comme sur une mer, glacées d'avoir balayé des lieues de marais et de terres nues.`,
      source: 'Émile Zola — Germinal (1885)',
      language: 'fr',
      difficulty: 3,
      wordCount: 84,
      charCount: 473,
      tags: ["zola", "naturalisme", "roman"],
    },
    {
      id: 'lit-en-51',
      content: `A throng of bearded men, in sad-colored garments, and gray, steeple-crowned hats, intermixed with women, some wearing hoods and others bareheaded, was assembled in front of a wooden edifice, the door of which was heavily timbered with oak, and studded with iron spikes.`,
      source: 'Nathaniel Hawthorne — The Scarlet Letter (1850)',
      language: 'en',
      difficulty: 4,
      wordCount: 43,
      charCount: 269,
      tags: ["hawthorne", "american literature", "novel"],
    },
    {
      id: 'lit-en-52',
      content: `Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice 'without pictures or conversations?'`,
      source: 'Lewis Carroll — Alice\'s Adventures in Wonderland (1865)',
      language: 'en',
      difficulty: 2,
      wordCount: 57,
      charCount: 302,
      tags: ["carroll", "fantasy", "novel"],
    },
    {
      id: 'lit-en-53',
      content: `There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further outdoor exercise was now out of the question.`,
      source: 'Charlotte Brontë — Jane Eyre (1847)',
      language: 'en',
      difficulty: 3,
      wordCount: 62,
      charCount: 346,
      tags: ["brontë", "gothic", "novel"],
    },
    {
      id: 'lit-en-54',
      content: `During the whole of a dull, dark, and soundless day in the autumn of the year, when the clouds hung oppressively low in the heavens, I had been passing alone, on horseback, through a singularly dreary tract of country, and at length found myself, as the shades of the evening drew on, within view of the melancholy House of Usher. I know not how it was—but, with the first glimpse of the building, a sense of insufferable gloom pervaded my spirit.`,
      source: 'Edgar Allan Poe — The Fall of the House of Usher (1839)',
      language: 'en',
      difficulty: 4,
      wordCount: 81,
      charCount: 447,
      tags: ["poe", "gothic", "short story"],
    },
    {
      id: 'lit-en-55',
      content: `"Christmas won't be Christmas without any presents," grumbled Jo, lying on the rug. "It's so dreadful to be poor!" sighed Meg, looking down at her old dress. "I don't think it's fair for some girls to have plenty of pretty things, and other girls nothing at all," added little Amy, with an injured sniff. "We've got Father and Mother, and each other," said Beth contentedly from her corner. The four young faces on which the firelight shone brightened at the cheerful words, but darkened again as Jo said sadly, "We haven't got Father, and shall not have him for a long time."`,
      source: 'Louisa May Alcott — Little Women (1868)',
      language: 'en',
      difficulty: 2,
      wordCount: 102,
      charCount: 576,
      tags: ["alcott", "family", "novel"],
    },
    {
      id: 'lit-en-56',
      content: `1801—I have just returned from a visit to my landlord—the solitary neighbour that I shall be troubled with. This is certainly a beautiful country! In all England, I do not believe that I could have fixed on a situation so completely removed from the stir of society. A perfect misanthropist's Heaven—and Mr. Heathcliff and I are such a suitable pair to divide the desolation between us. A capital fellow! He little imagined how my heart warmed towards him when I beheld his black eyes withdraw so suspiciously under their brows, as I rode up.`,
      source: 'Emily Brontë — Wuthering Heights (1847)',
      language: 'en',
      difficulty: 4,
      wordCount: 94,
      charCount: 542,
      tags: ["brontë", "gothic", "novel"],
    },
    {
      id: 'lit-fr-57',
      content: `L'année 1866 fut marquée par un événement bizarre, un phénomène inexpliqué et inexplicable que personne n'a sans doute oublié.`,
      source: 'Jules Verne — Vingt mille lieues sous les mers (1870)',
      language: 'fr',
      difficulty: 2,
      wordCount: 19,
      charCount: 126,
      tags: ["verne", "aventure", "chiffre"],
    },
    {
      id: 'lit-fr-58',
      content: `Le 24 février 1815, la vigie de Notre-Dame de la Garde signala le trois-mâts le Pharaon, venant de Smyrne, Trieste et Naples.`,
      source: 'Alexandre Dumas — Le Comte de Monte-Cristo (1844)',
      language: 'fr',
      difficulty: 2,
      wordCount: 22,
      charCount: 125,
      tags: ["dumas", "aventure", "chiffre"],
    },
    {
      id: 'lit-en-57',
      content: `Exclusive of the Lake basin and of 300,000 square miles in Texas and New Mexico, which in many aspects form a part of it, this basin contains about 1,250,000 square miles.`,
      source: 'Mark Twain — Life on the Mississippi (1883)',
      language: 'en',
      difficulty: 3,
      wordCount: 31,
      charCount: 171,
      tags: ["twain", "nonfiction", "chiffre"],
    },
    {
      id: 'lit-en-58',
      content: `In the year 1820 the ship Essex, Captain Pollard, of Nantucket, was cruising in the Pacific Ocean. One day she saw spouts, lowered her boats, and gave chase to a shoal of sperm whales.`,
      source: 'Herman Melville — Moby-Dick (1851)',
      language: 'en',
      difficulty: 3,
      wordCount: 34,
      charCount: 184,
      tags: ["melville", "adventure", "chiffre"],
    }
  ],
};
