/**
 * Collection Littérature : textes du domaine public (auteur mort > 70 ans).
 * Sources : Project Gutenberg, Wikisource.
 * Spec : docs/specs/06-content.md
 */

import type { CollectionConfig } from '@typewav/types';

export const litteratureCollection: CollectionConfig = {
  id: 'litterature',
  name: 'Littérature',
  nameEn: 'Literature',
  description: 'Grands textes de la littérature mondiale : domaine public.',
  language: 'multi',
  recommendedTheme: 'noir',
  isPremium: false,
  texts: [
    // ── Français ──────────────────────────────────────────────────────────────
    {
      id: 'lit-fr-01',
      content: `Il était une fois une petite fille de village, la plus jolie qu'on eût su voir ; sa mère en était folle, et sa mère-grand plus folle encore.`,
      source: 'Charles Perrault, Le Petit Chaperon rouge (1697)',
      language: 'fr',
      difficulty: 2,
      wordCount: 28,
      charCount: 140,
      tags: ["classique", "français", "conte"],
    },
    {
      id: 'lit-fr-02',
      content: `Longtemps, je me suis couché de bonne heure. Parfois, à peine ma bougie éteinte, mes yeux se fermaient si vite que je n'avais pas le temps de me dire : «Je m'endors.»`,
      source: 'Marcel Proust, Du côté de chez Swann (1913)',
      language: 'fr',
      difficulty: 5,
      wordCount: 32,
      charCount: 166,
      tags: ["classique","français","roman"],
    },
    {
      id: 'lit-fr-03',
      content: `Le 15 mai 1796, le général Bonaparte fit son entrée dans Milan à la tête de cette jeune armée qui venait de passer le pont de Lodi.`,
      source: 'Stendhal, La Chartreuse de Parme (1839)',
      language: 'fr',
      difficulty: 3,
      wordCount: 27,
      charCount: 131,
      tags: ["classique", "français", "roman"],
    },
    {
      id: 'lit-fr-04',
      content: `Toutes les familles heureuses se ressemblent ; chaque famille malheureuse est malheureuse à sa façon.`,
      source: 'Léon Tolstoï, Anna Karénine (1877)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 101,
      tags: ["classique","russe","roman"],
    },
    {
      id: 'lit-fr-05',
      content: `La nuit était sombre et orageuse. Raskolnikov se leva et sortit de sa mansarde.`,
      source: 'Fiodor Dostoïevski, Crime et Châtiment (1866)',
      language: 'fr',
      difficulty: 1,
      wordCount: 14,
      charCount: 79,
      tags: ["classique","russe","roman"],
    },
    {
      id: 'lit-fr-06',
      content: `Il était une fois un roi et une reine qui étaient si fâchés de n'avoir point d'enfants, si fâchés que l'on ne saurait dire.`,
      source: 'Charles Perrault, La Belle au bois dormant (1697)',
      language: 'fr',
      difficulty: 1,
      wordCount: 24,
      charCount: 123,
      tags: ["conte", "classique", "merveilleux"],
    },
    {
      id: 'lit-fr-07',
      content: `C'était le meilleur des temps, c'était le pire des temps, c'était l'âge de la sagesse, c'était l'âge de la folie.`,
      source: 'Charles Dickens, Le Conte de deux villes (1859)',
      language: 'fr',
      difficulty: 3,
      wordCount: 20,
      charCount: 113,
      tags: ["classique","anglais","historique"],
    },
    {
      id: 'lit-fr-08',
      content: `En l'année 1872, la maison portant le numéro 7 de Saville-row était habitée par Phileas Fogg, l'un des membres les plus singuliers du Reform-Club de Londres.`,
      source: 'Jules Verne, Le Tour du monde en quatre-vingts jours (1873)',
      language: 'fr',
      difficulty: 3,
      wordCount: 26,
      charCount: 157,
      tags: ["aventure", "classique", "roman"],
    },
    {
      id: 'lit-fr-09',
      content: `J'ai examiné les hommes, et j'ai cru que, dans cette infinie diversité de lois et de mœurs, ils n'étaient pas uniquement conduits par leurs fantaisies.`,
      source: 'Montesquieu, De l\'esprit des lois (1748)',
      language: 'fr',
      difficulty: 5,
      wordCount: 25,
      charCount: 151,
      tags: ["montesquieu", "lois", "raison"],
    },
    {
      id: 'lit-fr-10',
      content: `La vie est courte et l'art est long, l'occasion fugitive, l'expérience trompeuse, le jugement difficile.`,
      source: 'Hippocrate, Aphorismes (IVe siècle av. J.-C.)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 104,
      tags: ["philosophie","antiquité"],
    },
    {
      id: 'lit-fr-11',
      content: `Il est des parfums frais comme des chairs d'enfants, doux comme les hautbois, verts comme les prairies.`,
      source: 'Charles Baudelaire, Correspondances (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 103,
      tags: ["baudelaire","synesthésie","poème"],
    },
    {
      id: 'lit-fr-12',
      content: `Jean Valjean fut traduit devant les tribunaux alors qu'il avait volé un pain pour nourrir sa famille affamée.`,
      source: 'Victor Hugo, Les Misérables (1862)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 109,
      tags: ["hugo","justice","misère"],
    },
    {
      id: 'lit-fr-13',
      content: `La vie est une longue préparation à quelque chose qui ne vient jamais peut-être.`,
      source: 'William Butler Yeats, trad.',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 80,
      tags: ["yeats","vie","attente"],
    },
    {
      id: 'lit-fr-14',
      content: `Nous avons tous assez de force pour supporter les maux d'autrui.`,
      source: 'La Rochefoucauld, Maximes (1678)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 64,
      tags: ["moraliste", "maxime", "lucidité"],
    },
    {
      id: 'lit-fr-15',
      content: `Mon Dieu, mon Dieu ! Pourquoi m'avez-vous abandonné ? Les paroles se perdent dans le désert.`,
      source: 'Gustave Flaubert, La Tentation de saint Antoine (1874)',
      language: 'fr',
      difficulty: 4,
      wordCount: 16,
      charCount: 92,
      tags: ["flaubert","abandon","religion"],
    },
    {
      id: 'lit-fr-16',
      content: `Il avait rêvé d'une gloire littéraire et finissait clerc de notaire dans une ville de province.`,
      source: 'Stendhal, Le Rouge et le Noir (1830)',
      language: 'fr',
      difficulty: 3,
      wordCount: 16,
      charCount: 95,
      tags: ["stendhal","ambition","province"],
    },
    {
      id: 'lit-fr-17',
      content: `La mer, la mer, toujours recommencée ! Ô récompense après une pensée qu'un long regard sur le calme des dieux !`,
      source: 'Paul Valéry, Le Cimetière marin (1920)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 111,
      tags: ["valéry","mer","méditation"],
    },
    {
      id: 'lit-fr-18',
      content: `Ai-je été nourri par ma mère ? Est-ce une paysanne qui m'a donné son lait ? Je n'en sais rien.`,
      source: 'Jules Vallès, L\'Enfant (1879)',
      language: 'fr',
      difficulty: 2,
      wordCount: 20,
      charCount: 94,
      tags: ["enfance", "souvenir", "français"],
    },
    {
      id: 'lit-fr-19',
      content: `L'amour est aveugle ; voilà pourquoi il ne voit pas les imperfections de ceux que nous aimons.`,
      source: 'Molière, L\'École des femmes (1662)',
      language: 'fr',
      difficulty: 3,
      wordCount: 17,
      charCount: 94,
      tags: ["molière","amour","aveuglement"],
    },
    {
      id: 'lit-fr-20',
      content: `Paris, cette immense et ardente capitale, dressait ses tours et ses toits dans le ciel gris de novembre.`,
      source: 'Guy de Maupassant, Bel-Ami (1885)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 104,
      tags: ["maupassant","paris","automne"],
    },
    {
      id: 'lit-fr-21',
      content: `La nature est un temple où de vivants piliers laissent parfois sortir de confuses paroles.`,
      source: 'Charles Baudelaire, Correspondances (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 15,
      charCount: 90,
      tags: ["baudelaire","nature","temple"],
    },
    {
      id: 'lit-fr-22',
      content: `La femme naît libre et demeure égale à l'homme en droits.`,
      source: 'Olympe de Gouges, Déclaration des droits de la femme (1791)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 57,
      tags: ["droits", "égalité", "lumières"],
    },
    {
      id: 'lit-fr-23',
      content: `Le silence éternel de ces espaces infinis m'effraie.`,
      source: 'Blaise Pascal, Pensées (1670)',
      language: 'fr',
      difficulty: 3,
      wordCount: 8,
      charCount: 52,
      tags: ["pascal", "infini", "vertige"],
    },
    {
      id: 'lit-fr-24',
      content: `Deux choses me remplissent d'admiration : le ciel étoilé au-dessus de moi et la loi morale en moi.`,
      source: 'Emmanuel Kant, Critique de la raison pratique (1788)',
      language: 'fr',
      difficulty: 4,
      wordCount: 18,
      charCount: 98,
      tags: ["kant","admiration","éthique"],
    },
    {
      id: 'lit-fr-25',
      content: `Je sortais d'un théâtre où tous les soirs je paraissais aux avant-scènes en grande tenue de soupirant.`,
      source: 'Gérard de Nerval, Sylvie (1853)',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 102,
      tags: ["nerval", "mémoire", "nouvelle"],
    },
    {
      id: 'lit-fr-26',
      content: `Le beau est ce qui plaît à la raison et aux yeux tout ensemble.`,
      source: 'Joseph Joubert, Pensées (1838)',
      language: 'fr',
      difficulty: 3,
      wordCount: 14,
      charCount: 63,
      tags: ["beauté", "raison", "moraliste"],
    },
    {
      id: 'lit-fr-27',
      content: `Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.`,
      source: 'Sénèque, Lettres à Lucilius (traduction classique)',
      language: 'fr',
      difficulty: 2,
      wordCount: 22,
      charCount: 130,
      tags: ["stoïcisme", "audace", "antiquité"],
    },
    {
      id: 'lit-fr-28',
      content: `Tout est pour le mieux dans le meilleur des mondes possibles.`,
      source: 'Voltaire, Candide (1759)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 61,
      tags: ["voltaire","candide","optimisme"],
    },
    {
      id: 'lit-fr-29',
      content: `Il faut cultiver notre jardin.`,
      source: 'Voltaire, Candide (1759)',
      language: 'fr',
      difficulty: 1,
      wordCount: 5,
      charCount: 30,
      tags: ["voltaire","jardin","pragmatisme"],
    },
    {
      id: 'lit-fr-30',
      content: `La douleur est une leçon. La douleur bien portée apprend la mesure des choses.`,
      source: 'Léon Bloy, Journal (1892)',
      language: 'fr',
      difficulty: 3,
      wordCount: 14,
      charCount: 78,
      tags: ["bloy","douleur","mesure"],
    },
    {
      id: 'lit-fr-31',
      content: `La vérité est en marche et rien ne l'arrêtera.`,
      source: 'Émile Zola, J\'accuse (1898)',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 46,
      tags: ["zola","vérité","dreyfus"],
    },
    {
      id: 'lit-fr-32',
      content: `Ce que l'on conçoit bien s'énonce clairement, et les mots pour le dire arrivent aisément.`,
      source: 'Nicolas Boileau, L\'Art poétique (1674)',
      language: 'fr',
      difficulty: 4,
      wordCount: 15,
      charCount: 89,
      tags: ["boileau", "écriture", "clarté"],
    },
    {
      id: 'lit-fr-33',
      content: `Germinal. Le mot sonnait comme un coup de feu. L'aube levait sur les mines.`,
      source: 'Émile Zola, Germinal (1885)',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 75,
      tags: ["zola","germinal","mine"],
    },
    {
      id: 'lit-fr-34',
      content: `Monsieur Moreau avait passé sa vie à travailler pour une retraite qu'il n'eut jamais le temps de prendre.`,
      source: 'Gustave Flaubert, L\'Éducation sentimentale (1869)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 105,
      tags: ["flaubert","travail","retraite"],
    },
    {
      id: 'lit-fr-35',
      content: `Sur le versant d'une de ces collines pelées qui accidentent le paysage landais s'élevait, sous le règne de Louis XIII, un de ces castels comme il s'en trouve tant en Gascogne.`,
      source: 'Théophile Gautier, Le Capitaine Fracasse (1863)',
      language: 'fr',
      difficulty: 3,
      wordCount: 31,
      charCount: 175,
      tags: ["gautier", "aventure", "roman"],
    },
    {
      id: 'lit-fr-36',
      content: `Ce que nous savons est une goutte d'eau, ce que nous ignorons est un océan.`,
      source: 'Isaac Newton, attribué',
      language: 'fr',
      difficulty: 2,
      wordCount: 15,
      charCount: 75,
      tags: ["newton","savoir","ignorance"],
    },
    {
      id: 'lit-fr-37',
      content: `La lecture est à l'esprit ce que l'exercice est au corps.`,
      source: 'Joseph Addison, The Spectator (1711, trad.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 57,
      tags: ["addison","lecture","esprit"],
    },
    {
      id: 'lit-fr-38',
      content: `Il n'est pire misère que d'avoir été heureux autrefois.`,
      source: 'Dante Alighieri, La Divine Comédie (XIVe siècle, trad.)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 55,
      tags: ["dante","bonheur","souvenir"],
    },
    {
      id: 'lit-fr-39',
      content: `Éduquer c'est allumer un feu, non remplir un vase.`,
      source: 'Michel de Montaigne, Essais (1580)',
      language: 'fr',
      difficulty: 1,
      wordCount: 9,
      charCount: 50,
      tags: ["montaigne","éducation","feu"],
    },
    {
      id: 'lit-fr-40',
      content: `Jamais un grand homme ne fut puni pour ses crimes. Il fut seulement remplacé.`,
      source: 'Honoré de Balzac, attribué',
      language: 'fr',
      difficulty: 3,
      wordCount: 14,
      charCount: 77,
      tags: ["balzac","pouvoir","impunité"],
    },
    {
      id: 'lit-fr-41',
      content: `Apprendre sans réfléchir est vain ; réfléchir sans apprendre est dangereux.`,
      source: 'Confucius, Entretiens (traduction classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 75,
      tags: ["confucius", "étude", "sagesse"],
    },
    {
      id: 'lit-fr-42',
      content: `Les livres sont les testaments que les génies lèguent à l'humanité.`,
      source: 'Jules Renard, Journal (1890)',
      language: 'fr',
      difficulty: 2,
      wordCount: 11,
      charCount: 67,
      tags: ["renard","livres","génies"],
    },
    {
      id: 'lit-fr-43',
      content: `La lecture de tous les bons livres est comme une conversation avec les plus honnêtes gens des siècles passés.`,
      source: 'René Descartes, Discours de la méthode (1637)',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 109,
      tags: ["descartes", "lecture", "livre"],
    },
    {
      id: 'lit-fr-44',
      content: `On ne peut pas plaire à tout le monde et à son père.`,
      source: 'La Fontaine, Le Meunier, son fils et l\'âne (1668)',
      language: 'fr',
      difficulty: 1,
      wordCount: 13,
      charCount: 52,
      tags: ["la fontaine","fable","sagesse"],
    },
    {
      id: 'lit-fr-45',
      content: `L'histoire n'est que le tableau des crimes et des malheurs.`,
      source: 'Voltaire, L\'Ingénu (1767)',
      language: 'fr',
      difficulty: 2,
      wordCount: 10,
      charCount: 59,
      tags: ["voltaire", "histoire", "lucidité"],
    },
    {
      id: 'lit-fr-46',
      content: `Si tu veux aller loin, ménage ta monture.`,
      source: 'Proverbe français (XVIIe siècle)',
      language: 'fr',
      difficulty: 1,
      wordCount: 8,
      charCount: 41,
      tags: ["proverbe","prudence","endurance"],
    },
    {
      id: 'lit-fr-47',
      content: `Le silence est une réponse assez claire pour celui qui sait interpréter.`,
      source: 'Honoré de Balzac, attribué',
      language: 'fr',
      difficulty: 3,
      wordCount: 12,
      charCount: 72,
      tags: ["balzac","silence","interprétation"],
    },
    {
      id: 'lit-fr-48',
      content: `L'homme est la mesure de toutes choses.`,
      source: 'Protagoras, fragment (Ve siècle av. J.-C., trad.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 39,
      tags: ["protagoras","humanisme","mesure"],
    },
    {
      id: 'lit-fr-49',
      content: `La générosité consiste à donner plus qu'on ne peut et l'orgueil à recevoir moins qu'on ne peut.`,
      source: 'Khalil Gibran, Le Prophète (1923)',
      language: 'fr',
      difficulty: 4,
      wordCount: 17,
      charCount: 95,
      tags: ["gibran","générosité","orgueil"],
    },
    {
      id: 'lit-fr-50',
      content: `Mieux vaut être seul que mal accompagné.`,
      source: 'Molière, attribué',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 40,
      tags: ["molière","solitude","compagnie"],
    },
    // ── English ───────────────────────────────────────────────────────────────
    {
      id: 'lit-en-01',
      content: `Call me Ishmael. Some years ago — never mind how long precisely — having little money in my purse, I thought I would sail about a little and see the watery part of the world.`,
      source: 'Herman Melville, Moby-Dick (1851)',
      language: 'en',
      difficulty: 5,
      wordCount: 35,
      charCount: 174,
      tags: ["classic","american","novel"],
    },
    {
      id: 'lit-en-02',
      content: `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.`,
      source: 'Charles Dickens, A Tale of Two Cities (1859)',
      language: 'en',
      difficulty: 3,
      wordCount: 24,
      charCount: 109,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-03',
      content: `Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.`,
      source: 'Charles Dickens, David Copperfield (1850)',
      language: 'en',
      difficulty: 3,
      wordCount: 27,
      charCount: 132,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-04',
      content: `Happy families are all alike; every unhappy family is unhappy in its own way.`,
      source: 'Leo Tolstoy, Anna Karenina (1877)',
      language: 'en',
      difficulty: 1,
      wordCount: 14,
      charCount: 77,
      tags: ["classic","russian","novel"],
    },
    {
      id: 'lit-en-05',
      content: `It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.`,
      source: 'Jane Austen, Pride and Prejudice (1813)',
      language: 'en',
      difficulty: 3,
      wordCount: 23,
      charCount: 117,
      tags: ["classic","english","novel"],
    },
    {
      id: 'lit-en-06',
      content: `So we beat on, boats against the current, borne back ceaselessly into the past.`,
      source: 'F. Scott Fitzgerald, The Great Gatsby (1925)',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 79,
      tags: ["classic","american","novel"],
    },
    {
      id: 'lit-en-07',
      content: `In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep.`,
      source: 'Genesis 1:1, King James Bible (1611)',
      language: 'en',
      difficulty: 1,
      wordCount: 25,
      charCount: 136,
      tags: ["classic","religious","poetry"],
    },
    {
      id: 'lit-en-08',
      content: `To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune.`,
      source: 'William Shakespeare, Hamlet (1603)',
      language: 'en',
      difficulty: 5,
      wordCount: 25,
      charCount: 129,
      tags: ["classic","english","drama"],
    },
    {
      id: 'lit-en-09',
      content: `All animals are equal, but some animals are more equal than others.`,
      source: 'George Orwell, Animal Farm (1945)',
      language: 'en',
      difficulty: 1,
      wordCount: 12,
      charCount: 67,
      tags: ["classic","english","satire"],
    },
    {
      id: 'lit-en-10',
      content: `It was a bright cold day in April, and the clocks were striking thirteen.`,
      source: 'George Orwell, Nineteen Eighty-Four (1949)',
      language: 'en',
      difficulty: 1,
      wordCount: 14,
      charCount: 73,
      tags: ["classic","english","dystopia"],
    },
    {
      id: 'lit-en-11',
      content: `It is a far, far better thing that I do, than I have ever done before.`,
      source: 'Charles Dickens, A Tale of Two Cities (1859)',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 70,
      tags: ["dickens","sacrifice","nobility"],
    },
    {
      id: 'lit-en-12',
      content: `I am not afraid of storms, for I am learning how to sail my ship.`,
      source: 'Louisa May Alcott, Little Women (1868)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 65,
      tags: ["alcott","courage","growth"],
    },
    {
      id: 'lit-en-13',
      content: `If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.`,
      source: 'Henry David Thoreau, Walden (1854)',
      language: 'en',
      difficulty: 2,
      wordCount: 20,
      charCount: 115,
      tags: ["thoreau", "dreams", "living"],
    },
    {
      id: 'lit-en-14',
      content: `Afoot and light-hearted I take to the open road, healthy, free, the world before me.`,
      source: 'Walt Whitman, Song of the Open Road (1856)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 84,
      tags: ["whitman", "road", "freedom"],
    },
    {
      id: 'lit-en-15',
      content: `Whatever our souls are made of, his and mine are the same.`,
      source: 'Emily Brontë, Wuthering Heights (1847)',
      language: 'en',
      difficulty: 1,
      wordCount: 12,
      charCount: 58,
      tags: ["brontë", "love", "soul"],
    },
    {
      id: 'lit-en-16',
      content: `If we had a keen vision of all ordinary human life, it would be like hearing the grass grow and the squirrel's heart beat.`,
      source: 'George Eliot, Middlemarch (1871)',
      language: 'en',
      difficulty: 4,
      wordCount: 24,
      charCount: 122,
      tags: ["eliot", "empathy", "perception"],
    },
    {
      id: 'lit-en-17',
      content: `Our strength grows out of our weakness.`,
      source: 'Ralph Waldo Emerson, Compensation (1841)',
      language: 'en',
      difficulty: 2,
      wordCount: 7,
      charCount: 39,
      tags: ["emerson", "resilience", "strength"],
    },
    {
      id: 'lit-en-18',
      content: `I travel not to go anywhere, but to go. The great affair is to move.`,
      source: 'Robert Louis Stevenson, Travels with a Donkey (1879)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 68,
      tags: ["stevenson", "wandering", "purpose"],
    },
    {
      id: 'lit-en-19',
      content: `Nothing can bring you peace but yourself. Nothing can bring you peace but the triumph of principles.`,
      source: 'Ralph Waldo Emerson, Self-Reliance (1841)',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 100,
      tags: ["emerson", "peace", "character"],
    },
    {
      id: 'lit-en-20',
      content: `Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.`,
      source: 'Francis Bacon, Of Studies (1625)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 92,
      tags: ["bacon", "reading", "books"],
    },
    {
      id: 'lit-en-21',
      content: `To me every hour of the light and dark is a miracle, every cubic inch of space is a miracle.`,
      source: 'Walt Whitman, Miracles (1856)',
      language: 'en',
      difficulty: 3,
      wordCount: 20,
      charCount: 92,
      tags: ["whitman", "miracle", "wonder"],
    },
    {
      id: 'lit-en-22',
      content: `Nothing is so painful to the human mind as a great and sudden change.`,
      source: 'Mary Shelley, Frankenstein (1818)',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 69,
      tags: ["shelley", "change", "mind"],
    },
    {
      id: 'lit-en-23',
      content: `The sea is everything. It covers seven-tenths of the terrestrial globe.`,
      source: 'Jules Verne, Twenty Thousand Leagues Under the Sea (1870)',
      language: 'en',
      difficulty: 2,
      wordCount: 11,
      charCount: 71,
      tags: ["verne","sea","earth"],
    },
    {
      id: 'lit-en-24',
      content: `Adventure is worthwhile in itself.`,
      source: 'Amelia Earhart, attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 5,
      charCount: 34,
      tags: ["earhart","adventure","worth"],
    },
    {
      id: 'lit-en-25',
      content: `Do you not see how necessary a world of pains and troubles is to school an intelligence and make it a soul?`,
      source: 'John Keats, Letter to George and Georgiana Keats (1819)',
      language: 'en',
      difficulty: 4,
      wordCount: 22,
      charCount: 107,
      tags: ["keats", "suffering", "soul"],
    },
    {
      id: 'lit-en-26',
      content: `The best-laid schemes of mice and men go often awry.`,
      source: 'Robert Burns, To a Mouse (1785)',
      language: 'en',
      difficulty: 2,
      wordCount: 10,
      charCount: 52,
      tags: ["burns", "plans", "chance"],
    },
    {
      id: 'lit-en-27',
      content: `Whoso would be a man must be a nonconformist.`,
      source: 'Ralph Waldo Emerson, Self-Reliance (1841)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 45,
      tags: ["emerson", "courage", "thinking"],
    },
    {
      id: 'lit-en-28',
      content: `That is part of the beauty of all literature. You discover that your longings are universal longings.`,
      source: 'F. Scott Fitzgerald, attributed',
      language: 'en',
      difficulty: 4,
      wordCount: 17,
      charCount: 101,
      tags: ["fitzgerald","literature","longing"],
    },
    {
      id: 'lit-en-29',
      content: `Do not wait to strike till the iron is hot, but make it hot by striking.`,
      source: 'W.B. Yeats, attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 72,
      tags: ["yeats","action","opportunity"],
    },
    {
      id: 'lit-en-30',
      content: `The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.`,
      source: 'Jane Austen, Northanger Abbey (1817)',
      language: 'en',
      difficulty: 2,
      wordCount: 19,
      charCount: 102,
      tags: ["austen", "reading", "wit"],
    },
    {
      id: 'lit-en-31',
      content: `The very ink with which all history is written is merely fluid prejudice.`,
      source: 'Mark Twain, Following the Equator (1897)',
      language: 'en',
      difficulty: 4,
      wordCount: 13,
      charCount: 73,
      tags: ["twain","history","prejudice"],
    },
    {
      id: 'lit-en-32',
      content: `Every book is a quotation; and every house is a quotation out of all forests.`,
      source: 'Ralph Waldo Emerson, Plato (1850)',
      language: 'en',
      difficulty: 4,
      wordCount: 15,
      charCount: 77,
      tags: ["emerson","books","quotation"],
    },
    {
      id: 'lit-en-33',
      content: `I dwell in Possibility, a fairer House than Prose, more numerous of Windows, superior for Doors.`,
      source: 'Emily Dickinson, I dwell in Possibility (c.1862)',
      language: 'en',
      difficulty: 3,
      wordCount: 16,
      charCount: 96,
      tags: ["dickinson", "writing", "imagination"],
    },
    {
      id: 'lit-en-34',
      content: `To love is the great amulet that makes this world a garden.`,
      source: 'Robert Louis Stevenson, Virginibus Puerisque (1881)',
      language: 'en',
      difficulty: 2,
      wordCount: 12,
      charCount: 59,
      tags: ["stevenson", "love", "connection"],
    },
    {
      id: 'lit-en-35',
      content: `What do we live for, if it is not to make life less difficult to each other?`,
      source: 'George Eliot, Middlemarch (1871)',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 76,
      tags: ["eliot", "compassion", "purpose"],
    },
    {
      id: 'lit-en-36',
      content: `Long is the way and hard, that out of hell leads up to light.`,
      source: 'John Milton, Paradise Lost (1667)',
      language: 'en',
      difficulty: 3,
      wordCount: 14,
      charCount: 61,
      tags: ["milton", "darkness", "light"],
    },
    {
      id: 'lit-en-37',
      content: `He who has a why to live for can bear almost any how.`,
      source: 'Friedrich Nietzsche, Twilight of the Idols (1889)',
      language: 'en',
      difficulty: 3,
      wordCount: 13,
      charCount: 53,
      tags: ["nietzsche","purpose","endurance"],
    },
    {
      id: 'lit-en-38',
      content: `Art is not what you see, but what you make others see.`,
      source: 'Edgar Degas, attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 12,
      charCount: 54,
      tags: ["degas","art","perception"],
    },
    {
      id: 'lit-en-39',
      content: `Wherever you go, go with all your heart.`,
      source: 'Confucius, Analects (classical translation)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 40,
      tags: ["confucius","heart","commitment"],
    },
    {
      id: 'lit-en-40',
      content: `The secret to getting ahead is getting started.`,
      source: 'Mark Twain, attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 47,
      tags: ["twain","action","beginning"],
    },
    {
      id: 'lit-en-41',
      content: `A friend may well be reckoned the masterpiece of nature.`,
      source: 'Ralph Waldo Emerson, Friendship (1841)',
      language: 'en',
      difficulty: 2,
      wordCount: 10,
      charCount: 56,
      tags: ["emerson", "friendship", "nature"],
    },
    {
      id: 'lit-en-42',
      content: `To love oneself is the beginning of a lifelong romance.`,
      source: 'Oscar Wilde, An Ideal Husband (1895)',
      language: 'en',
      difficulty: 1,
      wordCount: 10,
      charCount: 55,
      tags: ["wilde", "identity", "self"],
    },
    {
      id: 'lit-en-43',
      content: `No one is useless in this world who lightens the burden of another.`,
      source: 'Charles Dickens, Our Mutual Friend (1865)',
      language: 'en',
      difficulty: 2,
      wordCount: 13,
      charCount: 67,
      tags: ["dickens", "kindness", "worth"],
    },
    {
      id: 'lit-en-44',
      content: `There is a tide in the affairs of men which, taken at the flood, leads on to fortune.`,
      source: 'William Shakespeare, Julius Caesar (1599)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 85,
      tags: ["shakespeare", "choice", "opportunity"],
    },
    {
      id: 'lit-en-45',
      content: `No man, for any considerable period, can wear one face to himself and another to the multitude, without finally getting bewildered as to which may be the true.`,
      source: 'Nathaniel Hawthorne, The Scarlet Letter (1850)',
      language: 'en',
      difficulty: 4,
      wordCount: 28,
      charCount: 159,
      tags: ["hawthorne", "truth", "self"],
    },
    {
      id: 'lit-en-46',
      content: `It always seems impossible until it's done.`,
      source: 'Nelson Mandela, attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 43,
      tags: ["mandela","possibility","achievement"],
    },
    {
      id: 'lit-en-47',
      content: `In the beginning was the Word, and the Word was with God, and the Word was God.`,
      source: 'John 1:1, King James Bible (1611)',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 79,
      tags: ["bible","word","creation"],
    },
    {
      id: 'lit-en-48',
      content: `Love is patient, love is kind. It does not envy, it does not boast, it is not proud.`,
      source: '1 Corinthians 13:4, King James Bible (1611)',
      language: 'en',
      difficulty: 2,
      wordCount: 18,
      charCount: 84,
      tags: ["bible","love","patience"],
    },
    {
      id: 'lit-en-49',
      content: `Life appears to me too short to be spent in nursing animosity or registering wrongs.`,
      source: 'Charlotte Brontë, Jane Eyre (1847)',
      language: 'en',
      difficulty: 4,
      wordCount: 15,
      charCount: 84,
      tags: ["brontë","life","forgiveness"],
    },
    {
      id: 'lit-en-50',
      content: `Second star to the right and straight on till morning.`,
      source: 'J.M. Barrie, Peter Pan (1911)',
      language: 'en',
      difficulty: 1,
      wordCount: 10,
      charCount: 54,
      tags: ["barrie","neverland","direction"],
    },
    {
      id: 'lit-fr-51',
      content: `C'était une de ces jolies et charmantes filles, nées, comme par une erreur du destin, dans une famille d'employés. Elle n'avait pas de dot, pas d'espérances, aucun moyen d'être connue, comprise, aimée, épousée par un homme riche et distingué ; et elle se laissa marier avec un petit commis du ministère de l'instruction publique.`,
      source: 'Guy de Maupassant, La Parure (1884)',
      language: 'fr',
      difficulty: 3,
      wordCount: 54,
      charCount: 329,
      tags: ["maupassant", "naturalisme", "nouvelle"],
    },
    {
      id: 'lit-fr-52',
      content: `Nous étions à l'étude, quand le Proviseur entra, suivi d'un nouveau habillé en bourgeois et d'un garçon de classe qui portait un grand pupitre. Ceux qui dormaient se réveillèrent, et chacun se leva comme surpris dans son travail. Le Proviseur nous fit signe de nous rasseoir ; puis, se tournant vers le maître d'études :`,
      source: 'Gustave Flaubert, Madame Bovary (1857)',
      language: 'fr',
      difficulty: 4,
      wordCount: 55,
      charCount: 320,
      tags: ["flaubert", "réalisme", "roman"],
    },
    {
      id: 'lit-fr-53',
      content: `Madame Vauquer, née de Conflans, est une vieille femme qui, depuis quarante ans, tient à Paris une pension bourgeoise établie rue Neuve-Sainte-Geneviève, entre le quartier latin et le faubourg Saint-Marcel. Cette pension, connue sous le nom de la maison Vauquer, admet également des hommes et des femmes, des jeunes gens et des vieillards.`,
      source: 'Honoré de Balzac, Le Père Goriot (1835)',
      language: 'fr',
      difficulty: 3,
      wordCount: 53,
      charCount: 339,
      tags: ["balzac", "comédie humaine", "roman"],
    },
    {
      id: 'lit-fr-54',
      content: `Le premier lundi du mois d'avril 1626, le bourg de Meung, où naquit l'auteur du Roman de la Rose, semblait être dans une révolution aussi entière que si les huguenots en fussent venus faire une seconde Rochelle. Plusieurs bourgeois, voyant s'enfuir les femmes le long de la grande rue, entendant les enfants crier sur le seuil des portes, se hâtaient d'endosser la cuirasse, et appuyant leur contenance quelque peu incertaine d'un mousquet ou d'une pertuisane, se dirigeaient vers l'hôtellerie du Franc-Meunier, devant laquelle s'empressait, en grossissant de minute en minute, un groupe compacte, bruyant et plein de curiosité.`,
      source: 'Alexandre Dumas, Les Trois Mousquetaires (1844)',
      language: 'fr',
      difficulty: 4,
      wordCount: 98,
      charCount: 628,
      tags: ["dumas", "aventure", "roman"],
    },
    {
      id: 'lit-fr-55',
      content: `Quoique ce détail ne touche en aucune manière au fond même de ce que nous avons à raconter, il n'est peut-être pas inutile, ne fût-ce que pour être exact en tout, d'indiquer ici les bruits et les propos qui avaient couru sur son compte au moment où il était arrivé dans le diocèse. Vrai ou faux, ce qu'on dit des hommes tient souvent autant de place dans leur vie et souvent dans leur destinée que ce qu'ils font. M. Myriel était fils d'un conseiller au parlement d'Aix ; noblesse de robe. On contait que son père, le réservant pour hériter de sa charge, l'avait marié de fort bonne heure, à dix-huit ou vingt ans, suivant un usage assez répandu dans les familles parlementaires.`,
      source: 'Victor Hugo, Les Misérables (1862)',
      language: 'fr',
      difficulty: 5,
      wordCount: 123,
      charCount: 679,
      tags: ["hugo", "romantisme", "roman"],
    },
    {
      id: 'lit-fr-56',
      content: `Dans la plaine rase, sous la nuit sans étoiles, d'une obscurité et d'une épaisseur d'encre, un homme suivait seul la grande route de Marchiennes à Montsou, dix kilomètres de pavé coupant tout droit, à travers les champs de betteraves. Devant lui, il ne voyait même pas le sol noir, et il n'avait la sensation de l'immense horizon plat que par les souffles du vent de mars, des rafales larges comme sur une mer, glacées d'avoir balayé des lieues de marais et de terres nues.`,
      source: 'Émile Zola, Germinal (1885)',
      language: 'fr',
      difficulty: 3,
      wordCount: 84,
      charCount: 473,
      tags: ["zola", "naturalisme", "roman"],
    },
    {
      id: 'lit-en-51',
      content: `A throng of bearded men, in sad-colored garments, and gray, steeple-crowned hats, intermixed with women, some wearing hoods and others bareheaded, was assembled in front of a wooden edifice, the door of which was heavily timbered with oak, and studded with iron spikes.`,
      source: 'Nathaniel Hawthorne, The Scarlet Letter (1850)',
      language: 'en',
      difficulty: 4,
      wordCount: 43,
      charCount: 269,
      tags: ["hawthorne", "american literature", "novel"],
    },
    {
      id: 'lit-en-52',
      content: `Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice 'without pictures or conversations?'`,
      source: 'Lewis Carroll, Alice\'s Adventures in Wonderland (1865)',
      language: 'en',
      difficulty: 2,
      wordCount: 57,
      charCount: 302,
      tags: ["carroll", "fantasy", "novel"],
    },
    {
      id: 'lit-en-53',
      content: `There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further outdoor exercise was now out of the question.`,
      source: 'Charlotte Brontë, Jane Eyre (1847)',
      language: 'en',
      difficulty: 3,
      wordCount: 62,
      charCount: 346,
      tags: ["brontë", "gothic", "novel"],
    },
    {
      id: 'lit-en-54',
      content: `During the whole of a dull, dark, and soundless day in the autumn of the year, when the clouds hung oppressively low in the heavens, I had been passing alone, on horseback, through a singularly dreary tract of country, and at length found myself, as the shades of the evening drew on, within view of the melancholy House of Usher. I know not how it was—but, with the first glimpse of the building, a sense of insufferable gloom pervaded my spirit.`,
      source: 'Edgar Allan Poe, The Fall of the House of Usher (1839)',
      language: 'en',
      difficulty: 4,
      wordCount: 81,
      charCount: 447,
      tags: ["poe", "gothic", "short story"],
    },
    {
      id: 'lit-en-55',
      content: `"Christmas won't be Christmas without any presents," grumbled Jo, lying on the rug. "It's so dreadful to be poor!" sighed Meg, looking down at her old dress. "I don't think it's fair for some girls to have plenty of pretty things, and other girls nothing at all," added little Amy, with an injured sniff. "We've got Father and Mother, and each other," said Beth contentedly from her corner. The four young faces on which the firelight shone brightened at the cheerful words, but darkened again as Jo said sadly, "We haven't got Father, and shall not have him for a long time."`,
      source: 'Louisa May Alcott, Little Women (1868)',
      language: 'en',
      difficulty: 2,
      wordCount: 102,
      charCount: 576,
      tags: ["alcott", "family", "novel"],
    },
    {
      id: 'lit-en-56',
      content: `1801—I have just returned from a visit to my landlord—the solitary neighbour that I shall be troubled with. This is certainly a beautiful country! In all England, I do not believe that I could have fixed on a situation so completely removed from the stir of society. A perfect misanthropist's Heaven—and Mr. Heathcliff and I are such a suitable pair to divide the desolation between us. A capital fellow! He little imagined how my heart warmed towards him when I beheld his black eyes withdraw so suspiciously under their brows, as I rode up.`,
      source: 'Emily Brontë, Wuthering Heights (1847)',
      language: 'en',
      difficulty: 4,
      wordCount: 94,
      charCount: 542,
      tags: ["brontë", "gothic", "novel"],
    },
    {
      id: 'lit-fr-57',
      content: `L'année 1866 fut marquée par un événement bizarre, un phénomène inexpliqué et inexplicable que personne n'a sans doute oublié.`,
      source: 'Jules Verne, Vingt mille lieues sous les mers (1870)',
      language: 'fr',
      difficulty: 2,
      wordCount: 19,
      charCount: 126,
      tags: ["verne", "aventure", "chiffre"],
    },
    {
      id: 'lit-fr-58',
      content: `Le 24 février 1815, la vigie de Notre-Dame de la Garde signala le trois-mâts le Pharaon, venant de Smyrne, Trieste et Naples.`,
      source: 'Alexandre Dumas, Le Comte de Monte-Cristo (1844)',
      language: 'fr',
      difficulty: 2,
      wordCount: 22,
      charCount: 125,
      tags: ["dumas", "aventure", "chiffre"],
    },
    {
      id: 'lit-en-57',
      content: `Exclusive of the Lake basin and of 300,000 square miles in Texas and New Mexico, which in many aspects form a part of it, this basin contains about 1,250,000 square miles.`,
      source: 'Mark Twain, Life on the Mississippi (1883)',
      language: 'en',
      difficulty: 3,
      wordCount: 31,
      charCount: 171,
      tags: ["twain", "nonfiction", "chiffre"],
    },
    {
      id: 'lit-en-58',
      content: `In the year 1820 the ship Essex, Captain Pollard, of Nantucket, was cruising in the Pacific Ocean. One day she saw spouts, lowered her boats, and gave chase to a shoal of sperm whales.`,
      source: 'Herman Melville, Moby-Dick (1851)',
      language: 'en',
      difficulty: 3,
      wordCount: 34,
      charCount: 184,
      tags: ["melville", "adventure", "chiffre"],
    },
    {
      id: 'lit-fr-59',
      content: `Ce sont les lapins qui ont été étonnés ! Depuis si longtemps qu'ils voyaient la porte du moulin fermée, les murs et la plate-forme envahis par les herbes, ils avaient fini par croire que la race des meuniers était éteinte, et, trouvant la place bonne, ils en avaient fait quelque chose comme un quartier général, un centre d'opérations stratégiques.`,
      source: 'Alphonse Daudet, Lettres de mon moulin (1869)',
      language: 'fr',
      difficulty: 3,
      wordCount: 59,
      charCount: 349,
      tags: ["daudet","provence","nouvelle"],
    },
    {
      id: 'lit-fr-60',
      content: `Quelle journée admirable ! J'ai passé toute la matinée étendu sur l'herbe, devant ma maison, sous l'énorme platane qui la couvre, l'abrite et l'ombrage tout entière. J'aime ce pays, et j'aime y vivre parce que j'y ai mes racines, ces profondes et délicates racines qui attachent un homme à la terre où sont nés et morts ses aïeux.`,
      source: 'Guy de Maupassant, Le Horla (1887)',
      language: 'fr',
      difficulty: 3,
      wordCount: 58,
      charCount: 330,
      tags: ["maupassant","fantastique","nouvelle"],
    },
    {
      id: 'lit-fr-61',
      content: `J'avais toujours soupçonné les géographes de ne savoir ce qu'ils disent lorsqu'ils placent le champ de bataille de Munda dans le pays des Bastuli-Poeni, près de la moderne Monda, à quelque deux lieues au nord de Marbella. D'après mes propres conjectures sur le texte de l'anonyme, auteur du Bellum Hispaniense, je pensais qu'il fallait chercher aux environs de Montilla le lieu mémorable.`,
      source: 'Prosper Mérimée, Carmen (1845)',
      language: 'fr',
      difficulty: 4,
      wordCount: 62,
      charCount: 388,
      tags: ["merimee","nouvelle","espagne"],
    },
    {
      id: 'lit-fr-62',
      content: `Quand je commençai, avec Germain le fin laboureur, l'histoire que je me propose de vous dire, j'avais sous les yeux une composition d'Holbein, représentant un laboureur conduisant sa charrue au milieu d'un champ. Au loin, un paysage riant, quelques cabanes. Le soleil se couche derrière la colline. C'est la fin d'une rude journée de travail.`,
      source: 'George Sand, La Mare au diable (1846)',
      language: 'fr',
      difficulty: 3,
      wordCount: 55,
      charCount: 342,
      tags: ["sand","campagne","roman"],
    },
    {
      id: 'lit-fr-63',
      content: `Comme il est impossible que je prévoie le moment de ma fin, comme à mon âge les jours accordés aux hommes ne sont qu'une grâce, ou plutôt une rigueur, je vais m'expliquer. Il est bien temps que je quitte un monde qui me quitte, et que je ne regrette pas. Ces Mémoires ont été la passion de ma vie ; jamais nuit ne s'est passée sans que j'y aie songé.`,
      source: 'Chateaubriand, Mémoires d\'outre-tombe (1849)',
      language: 'fr',
      difficulty: 5,
      wordCount: 70,
      charCount: 350,
      tags: ["chateaubriand","memoires","romantisme"],
    },
    {
      id: 'lit-fr-64',
      content: `Ils étaient cinq, aux carrures terribles, accoudés à boire, dans une sorte de logis sombre qui sentait la saumure et la mer. Le gîte, trop bas pour leurs tailles, se rétrécissait par un bout, comme l'intérieur d'une grande mouette vidée ; il oscillait faiblement, en rendant une plainte monotone, avec une lenteur de sommeil.`,
      source: 'Pierre Loti, Pêcheur d\'Islande (1886)',
      language: 'fr',
      difficulty: 4,
      wordCount: 54,
      charCount: 325,
      tags: ["loti","mer","bretagne"],
    },
    {
      id: 'lit-fr-65',
      content: `Je vais vous dire ce que me rappellent, tous les ans, le ciel agité de l'automne, les premiers dîners à la lampe et les feuilles qui jaunissent dans les arbres qui frissonnent. Je vais vous dire ce que je vois quand je traverse le Luxembourg dans les premiers jours d'octobre, alors qu'il est un peu triste et plus beau que jamais.`,
      source: 'Anatole France, Le Livre de mon ami (1885)',
      language: 'fr',
      difficulty: 4,
      wordCount: 61,
      charCount: 331,
      tags: ["france","souvenir","paris"],
    },
    {
      id: 'lit-fr-66',
      content: `Il n'y a rien de plus beau que de savoir résister à l'ennui et à la fortune. Mon voyage me coûtera peu de chose ; il ne me fera perdre aucun temps, puisque je ne partirai qu'après souper, et que je serai de retour assez à temps pour dîner le lendemain. Ma chambre est située sous le quarante-cinquième degré de latitude.`,
      source: 'Xavier de Maistre, Voyage autour de ma chambre (1794)',
      language: 'fr',
      difficulty: 2,
      wordCount: 61,
      charCount: 320,
      tags: ["maistre","recit","ironie"],
    },
    {
      id: 'lit-fr-67',
      content: `Comment s'étaient-ils rencontrés ? Par hasard, comme tout le monde. Comment s'appelaient-ils ? Que vous importe. D'où venaient-ils ? Du lieu le plus prochain. Où allaient-ils ? Est-ce que l'on sait où l'on va ? Que disaient-ils ? Le maître ne disait rien, et Jacques disait que son capitaine disait que tout ce qui nous arrive de bien et de mal ici-bas était écrit là-haut.`,
      source: 'Denis Diderot, Jacques le fataliste et son maître (1796)',
      language: 'fr',
      difficulty: 5,
      wordCount: 65,
      charCount: 373,
      tags: ["diderot","philosophique","dialogue"],
    },
    {
      id: 'lit-fr-68',
      content: `Sur le côté oriental de la montagne qui s'élève derrière le Port-Louis de l'île de France, on voit, dans un terrain jadis cultivé, les ruines de deux petites cabanes. Elles sont situées presque au milieu d'un bassin formé par de grands rochers, qui n'a qu'une seule ouverture tournée au nord. On aperçoit à gauche la montagne appelée le morne de la Découverte.`,
      source: 'Bernardin de Saint-Pierre, Paul et Virginie (1788)',
      language: 'fr',
      difficulty: 3,
      wordCount: 62,
      charCount: 360,
      tags: ["bernardin","ile","roman"],
    },
    {
      id: 'lit-fr-69',
      content: `Ceux qui veulent connaître les malheurs de cette époque, il faut qu'ils s'imaginent d'abord un village au fond des Vosges, sur la lisière de la forêt du Graufthal. Là vivait un vieil horloger nommé Jean-Baptiste Werner, et son petit-fils Joseph, qui boitait d'une jambe depuis sa naissance, et que tout le monde appelait Joseph le boiteux.`,
      source: 'Erckmann-Chatrian, Histoire d\'un conscrit de 1813 (1864)',
      language: 'fr',
      difficulty: 4,
      wordCount: 56,
      charCount: 339,
      tags: ["erckmann-chatrian","guerre","vosges"],
    },
    {
      id: 'lit-fr-70',
      content: `Le savant lord Evandale n'avait guère plus de vingt-huit ans, quoiqu'il en parût à peine vingt-deux. C'était un jeune homme svelte et vigoureux, aux cheveux d'un blond doré comme ceux des dieux et des héros. Il joignait à cette beauté toute britannique un flegme aussi britannique, et l'on eût dit une statue antique.`,
      source: 'Théophile Gautier, Le Roman de la momie (1858)',
      language: 'fr',
      difficulty: 3,
      wordCount: 53,
      charCount: 317,
      tags: ["gautier","egypte","roman"],
    },
    {
      id: 'lit-en-59',
      content: `My father's family name being Pirrip, and my Christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip. So, I called myself Pip, and came to be called Pip. I give Pirrip as my father's family name, on the authority of his tombstone and my sister, Mrs. Joe Gargery, who married the blacksmith.`,
      source: 'Charles Dickens, Great Expectations (1861)',
      language: 'en',
      difficulty: 4,
      wordCount: 61,
      charCount: 340,
      tags: ["dickens","classic","english"],
    },
    {
      id: 'lit-en-60',
      content: `You don't know about me without you have read a book by the name of The Adventures of Tom Sawyer, but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied, one time or another.`,
      source: 'Mark Twain, The Adventures of Huckleberry Finn (1884)',
      language: 'en',
      difficulty: 3,
      wordCount: 64,
      charCount: 328,
      tags: ["twain","american","classic"],
    },
    {
      id: 'lit-en-61',
      content: `Squire Trelawney, Dr. Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, from the beginning to the end, keeping nothing back but the bearings of the island, and that only because there is still treasure not yet lifted, I take up my pen in the year of grace and go back to the time when my father kept the Admiral Benbow inn.`,
      source: 'Robert Louis Stevenson, Treasure Island (1883)',
      language: 'en',
      difficulty: 3,
      wordCount: 72,
      charCount: 389,
      tags: ["stevenson","adventure","classic"],
    },
    {
      id: 'lit-en-62',
      content: `The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees of the garden, there came through the open door the heavy scent of the lilac, or the more delicate perfume of the pink-flowering thorn. From the corner of the divan of Persian saddle-bags on which he was lying, Lord Henry Wotton could just catch the gleam of the honey-sweet blossoms of a laburnum.`,
      source: 'Oscar Wilde, The Picture of Dorian Gray (1890)',
      language: 'en',
      difficulty: 4,
      wordCount: 73,
      charCount: 406,
      tags: ["wilde","aesthetic","classic"],
    },
    {
      id: 'lit-en-63',
      content: `The Nellie, a cruising yawl, swung to her anchor without a flutter of the sails, and was at rest. The flood had made, the wind was nearly calm, and being bound down the river, the only thing for it was to come to and wait for the turn of the tide. The sea-reach of the Thames stretched before us like the beginning of an interminable waterway.`,
      source: 'Joseph Conrad, Heart of Darkness (1899)',
      language: 'en',
      difficulty: 5,
      wordCount: 66,
      charCount: 343,
      tags: ["conrad","sea","classic"],
    },
    {
      id: 'lit-en-64',
      content: `Buck did not read the newspapers, or he would have known that trouble was brewing, not alone for himself, but for every tide-water dog, strong of muscle and with warm, long hair, from Puget Sound to San Diego. Because men, groping in the Arctic darkness, had found a yellow metal, and because steamship and transportation companies were booming the find, thousands of men were rushing into the Northland.`,
      source: 'Jack London, The Call of the Wild (1903)',
      language: 'en',
      difficulty: 3,
      wordCount: 68,
      charCount: 404,
      tags: ["london","adventure","classic"],
    },
    {
      id: 'lit-en-65',
      content: `Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer's wife. Their house was small, for the lumber to build it had to be carried by wagon many miles. There were four walls, a floor and a roof, which made one room; and this room contained a rusty looking cookstove, a cupboard for the dishes, a table, three or four chairs, and the beds.`,
      source: 'L. Frank Baum, The Wonderful Wizard of Oz (1900)',
      language: 'en',
      difficulty: 2,
      wordCount: 78,
      charCount: 408,
      tags: ["baum","children","classic"],
    },
    {
      id: 'lit-en-66',
      content: `The Time Traveller, for so it will be convenient to speak of him, was expounding a recondite matter to us. His pale grey eyes shone and twinkled, and his usually pale face was flushed and animated. The fire burned brightly, and the soft radiance of the incandescent lights in the lilies of silver caught the bubbles that flashed and passed in our glasses.`,
      source: 'H. G. Wells, The Time Machine (1895)',
      language: 'en',
      difficulty: 4,
      wordCount: 63,
      charCount: 355,
      tags: ["wells","science-fiction","classic"],
    },
    {
      id: 'lit-en-67',
      content: `Left Munich at 8:35 P.M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:46, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little I could walk through the streets. I feared to go very far from the station, as we had arrived late and would start as near the correct time as possible.`,
      source: 'Bram Stoker, Dracula (1897)',
      language: 'en',
      difficulty: 4,
      wordCount: 74,
      charCount: 387,
      tags: ["stoker","gothic","classic"],
    },
    {
      id: 'lit-en-68',
      content: `The Mole had been working very hard all the morning, spring-cleaning his little home. First with brooms, then with dusters; then on ladders and steps and chairs, with a brush and a pail of whitewash; till he had dust in his throat and eyes, and splashes of whitewash all over his black fur, and an aching back and weary arms.`,
      source: 'Kenneth Grahame, The Wind in the Willows (1908)',
      language: 'en',
      difficulty: 3,
      wordCount: 60,
      charCount: 325,
      tags: ["grahame","children","classic"],
    },
    {
      id: 'lit-en-69',
      content: `When Mary Lennox was sent to Misselthwaite Manor to live with her uncle everybody said she was the most disagreeable-looking child ever seen. It was true, too. She had a little thin face and a little thin body, thin light hair and a sour expression. Her hair was yellow, and her face was yellow because she had been born in India and had always been ill in one way or another.`,
      source: 'Frances Hodgson Burnett, The Secret Garden (1911)',
      language: 'en',
      difficulty: 3,
      wordCount: 71,
      charCount: 376,
      tags: ["burnett","children","classic"],
    },
    {
      id: 'lit-en-70',
      content: `A green and yellow parrot, which hung in a cage outside the door, kept repeating over and over: Allez vous-en! Allez vous-en! Sapristi! That's all right! He could speak a little Spanish, and also a language which nobody understood, unless it was the mocking-bird that hung on the other side of the door, whistling his fluty notes out upon the breeze with maddening persistence.`,
      source: 'Kate Chopin, The Awakening (1899)',
      language: 'en',
      difficulty: 5,
      wordCount: 64,
      charCount: 377,
      tags: ["chopin","american","classic"],
    },
    {
      id: 'lit-en-71',
      content: `London. Michaelmas term lately over, and the Lord Chancellor sitting in Lincoln's Inn Hall. Implacable November weather. As much mud in the streets as if the waters had but newly retired from the face of the earth. Fog everywhere. Fog up the river, where it flows among green aits and meadows; fog down the river, where it rolls defiled among the tiers of shipping and the waterside pollutions of a great and dirty city. Fog on the Essex marshes, fog on the Kentish heights. Fog creeping into the cabooses of collier-brigs; fog lying out on the yards, and hovering in the rigging of great ships; fog drooping on the gunwales of barges and small boats.`,
      source: 'Charles Dickens, Bleak House (1853)',
      language: 'en',
      difficulty: 5,
      wordCount: 115,
      charCount: 651,
      tags: ["dickens","london","fog"],
    },
    {
      id: 'lit-fr-71',
      content: `C'était à Mégara, faubourg de Carthage, dans les jardins d'Hamilcar. Les soldats qu'il avait commandés en Sicile se donnaient un grand festin pour célébrer le jour anniversaire de la bataille d'Éryx, et comme le maître était absent et qu'ils se trouvaient nombreux, ils mangeaient et ils buvaient en pleine liberté. Les capitaines, portant des cothurnes de bronze, s'étaient placés dans le chemin du milieu, sous un voile de pourpre à franges d'or, qui s'étendait depuis le mur des écuries jusqu'à la première terrasse du palais ; le commun des soldats était répandu sous les arbres, où l'on distinguait quantité de bâtiments à toit plat, pressoirs, celliers, magasins, boulangeries et arsenaux, avec une cour pour les éléphants, des fosses pour les bêtes féroces, une prison pour les esclaves.`,
      source: 'Gustave Flaubert, Salammbô (1862)',
      language: 'fr',
      difficulty: 5,
      wordCount: 127,
      charCount: 794,
      tags: ["flaubert","carthage","antiquite"],
    },
    {
      id: 'lit-en-72',
      content: `In the bosom of one of those spacious coves which indent the eastern shore of the Hudson, at that broad expansion of the river denominated by the ancient Dutch navigators the Tappan Zee, there lies a small market town or rural port which by some is called Greensburgh, but which is more generally and properly known by the name of Tarry Town. Not far from this village, perhaps about two miles, there is a little valley among high hills, which is one of the quietest places in the whole world. A small brook glides through it, with just murmur enough to lull one to repose.`,
      source: 'Washington Irving, The Legend of Sleepy Hollow (1820)',
      language: 'en',
      difficulty: 4,
      wordCount: 105,
      charCount: 573,
      tags: ["irving","american","gothic"],
    },
    {
      id: 'lit-fr-72',
      content: `Le whist venait de finir. Les joueurs se levèrent de la table, quelques-uns causant, d'autres allant reprendre leur place à cette cheminée où le feu tombait, car on était aux premiers jours d'automne.`,
      source: 'Jules Barbey d\'Aurevilly, Les Diaboliques (1874)',
      language: 'fr',
      difficulty: 3,
      wordCount: 33,
      charCount: 200,
      tags: ["barbey","nouvelle","nuit"],
    },
    {
      id: 'lit-en-73',
      content: `One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies. Pennies saved one and two at a time by bulldozing the grocer and the vegetable man and the butcher until one's cheeks burned with the silent imputation of parsimony that such close dealing implied.`,
      source: 'O. Henry, The Gift of the Magi (1905)',
      language: 'en',
      difficulty: 3,
      wordCount: 50,
      charCount: 284,
      tags: ["ohenry","american","short-story"],
    },
  ],
};
