import type { ThemeConfig } from '@typewav/types';

export const APP_THEMES: Record<string, ThemeConfig> = {
  terminal: {
    id: 'terminal',
    name: 'Dark Terminal',
    description: 'Le terminal original.',
    isPremium: false,
    colors: {
      bg: '#000000',
      surface: '#0A0A0A',
      border: '#1A1A2E',
      accent: '#00D4AA',
      textPrimary: '#E8E8E8',
      textMuted: '#888888',
      error: '#FF4444',
      charPending: '#888888',
      charCorrect: '#00D4AA',
      charError: '#FF4444',
      charCurrent: '#E8E8E8',
      cursor: '#00D4AA',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'deep-burgundy': {
    id: 'deep-burgundy',
    name: 'Deep Burgundy',
    description: 'Rouge bordeaux et sable doré.',
    isPremium: false,
    colors: {
      bg: '#5B0E14',
      surface: '#4A0B10',
      border: '#3A080C',
      accent: '#F1E194',
      textPrimary: '#F1E194',
      textMuted: '#A89B66',
      error: '#FF6B6B',
      charPending: '#A89B66',
      charCorrect: '#F1E194',
      charError: '#FF6B6B',
      charCurrent: '#FFFFFF',
      cursor: '#F1E194',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'cyprus-sand': {
    id: 'cyprus-sand',
    name: 'Cyprus Sand',
    description: 'Cyprès profond et sable.',
    isPremium: false,
    colors: {
      bg: '#004643',
      surface: '#003A38',
      border: '#002E2D',
      accent: '#F0EDE5',
      textPrimary: '#F0EDE5',
      textMuted: '#95A6A2',
      error: '#FF6B6B',
      charPending: '#95A6A2',
      charCorrect: '#F0EDE5',
      charError: '#FF6B6B',
      charCurrent: '#FFFFFF',
      cursor: '#F0EDE5',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'night-imperial': {
    id: 'night-imperial',
    name: 'Night Imperial',
    description: 'Nuit et rouge impérial.',
    isPremium: false,
    colors: {
      bg: '#000F08',
      surface: '#001A0E',
      border: '#002514',
      accent: '#FB3640',
      textPrimary: '#E8E8E8',
      textMuted: '#888888',
      error: '#FF6B6B',
      charPending: '#888888',
      charCorrect: '#FB3640',
      charError: '#FF6B6B',
      charCurrent: '#FFFFFF',
      cursor: '#FB3640',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
};
