import { arcadeTheme, midnightSunTheme, noirTheme } from '@typewav/themes';
import type { ThemeConfig } from '@typewav/types';

/**
 * Thèmes rendus par l'application (sélecteur de /parametres, ThemeProvider,
 * ThemeScript).
 *
 * Tous les thèmes définis inline ici sont débloqués d'office
 * (`BASE_UNLOCKED_THEME_IDS`, ticket #64 : palette étendue à 26 thèmes libres
 * d'entrée). `noir` / `midnight-sun` / `arcade` viennent de `@typewav/themes`
 * (objets `ThemeConfig` complets, déjà AA) et restent débloqués par les
 * jalons `MILESTONES` (`first_session`, `sessions_50`, `wpm_70`) ; ce
 * déblocage par jalon devient peu pertinent maintenant que la majorité de la
 * palette est libre d'office, à retrancher séparément (voir HANDOFF.md).
 *
 * Contraste AA vérifié combinaison par combinaison dans
 * `apps/web/lib/__tests__/theme-contrast.test.ts`, qui boucle automatiquement
 * sur `Object.values(APP_THEMES)` : ajouter un thème ici l'intègre à la
 * couverture sans autre modification.
 */
export const APP_THEMES: Record<string, ThemeConfig> = {
  terminal: {
    id: 'terminal',
    name: 'Dark Terminal',
    description: 'Le terminal original.',
    isPremium: false,
    colors: {
      bg: '#000000',
      surface: '#0A0A0A',
      border: '#1A1A2E',
      accent: '#00D4AA',
      textPrimary: '#E8E8E8',
      textMuted: '#888888',
      error: '#FF4444',
      charPending: '#888888',
      charCorrect: '#00D4AA',
      charError: '#FF4444',
      charCurrent: '#E8E8E8',
      cursor: '#00D4AA',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'deep-burgundy': {
    id: 'deep-burgundy',
    name: 'Deep Burgundy',
    description: 'Rouge bordeaux et sable doré.',
    isPremium: false,
    colors: {
      bg: '#5B0E14',
      surface: '#4A0B10',
      border: '#3A080C',
      accent: '#F1E194',
      textPrimary: '#F1E194',
      textMuted: '#A89B66',
      error: '#FF6B6B',
      charPending: '#A89B66',
      charCorrect: '#F1E194',
      charError: '#FF6B6B',
      charCurrent: '#FFFFFF',
      cursor: '#F1E194',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'cyprus-sand': {
    id: 'cyprus-sand',
    name: 'Cyprus Sand',
    description: 'Cyprès profond et sable.',
    isPremium: false,
    colors: {
      bg: '#004643',
      surface: '#003A38',
      border: '#002E2D',
      accent: '#F0EDE5',
      textPrimary: '#F0EDE5',
      // textMuted / error remontés à WCAG 2.2 AA (>= 4.5:1 sur bg et surface).
      // Voir apps/web/lib/__tests__/theme-contrast.test.ts.
      textMuted: '#9EB0AB',
      error: '#FF8989',
      charPending: '#9EB0AB',
      charCorrect: '#F0EDE5',
      charError: '#FF8989',
      charCurrent: '#FFFFFF',
      cursor: '#F0EDE5',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'night-imperial': {
    id: 'night-imperial',
    name: 'Night Imperial',
    description: 'Nuit et rouge impérial.',
    isPremium: false,
    colors: {
      bg: '#000F08',
      surface: '#001A0E',
      border: '#002514',
      accent: '#FB3640',
      textPrimary: '#E8E8E8',
      textMuted: '#888888',
      error: '#FF6B6B',
      charPending: '#888888',
      charCorrect: '#FB3640',
      charError: '#FF6B6B',
      charCurrent: '#FFFFFF',
      cursor: '#FB3640',
    },
    fonts: {
      display: 'Cormorant Garamond',
      ui: 'Sora',
      mono: 'JetBrains Mono',
    },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  // Ticket #64 : 22 thèmes supplémentaires, débloqués d'office. Contraste AA
  // vérifié un par un (voir theme-contrast.test.ts). chordProgressionId
  // reste 'terminal' comme les 4 thèmes de base ci-dessus : ChordProgressionTheme
  // n'a que 4 valeurs ('terminal'/'noir'/'midnight-sun'/'arcade'), inventer un
  // id par thème pointerait vers une progression inexistante.
  'terminal-amber': {
    id: 'terminal-amber',
    name: 'Terminal Ambre',
    description: 'Phosphore ambre sur noir, écran cathodique.',
    isPremium: false,
    colors: {
      bg: '#0A0600',
      surface: '#120B00',
      border: '#241706',
      accent: '#FFB000',
      textPrimary: '#FFD37A',
      textMuted: '#C99A3E',
      error: '#FF6B57',
      charPending: '#C99A3E',
      charCorrect: '#FFB000',
      charError: '#FF6B57',
      charCurrent: '#FFF3D6',
      cursor: '#FFB000',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  blueprint: {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Bleu marine et lignes techniques.',
    isPremium: false,
    colors: {
      bg: '#06121F',
      surface: '#0A1B2E',
      border: '#12314D',
      accent: '#63C9F5',
      textPrimary: '#DCEEFB',
      textMuted: '#78ADCB',
      error: '#FF7A7A',
      charPending: '#78ADCB',
      charCorrect: '#63C9F5',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#63C9F5',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  matcha: {
    id: 'matcha',
    name: 'Matcha',
    description: 'Vert thé profond, calme et concentré.',
    isPremium: false,
    colors: {
      bg: '#0B1509',
      surface: '#10200D',
      border: '#1B3315',
      accent: '#8FC15C',
      textPrimary: '#E4EFD8',
      textMuted: '#8AA875',
      error: '#FF8577',
      charPending: '#8AA875',
      charCorrect: '#8FC15C',
      charError: '#FF8577',
      charCurrent: '#F3FAE9',
      cursor: '#8FC15C',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  abysse: {
    id: 'abysse',
    name: 'Abysse',
    description: 'Bleu abyssal et lueur bioluminescente.',
    isPremium: false,
    colors: {
      bg: '#01050C',
      surface: '#030A16',
      border: '#0A1830',
      accent: '#3FDFC6',
      textPrimary: '#DFF7F2',
      textMuted: '#68A4B0',
      error: '#FF7A7A',
      charPending: '#68A4B0',
      charCorrect: '#3FDFC6',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#3FDFC6',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'cuivre-anthracite': {
    id: 'cuivre-anthracite',
    name: 'Cuivre et Anthracite',
    description: 'Anthracite et reflets de cuivre.',
    isPremium: false,
    colors: {
      bg: '#0E0C0B',
      surface: '#171310',
      border: '#2B2119',
      accent: '#E8894B',
      textPrimary: '#F0E4D8',
      textMuted: '#BC9575',
      error: '#FF7A6C',
      charPending: '#BC9575',
      charCorrect: '#E8894B',
      charError: '#FF7A6C',
      charCurrent: '#FFF6EC',
      cursor: '#E8894B',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'sable-lunaire': {
    id: 'sable-lunaire',
    name: 'Sable Lunaire',
    description: 'Parchemin clair, encre profonde.',
    isPremium: false,
    colors: {
      bg: '#F5EFE3',
      surface: '#EDE4D0',
      border: '#D8CBAE',
      accent: '#3A5A7A',
      textPrimary: '#241B12',
      textMuted: '#5B4E3B',
      error: '#A32E22',
      charPending: '#5B4E3B',
      charCorrect: '#3A5A7A',
      charError: '#A32E22',
      charCurrent: '#000000',
      cursor: '#3A5A7A',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'rouille-lin': {
    id: 'rouille-lin',
    name: 'Rouille et Lin',
    description: 'Lin clair et rouille chaude.',
    isPremium: false,
    colors: {
      bg: '#FAF3E0',
      surface: '#F1E6CB',
      border: '#DFCBA0',
      accent: '#9C3A0E',
      textPrimary: '#2B2013',
      textMuted: '#5E4C33',
      error: '#9E2016',
      charPending: '#5E4C33',
      charCorrect: '#9C3A0E',
      charError: '#9E2016',
      charCurrent: '#000000',
      cursor: '#9C3A0E',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'bitume-chlorophylle': {
    id: 'bitume-chlorophylle',
    name: 'Bitume Chlorophylle',
    description: 'Bitume noir et vert chlorophylle acide.',
    isPremium: false,
    colors: {
      bg: '#0B0B0B',
      surface: '#131313',
      border: '#232323',
      accent: '#9BE035',
      textPrimary: '#EAF7C9',
      textMuted: '#8FAC5D',
      error: '#FF6B57',
      charPending: '#8FAC5D',
      charCorrect: '#9BE035',
      charError: '#FF6B57',
      charCurrent: '#F5FBE3',
      cursor: '#9BE035',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'carbone-menthe': {
    id: 'carbone-menthe',
    name: 'Carbone Menthe',
    description: 'Carbone noir et menthe fraîche.',
    isPremium: false,
    colors: {
      bg: '#0A0E0D',
      surface: '#101715',
      border: '#1D2A26',
      accent: '#6DF2CE',
      textPrimary: '#DFF8EF',
      textMuted: '#6BB59A',
      error: '#FF7A6C',
      charPending: '#6BB59A',
      charCorrect: '#6DF2CE',
      charError: '#FF7A6C',
      charCurrent: '#FFFFFF',
      cursor: '#6DF2CE',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'nocturne-dore': {
    id: 'nocturne-dore',
    name: 'Nocturne Doré',
    description: 'Nuit marine et éclat doré.',
    isPremium: false,
    colors: {
      bg: '#070B14',
      surface: '#0D1220',
      border: '#1A2338',
      accent: '#E8C547',
      textPrimary: '#F3EBCF',
      textMuted: '#AFA878',
      error: '#FF7A7A',
      charPending: '#AFA878',
      charCorrect: '#E8C547',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#E8C547',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  cassis: {
    id: 'cassis',
    name: 'Cassis',
    description: 'Cassis profond et rose poudré.',
    isPremium: false,
    colors: {
      bg: '#0D0710',
      surface: '#170D1D',
      border: '#2B1832',
      accent: '#E39FB4',
      textPrimary: '#F4E3EA',
      textMuted: '#B98FA0',
      error: '#FF7A7A',
      charPending: '#B98FA0',
      charCorrect: '#E39FB4',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#E39FB4',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'corail-nocturne': {
    id: 'corail-nocturne',
    name: 'Corail Nocturne',
    description: 'Marine sombre et corail vif.',
    isPremium: false,
    colors: {
      bg: '#060E14',
      surface: '#0B1620',
      border: '#16283A',
      accent: '#FF8F70',
      textPrimary: '#F7E9E2',
      textMuted: '#AC8D82',
      error: '#FF5C7A',
      charPending: '#AC8D82',
      charCorrect: '#FF8F70',
      charError: '#FF5C7A',
      charCurrent: '#FFFFFF',
      cursor: '#FF8F70',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'ardoise-tilleul': {
    id: 'ardoise-tilleul',
    name: 'Ardoise et Tilleul',
    description: 'Ardoise grise et tilleul acidulé.',
    isPremium: false,
    colors: {
      bg: '#16161C',
      surface: '#1E1E27',
      border: '#333340',
      accent: '#BEEB8F',
      textPrimary: '#EDF3DE',
      textMuted: '#9CAA8A',
      error: '#FF8577',
      charPending: '#9CAA8A',
      charCorrect: '#BEEB8F',
      charError: '#FF8577',
      charCurrent: '#FFFFFF',
      cursor: '#BEEB8F',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'sakura-nuit': {
    id: 'sakura-nuit',
    name: 'Sakura Nuit',
    description: 'Nuit noire et fleurs de cerisier.',
    isPremium: false,
    colors: {
      bg: '#0C0709',
      surface: '#150D10',
      border: '#281820',
      accent: '#F5A6C6',
      textPrimary: '#FBE9EF',
      textMuted: '#C298AB',
      error: '#FF7A7A',
      charPending: '#C298AB',
      charCorrect: '#F5A6C6',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#F5A6C6',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'neon-tokyo': {
    id: 'neon-tokyo',
    name: 'Néon Tokyo',
    description: 'Nuit électrique, rose néon.',
    isPremium: false,
    colors: {
      bg: '#08060D',
      surface: '#0F0B17',
      border: '#1D1730',
      accent: '#FF5FA0',
      textPrimary: '#F2E9F5',
      textMuted: '#AD90B8',
      error: '#FF6B57',
      charPending: '#AD90B8',
      charCorrect: '#FF5FA0',
      charError: '#FF6B57',
      charCurrent: '#FFFFFF',
      cursor: '#FF5FA0',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'sable-sahara': {
    id: 'sable-sahara',
    name: 'Sable du Sahara',
    description: 'Argile du désert et sable doré.',
    isPremium: false,
    colors: {
      bg: '#140B06',
      surface: '#1E120A',
      border: '#351D0F',
      accent: '#E7B458',
      textPrimary: '#F5E4C8',
      textMuted: '#BB9A6E',
      error: '#FF7A6C',
      charPending: '#BB9A6E',
      charCorrect: '#E7B458',
      charError: '#FF7A6C',
      charCurrent: '#FFF6E5',
      cursor: '#E7B458',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'vieux-cuivre': {
    id: 'vieux-cuivre',
    name: 'Vieux Cuivre',
    description: 'Sépia patiné, vieille photographie.',
    isPremium: false,
    colors: {
      bg: '#100B06',
      surface: '#1A130B',
      border: '#2E2213',
      accent: '#D3A264',
      textPrimary: '#EFDFC4',
      textMuted: '#B4936A',
      error: '#FF7A6C',
      charPending: '#B4936A',
      charCorrect: '#D3A264',
      charError: '#FF7A6C',
      charCurrent: '#FBF0DC',
      cursor: '#D3A264',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  glacier: {
    id: 'glacier',
    name: 'Glacier',
    description: 'Nuit polaire et glace bleutée.',
    isPremium: false,
    colors: {
      bg: '#060A10',
      surface: '#0C131C',
      border: '#1B2A3A',
      accent: '#8FD9F5',
      textPrimary: '#E4F4FB',
      textMuted: '#7BA3B8',
      error: '#FF7A7A',
      charPending: '#7BA3B8',
      charCorrect: '#8FD9F5',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#8FD9F5',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'cobalt-industriel': {
    id: 'cobalt-industriel',
    name: 'Cobalt Industriel',
    description: 'Graphite industriel et bleu cobalt.',
    isPremium: false,
    colors: {
      bg: '#0B0D10',
      surface: '#141719',
      border: '#262B2F',
      accent: '#5B93FF',
      textPrimary: '#E4E9EF',
      textMuted: '#98A6B3',
      error: '#FF7A7A',
      charPending: '#98A6B3',
      charCorrect: '#5B93FF',
      charError: '#FF7A7A',
      charCurrent: '#FFFFFF',
      cursor: '#5B93FF',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'volcan-obsidienne': {
    id: 'volcan-obsidienne',
    name: 'Volcan Obsidienne',
    description: 'Obsidienne noire et lave incandescente.',
    isPremium: false,
    colors: {
      bg: '#080605',
      surface: '#110C09',
      border: '#241812',
      accent: '#FF6A3D',
      textPrimary: '#F5E2D6',
      textMuted: '#BC8F7C',
      error: '#FF5C7A',
      charPending: '#BC8F7C',
      charCorrect: '#FF6A3D',
      charError: '#FF5C7A',
      charCurrent: '#FFF1E7',
      cursor: '#FF6A3D',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  'ardoise-ecarlate': {
    id: 'ardoise-ecarlate',
    name: 'Ardoise Écarlate',
    description: 'Ardoise sombre et rouge écarlate.',
    isPremium: false,
    colors: {
      bg: '#0D0E10',
      surface: '#151719',
      border: '#262A2E',
      accent: '#FF5C6C',
      textPrimary: '#E9EBEE',
      textMuted: '#9CA3AB',
      error: '#FF3B4E',
      charPending: '#9CA3AB',
      charCorrect: '#FF5C6C',
      charError: '#FF3B4E',
      charCurrent: '#FFFFFF',
      cursor: '#FF5C6C',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  riviera: {
    id: 'riviera',
    name: 'Riviera',
    description: 'Nuit méditerranéenne, turquoise chaud.',
    isPremium: false,
    colors: {
      bg: '#080F0E',
      surface: '#0E1716',
      border: '#16241F',
      accent: '#3ECFC0',
      textPrimary: '#E1F3F0',
      textMuted: '#6FA89E',
      error: '#FF7A6C',
      charPending: '#6FA89E',
      charCorrect: '#3ECFC0',
      charError: '#FF7A6C',
      charCurrent: '#FFFFFF',
      cursor: '#3ECFC0',
    },
    fonts: { display: 'Cormorant Garamond', ui: 'Sora', mono: 'JetBrains Mono' },
    chordProgressionId: 'terminal',
    defaultSoundPackId: 'piano',
  },
  // Thèmes de jalon : définis dans `@typewav/themes`, débloqués via MILESTONES.
  noir: noirTheme,
  'midnight-sun': midnightSunTheme,
  arcade: arcadeTheme,
};

/**
 * Thèmes débloqués d'office. Seule vérité du défaut, importée par
 * `db.ts` (`DEFAULT_PROFILE.unlockedThemes`) et par le sélecteur de thème.
 * Tout ce qui n'est pas là est derrière un jalon.
 */
export const BASE_UNLOCKED_THEME_IDS = [
  'terminal',
  'deep-burgundy',
  'cyprus-sand',
  'night-imperial',
  'terminal-amber',
  'blueprint',
  'matcha',
  'abysse',
  'cuivre-anthracite',
  'sable-lunaire',
  'rouille-lin',
  'bitume-chlorophylle',
  'carbone-menthe',
  'nocturne-dore',
  'cassis',
  'corail-nocturne',
  'ardoise-tilleul',
  'sakura-nuit',
  'neon-tokyo',
  'sable-sahara',
  'vieux-cuivre',
  'glacier',
  'cobalt-industriel',
  'volcan-obsidienne',
  'ardoise-ecarlate',
  'riviera',
] as const;
