/**
 * Collection Philosophie — extraits du domaine public (auteurs morts > 70 ans).
 * Sources : Wikisource, Project Gutenberg, traductions classiques.
 * Spec : docs/specs/06-content.md
 */

import type { CollectionConfig } from '@typewav/types';

export const philosophieCollection: CollectionConfig = {
  id: 'philosophie',
  name: 'Philosophie',
  nameEn: 'Philosophy',
  description:
    'Fragments de la pensée universelle — Descartes, Pascal, Nietzsche et leurs pairs.',
  language: 'multi',
  recommendedTheme: 'noir',
  isPremium: false,
  texts: [
    {
      id: 'phi-fr-01',
      content: `Je pense, donc je suis. Cette vérité est si ferme et si assurée que toutes les plus extravagantes suppositions des sceptiques ne sont pas capables de l'ébranler.`,
      source: 'René Descartes — Discours de la méthode (1637)',
      language: 'fr',
      difficulty: 5,
      wordCount: 27,
      charCount: 161,
      tags: ["descartes","rationalisme","cogito"],
    },
    {
      id: 'phi-fr-02',
      content: `Le cœur a ses raisons que la raison ne connaît point. On le sait en mille choses.`,
      source: 'Blaise Pascal — Pensées (1670)',
      language: 'fr',
      difficulty: 1,
      wordCount: 17,
      charCount: 81,
      tags: ["pascal","raison","cœur"],
    },
    {
      id: 'phi-fr-03',
      content: `L'homme est né libre, et partout il est dans les fers. Tel se croit le maître des autres qui ne laisse pas d'être plus esclave qu'eux.`,
      source: 'Jean-Jacques Rousseau — Du Contrat social (1762)',
      language: 'fr',
      difficulty: 3,
      wordCount: 26,
      charCount: 134,
      tags: ["rousseau","liberté","contrat social"],
    },
    {
      id: 'phi-fr-04',
      content: `Si Dieu n'existait pas, il faudrait l'inventer. Mais toute la nature nous crie qu'il existe.`,
      source: 'Voltaire — Épître à l\'auteur du livre des Trois Imposteurs (1769)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 92,
      tags: ["voltaire","déisme","raison"],
    },
    {
      id: 'phi-fr-05',
      content: `Que sais-je ? Cette belle parole est la devise du scepticisme, et c'est aussi la devise de toute philosophie.`,
      source: 'Michel de Montaigne — Essais (1580)',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 109,
      tags: ["montaigne","scepticisme","essais"],
    },
    {
      id: 'phi-fr-06',
      content: `Ce qui nous trouble, ce ne sont pas les événements, mais les opinions que nous avons des événements.`,
      source: 'Épictète — Manuel (vers 125 ap. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 100,
      tags: ["épictète","stoïcisme","opinion"],
    },
    {
      id: 'phi-fr-07',
      content: `L'homme libre ne pense à aucune chose moins qu'à la mort, et sa sagesse est une méditation non de la mort, mais de la vie.`,
      source: 'Baruch Spinoza, Éthique (1677)',
      language: 'fr',
      difficulty: 5,
      wordCount: 25,
      charCount: 122,
      tags: ["spinoza", "liberté", "vie"],
    },
    {
      id: 'phi-fr-08',
      content: `Dieu est mort. Dieu reste mort. Et c'est nous qui l'avons tué. Comment nous consoler, nous les meurtriers des meurtriers ?`,
      source: 'Friedrich Nietzsche — Le Gai Savoir (1882)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 122,
      tags: ["nietzsche","nihilisme","modernité"],
    },
    {
      id: 'phi-fr-09',
      content: `La vie doit être comprise à rebours, mais elle doit être vécue en avant. Telle est la condition de ceux qui réfléchissent.`,
      source: 'Søren Kierkegaard — Journal (vers 1843)',
      language: 'fr',
      difficulty: 5,
      wordCount: 22,
      charCount: 122,
      tags: ["kierkegaard","existence","temps"],
    },
    {
      id: 'phi-fr-10',
      content: `Agis seulement d'après la maxime grâce à laquelle tu peux vouloir en même temps qu'elle devienne une loi universelle.`,
      source: 'Emmanuel Kant — Fondation de la métaphysique des mœurs (1785)',
      language: 'fr',
      difficulty: 5,
      wordCount: 19,
      charCount: 117,
      tags: ["kant","impératif catégorique","éthique"],
    },
    {
      id: 'phi-fr-11',
      content: `Nous ne cherchons pas seulement à connaître ce que les philosophes ont pensé, mais aussi ce que pensent les choses elles-mêmes.`,
      source: 'Aristote — Métaphysique (IVe siècle av. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 127,
      tags: ["aristote","métaphysique","vérité"],
    },
    {
      id: 'phi-fr-12',
      content: `Une vie sans examen ne vaut pas la peine d'être vécue pour un homme.`,
      source: 'Socrate — cité par Platon, Apologie (399 av. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 14,
      charCount: 68,
      tags: ["socrate","platon","vertu"],
    },
    {
      id: 'phi-fr-13',
      content: `La vérité est un flambeau, mais un flambeau énorme, et tout le monde a peur de se brûler.`,
      source: 'Claude Adrien Helvétius — De l\'esprit (1758)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 89,
      tags: ["helvétius","vérité","lumières"],
    },
    {
      id: 'phi-fr-14',
      content: `Ne perds plus de temps à discuter ce que doit être un homme de bien. Sois-le.`,
      source: 'Marc Aurèle, Pensées pour moi-même (traduction classique)',
      language: 'fr',
      difficulty: 2,
      wordCount: 16,
      charCount: 77,
      tags: ["marc aurèle", "stoïcisme", "action"],
    },
    {
      id: 'phi-fr-15',
      content: `Ne pas railler, ne pas déplorer, ne pas maudire, mais comprendre.`,
      source: 'Baruch Spinoza, Traité politique (1677)',
      language: 'fr',
      difficulty: 3,
      wordCount: 11,
      charCount: 65,
      tags: ["spinoza", "compréhension", "raison"],
    },
    {
      id: 'phi-fr-16',
      content: `Chaque homme porte la forme entière de l'humaine condition.`,
      source: 'Michel de Montaigne — Essais (1580)',
      language: 'fr',
      difficulty: 3,
      wordCount: 9,
      charCount: 59,
      tags: ["montaigne","humanité","condition"],
    },
    {
      id: 'phi-fr-17',
      content: `Il vaut mieux débattre une question sans la trancher que la trancher sans la débattre.`,
      source: 'Joseph Joubert, Pensées (1838)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 86,
      tags: ["joubert", "débat", "jugement"],
    },
    {
      id: 'phi-fr-18',
      content: `La liberté est le droit de faire tout ce que les lois permettent.`,
      source: 'Montesquieu, De l\'esprit des lois (1748)',
      language: 'fr',
      difficulty: 2,
      wordCount: 13,
      charCount: 65,
      tags: ["montesquieu", "liberté", "loi"],
    },
    {
      id: 'phi-fr-19',
      content: `Soyez résolus de ne servir plus, et vous voilà libres.`,
      source: 'Étienne de La Boétie, Discours de la servitude volontaire (1576)',
      language: 'fr',
      difficulty: 3,
      wordCount: 10,
      charCount: 54,
      tags: ["la boétie", "servitude", "liberté"],
    },
    {
      id: 'phi-fr-20',
      content: `Le doute est le commencement de la sagesse.`,
      source: 'Aristote — Métaphysique (traduction)',
      language: 'fr',
      difficulty: 1,
      wordCount: 8,
      charCount: 43,
      tags: ["aristote","doute","sagesse"],
    },
    {
      id: 'phi-fr-21',
      content: `Penser, c'est dire non.`,
      source: 'Alain — Propos sur l\'éducation (1932)',
      language: 'fr',
      difficulty: 1,
      wordCount: 4,
      charCount: 23,
      tags: ["alain","pensée","refus"],
    },
    {
      id: 'phi-fr-22',
      content: `La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui.`,
      source: 'Déclaration des droits de l\'homme (1789)',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 69,
      tags: ["liberté","droit","autrui"],
    },
    {
      id: 'phi-fr-23',
      content: `Nul n'est méchant volontairement.`,
      source: 'Platon — Ménon (traduction classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 4,
      charCount: 33,
      tags: ["platon","méchanceté","volonté"],
    },
    {
      id: 'phi-fr-24',
      content: `Le commencement est la moitié du tout.`,
      source: 'Pythagore — Maximes (VIe siècle av. J.-C.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 38,
      tags: ["pythagore","commencement","action"],
    },
    {
      id: 'phi-fr-25',
      content: `Mens sana in corpore sano. Un esprit sain dans un corps sain.`,
      source: 'Juvénal — Satires (Ier siècle ap. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 2,
      wordCount: 12,
      charCount: 61,
      tags: ["juvénal","santé","équilibre"],
    },
    {
      id: 'phi-fr-26',
      content: `La nature ne fait rien en vain.`,
      source: 'Aristote — De caelo (traduction classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 31,
      tags: ["aristote","nature","téléologie"],
    },
    {
      id: 'phi-fr-27',
      content: `Connais-toi toi-même et tu connaîtras l'univers et les dieux.`,
      source: 'Socrate — Apophtegme (cité par Platon)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 61,
      tags: ["socrate","connaissance","soi"],
    },
    {
      id: 'phi-fr-28',
      content: `Notre grand et glorieux chef-d'œuvre, c'est vivre à propos.`,
      source: 'Michel de Montaigne, Essais (1580)',
      language: 'fr',
      difficulty: 4,
      wordCount: 9,
      charCount: 59,
      tags: ["montaigne", "vie", "sagesse"],
    },
    {
      id: 'phi-fr-29',
      content: `La force n'est pas la brutalité et la faiblesse n'est pas la douceur.`,
      source: 'Khalil Gibran — Le Prophète (1923)',
      language: 'fr',
      difficulty: 3,
      wordCount: 13,
      charCount: 69,
      tags: ["gibran","force","douceur"],
    },
    {
      id: 'phi-fr-30',
      content: `Le courage, c'est de chercher la vérité et de la dire.`,
      source: 'Jean Jaurès — Discours (1903)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 54,
      tags: ["jaurès","courage","vérité"],
    },
    {
      id: 'phi-en-01',
      content: `To be or not to be, that is the question: whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune.`,
      source: 'William Shakespeare — Hamlet (1603)',
      language: 'en',
      difficulty: 3,
      wordCount: 25,
      charCount: 128,
      tags: ["shakespeare","existence","theatre"],
    },
    {
      id: 'phi-en-02',
      content: `The unexamined life is not worth living. We must care for our soul before we care for our body or our wealth.`,
      source: 'Plato — Apology (399 BC, classical translation)',
      language: 'en',
      difficulty: 3,
      wordCount: 22,
      charCount: 109,
      tags: ["plato","socrates","virtue"],
    },
    {
      id: 'phi-en-03',
      content: `Man is by nature a political animal. Outside of society he is either a beast or a god.`,
      source: 'Aristotle — Politics (350 BC, classical translation)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 86,
      tags: ["aristotle","politics","nature"],
    },
    {
      id: 'phi-en-04',
      content: `Knowledge is power. Reading maketh a full man, conference a ready man, and writing an exact man.`,
      source: 'Francis Bacon — Essays (1597)',
      language: 'en',
      difficulty: 1,
      wordCount: 17,
      charCount: 96,
      tags: ["bacon","knowledge","empiricism"],
    },
    {
      id: 'phi-en-05',
      content: `It is not enough to have a good mind; the main thing is to use it well.`,
      source: 'René Descartes, Discourse on the Method (1637)',
      language: 'en',
      difficulty: 2,
      wordCount: 17,
      charCount: 71,
      tags: ["descartes", "reason", "method"],
    },
    {
      id: 'phi-en-06',
      content: `To do as one would be done by, and to love one's neighbour as oneself, constitute the ideal perfection of utilitarian morality.`,
      source: 'John Stuart Mill — Utilitarianism (1863)',
      language: 'en',
      difficulty: 5,
      wordCount: 22,
      charCount: 127,
      tags: ["mill","utilitarianism","ethics"],
    },
    {
      id: 'phi-en-07',
      content: `The life of man, solitary, poor, nasty, brutish, and short. In such condition there is no place for industry.`,
      source: 'Thomas Hobbes — Leviathan (1651)',
      language: 'en',
      difficulty: 5,
      wordCount: 19,
      charCount: 109,
      tags: ["hobbes","state of nature","politics"],
    },
    {
      id: 'phi-en-08',
      content: `God is dead. We have killed him. How shall we comfort ourselves, the murderers of all murderers?`,
      source: 'Friedrich Nietzsche — The Gay Science (1882)',
      language: 'en',
      difficulty: 3,
      wordCount: 17,
      charCount: 96,
      tags: ["nietzsche","nihilism","modernity"],
    },
    {
      id: 'phi-en-09',
      content: `We suffer more often in imagination than in reality.`,
      source: 'Seneca, Letters to Lucilius (classical translation)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 52,
      tags: ["seneca", "stoicism", "fear"],
    },
    {
      id: 'phi-en-10',
      content: `The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.`,
      source: 'John Milton, Paradise Lost (1667)',
      language: 'en',
      difficulty: 4,
      wordCount: 19,
      charCount: 85,
      tags: ["milton", "mind", "freedom"],
    },
    {
      id: 'phi-en-11',
      content: `The more I know, the more I realize I know nothing.`,
      source: 'Socrates — attributed (classical)',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["socrates","knowledge","humility"],
    },
    {
      id: 'phi-en-12',
      content: `We are what we repeatedly do. Excellence, then, is not an act, but a habit.`,
      source: 'Aristotle — Nicomachean Ethics (classical translation)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 75,
      tags: ["aristotle","excellence","habit"],
    },
    {
      id: 'phi-en-13',
      content: `Do not go where the path may lead; go instead where there is no path and leave a trail.`,
      source: 'Ralph Waldo Emerson — Self-Reliance (1841)',
      language: 'en',
      difficulty: 3,
      wordCount: 19,
      charCount: 87,
      tags: ["emerson","path","individualism"],
    },
    {
      id: 'phi-en-14',
      content: `Freedom is not worth having if it does not include the freedom to make mistakes.`,
      source: 'Mahatma Gandhi — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 80,
      tags: ["gandhi","freedom","mistakes"],
    },
    {
      id: 'phi-en-15',
      content: `In the middle of difficulty lies opportunity.`,
      source: 'Albert Einstein — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 45,
      tags: ["einstein","difficulty","opportunity"],
    },
    {
      id: 'phi-en-16',
      content: `It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.`,
      source: 'Charles Darwin — On the Origin of Species (1859)',
      language: 'en',
      difficulty: 4,
      wordCount: 21,
      charCount: 117,
      tags: ["darwin","evolution","adaptation"],
    },
    {
      id: 'phi-en-17',
      content: `One cannot step into the same river twice. Everything flows.`,
      source: 'Heraclitus — Fragments (c.500 BC, classical translation)',
      language: 'en',
      difficulty: 2,
      wordCount: 10,
      charCount: 60,
      tags: ["heraclitus","change","river"],
    },
    {
      id: 'phi-en-18',
      content: `The greatest wealth is to live content with little.`,
      source: 'Plato — Republic (classical translation)',
      language: 'en',
      difficulty: 1,
      wordCount: 9,
      charCount: 51,
      tags: ["plato","wealth","contentment"],
    },
    {
      id: 'phi-en-19',
      content: `To live is the rarest thing in the world. Most people exist, that is all.`,
      source: 'Oscar Wilde — The Soul of Man Under Socialism (1891)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 73,
      tags: ["wilde","existence","living"],
    },
    {
      id: 'phi-en-20',
      content: `Treat others as you wish to be treated. This is the whole of the Law.`,
      source: 'Hillel the Elder — Talmud (c. 110 BC)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 69,
      tags: ["hillel","golden rule","ethics"],
    },
    {
      id: 'phi-en-21',
      content: `The truth is rarely pure and never simple.`,
      source: 'Oscar Wilde — The Importance of Being Earnest (1895)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 42,
      tags: ["wilde","truth","simplicity"],
    },
    {
      id: 'phi-en-22',
      content: `Power tends to corrupt, and absolute power corrupts absolutely.`,
      source: 'Lord Acton — Historical Essays (1887)',
      language: 'en',
      difficulty: 3,
      wordCount: 9,
      charCount: 63,
      tags: ["acton","power","corruption"],
    },
    {
      id: 'phi-en-23',
      content: `Time is money. Lost time is never found again.`,
      source: 'Benjamin Franklin — Advice to a Young Tradesman (1748)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 46,
      tags: ["franklin","time","money"],
    },
    {
      id: 'phi-en-24',
      content: `To err is human, to forgive divine.`,
      source: 'Alexander Pope, An Essay on Criticism (1711)',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 35,
      tags: ["pope", "forgiveness", "humanity"],
    },
    {
      id: 'phi-en-25',
      content: `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`,
      source: 'Ralph Waldo Emerson — Self-Reliance (1841)',
      language: 'en',
      difficulty: 4,
      wordCount: 19,
      charCount: 110,
      tags: ["emerson","authenticity","self"],
    },
    {
      id: 'phi-en-26',
      content: `A room without books is like a body without a soul.`,
      source: 'Marcus Tullius Cicero — attributed (classical)',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["cicero","books","soul"],
    },
    {
      id: 'phi-en-27',
      content: `When you reach the end of your rope, tie a knot in it and hang on.`,
      source: 'Franklin D. Roosevelt — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 66,
      tags: ["fdr","perseverance","hope"],
    },
    {
      id: 'phi-en-28',
      content: `No man is an island, entire of itself.`,
      source: 'John Donne — Devotions upon Emergent Occasions (1624)',
      language: 'en',
      difficulty: 2,
      wordCount: 8,
      charCount: 38,
      tags: ["donne","community","connection"],
    },
    {
      id: 'phi-en-29',
      content: `Whatever you are, be a good one.`,
      source: 'Abraham Lincoln — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 32,
      tags: ["lincoln","excellence","integrity"],
    },
    {
      id: 'phi-en-30',
      content: `Do what you can, with what you have, where you are.`,
      source: 'Theodore Roosevelt — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["roosevelt","action","possibility"],
    },
    {
      id: 'phi-fr-31',
      content: `Suivant cette doctrine fondamentale, toutes nos spéculations quelconques sont inévitablement assujetties, soit chez l'individu, soit chez l'espèce, à passer successivement par trois états théoriques différents, que les dénominations habituelles de théologique, métaphysique et positif pourront ici qualifier suffisamment, pour ceux, du moins, qui en auront bien compris le vrai sens général.`,
      source: 'Auguste Comte — Discours sur l\'esprit positif (1844)',
      language: 'fr',
      difficulty: 4,
      wordCount: 51,
      charCount: 391,
      tags: ["comte", "positivisme", "science"],
    },
    {
      id: 'phi-fr-32',
      content: `Je forme une entreprise qui n'eut jamais d'exemple, et dont l'exécution n'aura point d'imitateur. Je veux montrer à mes semblables un homme dans toute la vérité de la nature, et cet homme, ce sera moi. Moi seul. Je sens mon cœur, et je connais les hommes.`,
      source: 'Jean-Jacques Rousseau — Les Confessions (1782)',
      language: 'fr',
      difficulty: 3,
      wordCount: 46,
      charCount: 255,
      tags: ["rousseau", "autobiographie", "introspection"],
    },
    {
      id: 'phi-fr-33',
      content: `Que signifie le rire ? Qu'y a-t-il au fond du risible ? Que trouverait-on de commun entre une grimace de pitre, un jeu de mots, un quiproquo de vaudeville, une scène de fine comédie ? Quelle distillation nous donnera l'essence, toujours la même, à laquelle tant de produits divers empruntent ou leur indiscrète odeur ou leur parfum délicat ?`,
      source: 'Henri Bergson — Le Rire : essai sur la signification du comique (1900)',
      language: 'fr',
      difficulty: 3,
      wordCount: 59,
      charCount: 341,
      tags: ["bergson", "rire", "esthétique"],
    },
    {
      id: 'phi-fr-34',
      content: `On déclame sans fin contre les passions ; on leur impute toutes les peines de l'homme, et l'on oublie qu'elles sont aussi la source de tous ses plaisirs. C'est dans sa constitution un élément dont on ne peut dire ni trop de bien ni trop de mal. Mais ce qui me donne de l'humeur, c'est qu'on ne les regarde jamais que du mauvais côté. On croirait faire injure à la raison, si l'on disait un mot en faveur de ses rivales ; cependant il n'y a que les passions, et les grandes passions, qui puissent élever l'âme aux grandes choses. Sans elles, plus de sublime, soit dans les mœurs, soit dans les ouvrages ; les beaux-arts retournent en enfance, et la vertu devient minutieuse.`,
      source: 'Denis Diderot — Pensées philosophiques (1746)',
      language: 'fr',
      difficulty: 4,
      wordCount: 124,
      charCount: 673,
      tags: ["diderot", "passions", "lumières"],
    },
    {
      id: 'phi-fr-35',
      content: `Il ne faut pas un grand art, une éloquence bien recherchée, pour prouver que des chrétiens doivent se tolérer les uns les autres. Je vais plus loin : je vous dis qu'il faut regarder tous les hommes comme nos frères. Quoi ! mon frère le Turc ? mon frère le Chinois ? le Juif ? le Siamois ? Oui, sans doute ; ne sommes-nous pas tous enfants du même père, et créatures du même Dieu ? Mais ces peuples nous méprisent ; mais ils nous traitent d'idolâtres ! Hé bien ! je leur dirai qu'ils ont grand tort.`,
      source: 'Voltaire — Traité sur la tolérance (1763)',
      language: 'fr',
      difficulty: 3,
      wordCount: 98,
      charCount: 498,
      tags: ["voltaire", "tolérance", "lumières"],
    },
    {
      id: 'phi-fr-36',
      content: `Meshuy c'est fait. Or les traits de ma peinture ne forvoyent point, quoy qu'ils se changent et diversifient. Le monde n'est qu'une branloire perenne. Toutes choses y branlent sans cesse : la terre, les rochers du Caucase, les pyramides d'Aegypte, et du branle public et du leur. La constance mesme n'est autre chose qu'un branle plus languissant. Je ne puis asseurer mon object. Il va trouble et chancelant, d'une yvresse naturelle. Je le prens en ce point, comme il est, en l'instant que je m'amuse à luy. Je ne peints pas l'estre. Je peints le passage.`,
      source: 'Michel de Montaigne — Essais, Livre III, chapitre 2, Du repentir (1588)',
      language: 'fr',
      difficulty: 5,
      wordCount: 96,
      charCount: 554,
      tags: ["montaigne", "scepticisme", "renaissance"],
    },
    {
      id: 'phi-en-31',
      content: `But it is not only the difficulty and labor, which men take in finding out of truth, nor again, that when it is found, it imposeth upon men's thoughts, that doth bring lies in favor; but a natural, though corrupt love, of the lie itself.`,
      source: 'Francis Bacon — Essays, "Of Truth" (1625)',
      language: 'en',
      difficulty: 4,
      wordCount: 45,
      charCount: 237,
      tags: ["bacon", "truth", "empiricism"],
    },
    {
      id: 'phi-en-32',
      content: `The less forcible and lively are commonly denominated Thoughts or Ideas. The other species want a name in our language, and in most others; I suppose, because it was not requisite for any, but philosophical purposes, to rank them under a general term or appellation.`,
      source: 'David Hume — An Enquiry Concerning Human Understanding (1748)',
      language: 'en',
      difficulty: 4,
      wordCount: 45,
      charCount: 266,
      tags: ["hume", "empiricism", "ideas"],
    },
    {
      id: 'phi-en-33',
      content: `I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.`,
      source: 'Henry David Thoreau — Walden (1854)',
      language: 'en',
      difficulty: 3,
      wordCount: 44,
      charCount: 212,
      tags: ["thoreau", "transcendentalism", "nature"],
    },
    {
      id: 'phi-en-34',
      content: `This Opinion I have at large examined already; and, I suppose, what I have said in the fore-going Book, will be much more easily admitted, when I have shewed, whence the Understanding may get all the Ideas it has, and by what ways and degrees they may come into the Mind; for which I shall appeal to every ones own Observation and Experience. Let us then suppose the Mind to be, as we say, white Paper, void of all Characters, without any Ideas; How comes it to be furnished? To this I answer, in one word, From Experience: In that, all our Knowledge is founded; and from that it ultimately derives it self.`,
      source: 'John Locke — An Essay Concerning Human Understanding (1690)',
      language: 'en',
      difficulty: 5,
      wordCount: 113,
      charCount: 607,
      tags: ["locke", "empiricism", "tabula rasa"],
    },
    {
      id: 'phi-en-35',
      content: `The object of this Essay is to assert one very simple principle, as entitled to govern absolutely the dealings of society with the individual in the way of compulsion and control, whether the means used be physical force in the form of legal penalties, or the moral coercion of public opinion. That principle is, that the sole end for which mankind are warranted, individually or collectively, in interfering with the liberty of action of any of their number, is self-protection. That the only purpose for which power can be rightfully exercised over any member of a civilised community, against his will, is to prevent harm to others.`,
      source: 'John Stuart Mill — On Liberty (1859)',
      language: 'en',
      difficulty: 4,
      wordCount: 107,
      charCount: 635,
      tags: ["mill", "liberty", "utilitarianism"],
    },
    {
      id: 'phi-en-36',
      content: `Suppose you should contradict yourself; what then? A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines. With consistency a great soul has simply nothing to do. He may as well concern himself with his shadow on the wall. Speak what you think now in hard words and to-morrow speak what to-morrow thinks in hard words again, though it contradict every thing you said to-day.—'Ah, so you shall be sure to be misunderstood.'—Is it so bad then to be misunderstood?`,
      source: 'Ralph Waldo Emerson — Self-Reliance (1841)',
      language: 'en',
      difficulty: 4,
      wordCount: 87,
      charCount: 518,
      tags: ["emerson", "individualism", "transcendentalism"],
    },
    {
      id: 'phi-en-37',
      content: `Near the end of March, 1845, I borrowed an axe and went down to the woods by Walden Pond, nearest to where I intended to build my house.`,
      source: 'Henry David Thoreau — Walden (1854)',
      language: 'en',
      difficulty: 2,
      wordCount: 28,
      charCount: 136,
      tags: ["thoreau", "transcendentalism", "chiffre"],
    },
  ],
};
