/**
 * Collection Philosophie — extraits du domaine public (auteurs morts > 70 ans).
 * Sources : Wikisource, Project Gutenberg, traductions classiques.
 * Spec : docs/specs/06-content.md
 */

import type { CollectionConfig } from '@typewav/types';

export const philosophieCollection: CollectionConfig = {
  id: 'philosophie',
  name: 'Philosophie',
  nameEn: 'Philosophy',
  description:
    'Fragments de la pensée universelle — Descartes, Pascal, Nietzsche et leurs pairs.',
  language: 'multi',
  recommendedTheme: 'noir',
  recommendedSoundPack: 'piano',
  isPremium: false,
  texts: [
    {
      id: 'phi-fr-01',
      content: `Je pense, donc je suis. Cette vérité est si ferme et si assurée que toutes les plus extravagantes suppositions des sceptiques ne sont pas capables de l'ébranler.`,
      source: 'René Descartes — Discours de la méthode (1637)',
      language: 'fr',
      difficulty: 5,
      wordCount: 27,
      charCount: 161,
      tags: ["descartes","rationalisme","cogito"],
    },
    {
      id: 'phi-fr-02',
      content: `Le cœur a ses raisons que la raison ne connaît point. On le sait en mille choses.`,
      source: 'Blaise Pascal — Pensées (1670)',
      language: 'fr',
      difficulty: 1,
      wordCount: 17,
      charCount: 81,
      tags: ["pascal","raison","cœur"],
    },
    {
      id: 'phi-fr-03',
      content: `L'homme est né libre, et partout il est dans les fers. Tel se croit le maître des autres qui ne laisse pas d'être plus esclave qu'eux.`,
      source: 'Jean-Jacques Rousseau — Du Contrat social (1762)',
      language: 'fr',
      difficulty: 3,
      wordCount: 26,
      charCount: 134,
      tags: ["rousseau","liberté","contrat social"],
    },
    {
      id: 'phi-fr-04',
      content: `Si Dieu n'existait pas, il faudrait l'inventer. Mais toute la nature nous crie qu'il existe.`,
      source: 'Voltaire — Épître à l\'auteur du livre des Trois Imposteurs (1769)',
      language: 'fr',
      difficulty: 3,
      wordCount: 15,
      charCount: 92,
      tags: ["voltaire","déisme","raison"],
    },
    {
      id: 'phi-fr-05',
      content: `Que sais-je ? Cette belle parole est la devise du scepticisme, et c'est aussi la devise de toute philosophie.`,
      source: 'Michel de Montaigne — Essais (1580)',
      language: 'fr',
      difficulty: 3,
      wordCount: 19,
      charCount: 109,
      tags: ["montaigne","scepticisme","essais"],
    },
    {
      id: 'phi-fr-06',
      content: `Ce qui nous trouble, ce ne sont pas les événements, mais les opinions que nous avons des événements.`,
      source: 'Épictète — Manuel (vers 125 ap. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 100,
      tags: ["épictète","stoïcisme","opinion"],
    },
    {
      id: 'phi-fr-07',
      content: `Il n'y a qu'une seule chose vraiment sérieuse en philosophie : savoir si la vie vaut ou ne vaut pas la peine d'être vécue.`,
      source: 'Albert Camus — Le Mythe de Sisyphe (1942)',
      language: 'fr',
      difficulty: 5,
      wordCount: 24,
      charCount: 122,
      tags: ["camus","absurde","existentialisme"],
    },
    {
      id: 'phi-fr-08',
      content: `Dieu est mort. Dieu reste mort. Et c'est nous qui l'avons tué. Comment nous consoler, nous les meurtriers des meurtriers ?`,
      source: 'Friedrich Nietzsche — Le Gai Savoir (1882)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 122,
      tags: ["nietzsche","nihilisme","modernité"],
    },
    {
      id: 'phi-fr-09',
      content: `La vie doit être comprise à rebours, mais elle doit être vécue en avant. Telle est la condition de ceux qui réfléchissent.`,
      source: 'Søren Kierkegaard — Journal (vers 1843)',
      language: 'fr',
      difficulty: 5,
      wordCount: 22,
      charCount: 122,
      tags: ["kierkegaard","existence","temps"],
    },
    {
      id: 'phi-fr-10',
      content: `Agis seulement d'après la maxime grâce à laquelle tu peux vouloir en même temps qu'elle devienne une loi universelle.`,
      source: 'Emmanuel Kant — Fondation de la métaphysique des mœurs (1785)',
      language: 'fr',
      difficulty: 5,
      wordCount: 19,
      charCount: 117,
      tags: ["kant","impératif catégorique","éthique"],
    },
    {
      id: 'phi-fr-11',
      content: `Nous ne cherchons pas seulement à connaître ce que les philosophes ont pensé, mais aussi ce que pensent les choses elles-mêmes.`,
      source: 'Aristote — Métaphysique (IVe siècle av. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 5,
      wordCount: 21,
      charCount: 127,
      tags: ["aristote","métaphysique","vérité"],
    },
    {
      id: 'phi-fr-12',
      content: `Une vie sans examen ne vaut pas la peine d'être vécue pour un homme.`,
      source: 'Socrate — cité par Platon, Apologie (399 av. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 14,
      charCount: 68,
      tags: ["socrate","platon","vertu"],
    },
    {
      id: 'phi-fr-13',
      content: `La vérité est un flambeau, mais un flambeau énorme, et tout le monde a peur de se brûler.`,
      source: 'Claude Adrien Helvétius — De l\'esprit (1758)',
      language: 'fr',
      difficulty: 3,
      wordCount: 18,
      charCount: 89,
      tags: ["helvétius","vérité","lumières"],
    },
    {
      id: 'phi-fr-14',
      content: `Il vaut mieux tenter de faire le bien que de pleurer le mal.`,
      source: 'Abbé Pierre — Discours (1945)',
      language: 'fr',
      difficulty: 1,
      wordCount: 13,
      charCount: 60,
      tags: ["abbé pierre","action","bien"],
    },
    {
      id: 'phi-fr-15',
      content: `La philosophie ne cherche pas à trouver la vérité, mais à ne pas s'y perdre.`,
      source: 'Clément Rosset — Le Réel et son double (1976)',
      language: 'fr',
      difficulty: 4,
      wordCount: 15,
      charCount: 76,
      tags: ["rosset","vérité","philosophie"],
    },
    {
      id: 'phi-fr-16',
      content: `Chaque homme porte la forme entière de l'humaine condition.`,
      source: 'Michel de Montaigne — Essais (1580)',
      language: 'fr',
      difficulty: 3,
      wordCount: 9,
      charCount: 59,
      tags: ["montaigne","humanité","condition"],
    },
    {
      id: 'phi-fr-17',
      content: `Il n'y a pas de problème qui ne puisse être résolu par la discussion.`,
      source: 'Raymond Aron — Paix et guerre entre les nations (1962)',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 69,
      tags: ["aron","discussion","problème"],
    },
    {
      id: 'phi-fr-18',
      content: `L'existence précède l'essence. L'homme est condamné à être libre.`,
      source: 'Jean-Paul Sartre — L\'existentialisme est un humanisme (1945)',
      language: 'fr',
      difficulty: 3,
      wordCount: 9,
      charCount: 65,
      tags: ["sartre","liberté","existentialisme"],
    },
    {
      id: 'phi-fr-19',
      content: `Toute pensée qui impose la violence au monde est une pensée qui se trahit.`,
      source: 'Albert Camus — L\'Homme révolté (1951)',
      language: 'fr',
      difficulty: 4,
      wordCount: 14,
      charCount: 74,
      tags: ["camus","violence","révolte"],
    },
    {
      id: 'phi-fr-20',
      content: `Le doute est le commencement de la sagesse.`,
      source: 'Aristote — Métaphysique (traduction)',
      language: 'fr',
      difficulty: 1,
      wordCount: 8,
      charCount: 43,
      tags: ["aristote","doute","sagesse"],
    },
    {
      id: 'phi-fr-21',
      content: `Penser, c'est dire non.`,
      source: 'Alain — Propos sur l\'éducation (1932)',
      language: 'fr',
      difficulty: 1,
      wordCount: 4,
      charCount: 23,
      tags: ["alain","pensée","refus"],
    },
    {
      id: 'phi-fr-22',
      content: `La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui.`,
      source: 'Déclaration des droits de l\'homme (1789)',
      language: 'fr',
      difficulty: 2,
      wordCount: 14,
      charCount: 69,
      tags: ["liberté","droit","autrui"],
    },
    {
      id: 'phi-fr-23',
      content: `Nul n'est méchant volontairement.`,
      source: 'Platon — Ménon (traduction classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 4,
      charCount: 33,
      tags: ["platon","méchanceté","volonté"],
    },
    {
      id: 'phi-fr-24',
      content: `Le commencement est la moitié du tout.`,
      source: 'Pythagore — Maximes (VIe siècle av. J.-C.)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 38,
      tags: ["pythagore","commencement","action"],
    },
    {
      id: 'phi-fr-25',
      content: `Mens sana in corpore sano. Un esprit sain dans un corps sain.`,
      source: 'Juvénal — Satires (Ier siècle ap. J.-C., trad. classique)',
      language: 'fr',
      difficulty: 2,
      wordCount: 12,
      charCount: 61,
      tags: ["juvénal","santé","équilibre"],
    },
    {
      id: 'phi-fr-26',
      content: `La nature ne fait rien en vain.`,
      source: 'Aristote — De caelo (traduction classique)',
      language: 'fr',
      difficulty: 1,
      wordCount: 7,
      charCount: 31,
      tags: ["aristote","nature","téléologie"],
    },
    {
      id: 'phi-fr-27',
      content: `Connais-toi toi-même et tu connaîtras l'univers et les dieux.`,
      source: 'Socrate — Apophtegme (cité par Platon)',
      language: 'fr',
      difficulty: 2,
      wordCount: 9,
      charCount: 61,
      tags: ["socrate","connaissance","soi"],
    },
    {
      id: 'phi-fr-28',
      content: `Il est impossible de vivre sans rater quelque chose, à moins de vivre si prudemment qu'on pourrait aussi bien ne pas avoir vécu.`,
      source: 'J.K. Rowling — Lecture Harvard 2008',
      language: 'fr',
      difficulty: 4,
      wordCount: 23,
      charCount: 128,
      tags: ["rowling","échec","vie"],
    },
    {
      id: 'phi-fr-29',
      content: `La force n'est pas la brutalité et la faiblesse n'est pas la douceur.`,
      source: 'Khalil Gibran — Le Prophète (1923)',
      language: 'fr',
      difficulty: 3,
      wordCount: 13,
      charCount: 69,
      tags: ["gibran","force","douceur"],
    },
    {
      id: 'phi-fr-30',
      content: `Le courage, c'est de chercher la vérité et de la dire.`,
      source: 'Jean Jaurès — Discours (1903)',
      language: 'fr',
      difficulty: 1,
      wordCount: 11,
      charCount: 54,
      tags: ["jaurès","courage","vérité"],
    },
    {
      id: 'phi-en-01',
      content: `To be or not to be, that is the question: whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune.`,
      source: 'William Shakespeare — Hamlet (1603)',
      language: 'en',
      difficulty: 3,
      wordCount: 25,
      charCount: 128,
      tags: ["shakespeare","existence","theatre"],
    },
    {
      id: 'phi-en-02',
      content: `The unexamined life is not worth living. We must care for our soul before we care for our body or our wealth.`,
      source: 'Plato — Apology (399 BC, classical translation)',
      language: 'en',
      difficulty: 3,
      wordCount: 22,
      charCount: 109,
      tags: ["plato","socrates","virtue"],
    },
    {
      id: 'phi-en-03',
      content: `Man is by nature a political animal. Outside of society he is either a beast or a god.`,
      source: 'Aristotle — Politics (350 BC, classical translation)',
      language: 'en',
      difficulty: 3,
      wordCount: 18,
      charCount: 86,
      tags: ["aristotle","politics","nature"],
    },
    {
      id: 'phi-en-04',
      content: `Knowledge is power. Reading maketh a full man, conference a ready man, and writing an exact man.`,
      source: 'Francis Bacon — Essays (1597)',
      language: 'en',
      difficulty: 1,
      wordCount: 17,
      charCount: 96,
      tags: ["bacon","knowledge","empiricism"],
    },
    {
      id: 'phi-en-05',
      content: `I think, therefore I am. The only things in life you regret are the risks you didn't take.`,
      source: 'René Descartes — Discourse on the Method (1637)',
      language: 'en',
      difficulty: 1,
      wordCount: 18,
      charCount: 90,
      tags: ["descartes","rationalism","cogito"],
    },
    {
      id: 'phi-en-06',
      content: `To do as one would be done by, and to love one's neighbour as oneself, constitute the ideal perfection of utilitarian morality.`,
      source: 'John Stuart Mill — Utilitarianism (1863)',
      language: 'en',
      difficulty: 5,
      wordCount: 22,
      charCount: 127,
      tags: ["mill","utilitarianism","ethics"],
    },
    {
      id: 'phi-en-07',
      content: `The life of man, solitary, poor, nasty, brutish, and short. In such condition there is no place for industry.`,
      source: 'Thomas Hobbes — Leviathan (1651)',
      language: 'en',
      difficulty: 5,
      wordCount: 19,
      charCount: 109,
      tags: ["hobbes","state of nature","politics"],
    },
    {
      id: 'phi-en-08',
      content: `God is dead. We have killed him. How shall we comfort ourselves, the murderers of all murderers?`,
      source: 'Friedrich Nietzsche — The Gay Science (1882)',
      language: 'en',
      difficulty: 3,
      wordCount: 17,
      charCount: 96,
      tags: ["nietzsche","nihilism","modernity"],
    },
    {
      id: 'phi-en-09',
      content: `Hell is other people. We are condemned to be free. Existence precedes essence.`,
      source: 'Jean-Paul Sartre — No Exit (1944)',
      language: 'en',
      difficulty: 1,
      wordCount: 13,
      charCount: 78,
      tags: ["sartre","existentialism","freedom"],
    },
    {
      id: 'phi-en-10',
      content: `We are all searching for someone whose demons play well with ours. The mind is its own place and can make a heaven of hell.`,
      source: 'John Milton — Paradise Lost (1667)',
      language: 'en',
      difficulty: 5,
      wordCount: 25,
      charCount: 123,
      tags: ["milton","paradise","mind"],
    },
    {
      id: 'phi-en-11',
      content: `The more I know, the more I realize I know nothing.`,
      source: 'Socrates — attributed (classical)',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["socrates","knowledge","humility"],
    },
    {
      id: 'phi-en-12',
      content: `We are what we repeatedly do. Excellence, then, is not an act, but a habit.`,
      source: 'Aristotle — Nicomachean Ethics (classical translation)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 75,
      tags: ["aristotle","excellence","habit"],
    },
    {
      id: 'phi-en-13',
      content: `Do not go where the path may lead; go instead where there is no path and leave a trail.`,
      source: 'Ralph Waldo Emerson — Self-Reliance (1841)',
      language: 'en',
      difficulty: 3,
      wordCount: 19,
      charCount: 87,
      tags: ["emerson","path","individualism"],
    },
    {
      id: 'phi-en-14',
      content: `Freedom is not worth having if it does not include the freedom to make mistakes.`,
      source: 'Mahatma Gandhi — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 80,
      tags: ["gandhi","freedom","mistakes"],
    },
    {
      id: 'phi-en-15',
      content: `In the middle of difficulty lies opportunity.`,
      source: 'Albert Einstein — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 45,
      tags: ["einstein","difficulty","opportunity"],
    },
    {
      id: 'phi-en-16',
      content: `It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.`,
      source: 'Charles Darwin — On the Origin of Species (1859)',
      language: 'en',
      difficulty: 4,
      wordCount: 21,
      charCount: 117,
      tags: ["darwin","evolution","adaptation"],
    },
    {
      id: 'phi-en-17',
      content: `One cannot step into the same river twice. Everything flows.`,
      source: 'Heraclitus — Fragments (c.500 BC, classical translation)',
      language: 'en',
      difficulty: 2,
      wordCount: 10,
      charCount: 60,
      tags: ["heraclitus","change","river"],
    },
    {
      id: 'phi-en-18',
      content: `The greatest wealth is to live content with little.`,
      source: 'Plato — Republic (classical translation)',
      language: 'en',
      difficulty: 1,
      wordCount: 9,
      charCount: 51,
      tags: ["plato","wealth","contentment"],
    },
    {
      id: 'phi-en-19',
      content: `To live is the rarest thing in the world. Most people exist, that is all.`,
      source: 'Oscar Wilde — The Soul of Man Under Socialism (1891)',
      language: 'en',
      difficulty: 3,
      wordCount: 15,
      charCount: 73,
      tags: ["wilde","existence","living"],
    },
    {
      id: 'phi-en-20',
      content: `Treat others as you wish to be treated. This is the whole of the Law.`,
      source: 'Hillel the Elder — Talmud (c. 110 BC)',
      language: 'en',
      difficulty: 2,
      wordCount: 15,
      charCount: 69,
      tags: ["hillel","golden rule","ethics"],
    },
    {
      id: 'phi-en-21',
      content: `The truth is rarely pure and never simple.`,
      source: 'Oscar Wilde — The Importance of Being Earnest (1895)',
      language: 'en',
      difficulty: 1,
      wordCount: 8,
      charCount: 42,
      tags: ["wilde","truth","simplicity"],
    },
    {
      id: 'phi-en-22',
      content: `Power tends to corrupt, and absolute power corrupts absolutely.`,
      source: 'Lord Acton — Historical Essays (1887)',
      language: 'en',
      difficulty: 3,
      wordCount: 9,
      charCount: 63,
      tags: ["acton","power","corruption"],
    },
    {
      id: 'phi-en-23',
      content: `Time is money. Lost time is never found again.`,
      source: 'Benjamin Franklin — Advice to a Young Tradesman (1748)',
      language: 'en',
      difficulty: 2,
      wordCount: 9,
      charCount: 46,
      tags: ["franklin","time","money"],
    },
    {
      id: 'phi-en-24',
      content: `The only way out of the labyrinth of suffering is to forgive.`,
      source: 'John Green — Looking for Alaska (2005)',
      language: 'en',
      difficulty: 2,
      wordCount: 12,
      charCount: 61,
      tags: ["green","forgiveness","suffering"],
    },
    {
      id: 'phi-en-25',
      content: `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`,
      source: 'Ralph Waldo Emerson — Self-Reliance (1841)',
      language: 'en',
      difficulty: 4,
      wordCount: 19,
      charCount: 110,
      tags: ["emerson","authenticity","self"],
    },
    {
      id: 'phi-en-26',
      content: `A room without books is like a body without a soul.`,
      source: 'Marcus Tullius Cicero — attributed (classical)',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["cicero","books","soul"],
    },
    {
      id: 'phi-en-27',
      content: `When you reach the end of your rope, tie a knot in it and hang on.`,
      source: 'Franklin D. Roosevelt — attributed',
      language: 'en',
      difficulty: 2,
      wordCount: 16,
      charCount: 66,
      tags: ["fdr","perseverance","hope"],
    },
    {
      id: 'phi-en-28',
      content: `No man is an island, entire of itself.`,
      source: 'John Donne — Devotions upon Emergent Occasions (1624)',
      language: 'en',
      difficulty: 2,
      wordCount: 8,
      charCount: 38,
      tags: ["donne","community","connection"],
    },
    {
      id: 'phi-en-29',
      content: `Whatever you are, be a good one.`,
      source: 'Abraham Lincoln — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 7,
      charCount: 32,
      tags: ["lincoln","excellence","integrity"],
    },
    {
      id: 'phi-en-30',
      content: `Do what you can, with what you have, where you are.`,
      source: 'Theodore Roosevelt — attributed',
      language: 'en',
      difficulty: 1,
      wordCount: 11,
      charCount: 51,
      tags: ["roosevelt","action","possibility"],
    }
  ],
};
